import { AB100_SYLLABUS } from "./ab100-syllabus.ts";
import { buildersFor, citeFrom } from "./question-builders.ts";
import type { Question } from "./questions";

/**
 * MAINTAINED BY HAND. Standalone AB-100 items in the interactive formats the real exam
 * uses: multiple choice of five (one or two keyed answers), drag-and-drop matching and
 * ordering, and dropdown gap-fill. Spread by the published domain weights (Plan 25–30%,
 * Design 25–30%, Deploy 40–45%), favoring the least-cited skills-measured bullets.
 *
 * Authoring convention (see question-builders.ts): the right answer comes first.
 */
const { choose, match, sequence, gaps } = buildersFor("ab100");
const cite = citeFrom(AB100_SYLLABUS);

export const AB100_FORMAT_QUESTIONS: Question[] = [
  // ===== Plan AI-powered business solutions =====
  sequence({
    id: "ab-fm-p01", domain: "ab-plan", topic: "AI adoption phases",
    prompt: "An organization is starting its AI adoption with the Cloud Adoption Framework for Azure. Arrange the phases in the order the framework describes.",
    steps: [
      "AI Strategy: decide which business outcomes AI should deliver",
      "AI Plan: assess skills and data, and choose the priority use cases",
      "AI Ready: prepare the Azure landing zone for AI workloads",
      "Govern, Secure, and Manage AI as continuous processes",
    ],
    distractors: ["License every user before any outcomes are defined", "Train a custom model before the data is assessed"],
    explanation: "The framework runs AI Strategy, AI Plan, and AI Ready in sequence, then treats Govern, Secure, and Manage as continuous processes that are revisited over time. Licensing everyone before outcomes are defined and training a custom model before assessing data invert the order the framework recommends.",
    syllabus: cite("Implement the AI adoption process from the Cloud Adoption Framework for Azure", "https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/ai/", "AI adoption in the Cloud Adoption Framework"),
  }),
  match({
    id: "ab-fm-p02", domain: "ab-plan", topic: "Build, buy, or extend",
    prompt: "Match each business requirement to the build, buy, or extend decision the architect should recommend for the AI solution.",
    targets: [
      "Sellers need CRM-aware email summaries in Outlook",
      "Employees need HR policy answers in Copilot Chat from SharePoint",
      "A pricing engine must combine a proprietary model with ERP data",
    ],
    answers: [
      "Buy: Microsoft 365 Copilot for Sales",
      "Extend: a declarative agent in Microsoft 365 Copilot",
      "Build: a custom agent in Microsoft Foundry",
    ],
    distractors: ["Build: a new CRM system to hold the pricing data", "Buy: a chatbot with no Microsoft 365 integration"],
    explanation: "A packaged product already covers CRM-aware email in Outlook, so buy it. HR answers from SharePoint inside Copilot Chat need only a declarative agent that extends Microsoft 365 Copilot. A proprietary model combined with ERP data is differentiating work that justifies a custom Foundry agent. Building a CRM and buying a chatbot outside Microsoft 365 each add a system without meeting any of these needs.",
    syllabus: cite("Analyze whether to build, buy, or extend AI components for business solutions", "https://learn.microsoft.com/dynamics365/copilot/ai-get-started", "Agents, Copilot, and AI capabilities in Dynamics 365 apps"),
  }),
  match({
    id: "ab-fm-p03", domain: "ab-plan", topic: "Platform per agent",
    prompt: "A multi-agent solution has three parts. Match each part to the platform that fits it best.",
    targets: [
      "An employee assistant used inside Teams and Outlook",
      "A low-code customer service agent built on Dynamics 365 connectors",
      "A code-first agent that orchestrates custom models and tools at scale",
    ],
    answers: ["Microsoft 365 Copilot", "Copilot Studio", "Microsoft Foundry"],
    distractors: ["Power BI", "Power Pages"],
    explanation: "Microsoft 365 Copilot meets employees where they already work, Copilot Studio suits low-code agents that use Power Platform and Dynamics 365 connectors, and Microsoft Foundry gives pro developers code-first control of models and tools. Power BI is for analytics and Power Pages for external websites; neither hosts these agents.",
    syllabus: cite("Design a multi-agent solution by using platforms such as Microsoft 365 Copilot, Copilot Studio, and Microsoft Foundry", "https://learn.microsoft.com/microsoft-copilot-studio/guidance/multi-agent-patterns", "Multi-agent orchestration patterns"),
  }),
  match({
    id: "ab-fm-p04", domain: "ab-plan", topic: "When to customize models",
    prompt: "Match each requirement for an AI solution to the approach the architect should choose.",
    targets: [
      "Answer from policy documents that change every week",
      "Write every summary in a strict house style across thousands of documents",
      "Label notes with 40 proprietary defect codes",
      "Draft a one-off summary of a short report",
    ],
    answers: ["Retrieval-augmented generation", "Fine-tuning", "A custom classification model", "Prompt engineering"],
    distractors: ["Pretraining a new foundation model", "A larger context window alone"],
    explanation: "Weekly-changing documents belong in retrieval rather than in model weights, a consistent house style at volume is what fine-tuning is for, a fixed proprietary label set suits a custom classifier, and a one-off summary needs only a good prompt. Pretraining a foundation model is never justified here, and a larger context window neither keeps content current nor enforces style.",
    syllabus: cite("Determine when custom AI models should be created", "https://learn.microsoft.com/azure/ai-foundry/concepts/fine-tuning-overview", "Fine-tuning in Microsoft Foundry"),
  }),
  match({
    id: "ab-fm-p05", domain: "ab-plan", topic: "Data for several AI systems",
    prompt: "Several agents will reuse the same business data. Match each data set to where the architect should organize it.",
    targets: [
      "Customer master data used by several agents",
      "Five years of sales history for analytics agents",
      "Policy documents used for grounding",
    ],
    answers: [
      "One governed table in Dataverse, shared through connectors",
      "A lakehouse in Microsoft Fabric",
      "SharePoint libraries with metadata and permissions",
    ],
    distractors: ["Copies pasted into each agent's instructions", "Files in each maker's personal OneDrive"],
    explanation: "Shared master data lives once in a governed Dataverse table, large analytical history suits a Fabric lakehouse, and grounding documents belong in SharePoint libraries whose metadata and permissions carry through to retrieval. Copies in instructions go stale and bypass security, and personal OneDrive folders are neither governed nor shared.",
    syllabus: cite("Organize business solution data to be available for other AI systems", "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/data-architecture-plan", "Data architecture for AI agents"),
  }),
  gaps({
    id: "ab-fm-p06", domain: "ab-plan", topic: "Prompt library entries",
    prompt: "Complete the guideline for entries in a company's Copilot prompt library.",
    template: "Every prompt has an {0}, a description of its {1}, and is retested against {2} whenever the underlying model changes.",
    blanks: [
      ["owner and version", "creation date only", "anonymous author"],
      ["purpose and inputs", "marketing tagline", "banned-user list"],
      ["a saved test set", "the author's recollection", "one live chat"],
    ],
    explanation: "An owner and a version make each prompt maintainable, a description of purpose and inputs tells people when to use it, and a saved test set shows whether a model change broke it. A creation date or an anonymous author gives no one responsibility, taglines and user lists do not help reuse, and memory or a single chat is not a repeatable test.",
    syllabus: cite("Provide guidelines for creating a prompt library", "https://learn.microsoft.com/microsoft-copilot-studio/prompts-overview", "Prompts in Copilot Studio"),
  }),
  gaps({
    id: "ab-fm-p07", domain: "ab-plan", topic: "Prompt engineering guideline",
    prompt: "Complete the prompt engineering guideline an architect publishes for makers of AI-powered business solutions.",
    template: "State the {0} first, give the model {1} to ground its answer, show {2} of the expected output format, and say what to do when the context lacks the answer.",
    blanks: [
      ["task and audience", "model version", "author's name"],
      ["the relevant source content", "every document in the tenant", "unrelated examples"],
      ["one or two examples", "a hundred examples", "no examples"],
    ],
    explanation: "Clear prompts state the task and audience, provide only the source content relevant to the question, show one or two examples of the format, and give an instruction for missing information. Model versions and author names do not guide the output, the whole tenant floods the context, unrelated examples mislead, a hundred examples waste tokens, and no example leaves the format to chance.",
    syllabus: cite("Provide prompt engineering guidelines and techniques for AI-powered business solutions", "https://learn.microsoft.com/microsoft-copilot-studio/prompts-overview", "Prompts in Copilot Studio"),
  }),
  gaps({
    id: "ab-fm-p08", domain: "ab-plan", topic: "Routing by complexity",
    prompt: "Complete the architect's proposal for lowering model cost in a Microsoft Foundry agent solution.",
    template: "Deploy {0} so that simple requests go to {1} models and complex ones to {2} models, lowering cost without changing the agent's code.",
    blanks: [
      ["model router", "a fine-tuned model", "a batch deployment"],
      ["smaller, cheaper", "larger, slower", "image generation"],
      ["more capable reasoning", "smaller, cheaper", "speech transcription"],
    ],
    explanation: "Model router is deployed once and chooses a model per request, sending simple prompts to smaller, cheaper models and complex ones to more capable reasoning models. A fine-tuned model or a batch deployment serves one model, sending complex requests to small models defeats the purpose, and image generation and speech transcription models do not answer chat requests.",
    syllabus: cite("Implement a model router to intelligently route requests to the most suitable model", "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router", "Model router for Microsoft Foundry"),
  }),
  gaps({
    id: "ab-fm-p09", domain: "ab-plan", topic: "Where small models fit",
    prompt: "Complete the architect's guidance on customized small language models in the solution.",
    template: "A customized small language model suits {0} tasks that need {1} and can run {2}, while open-ended research questions stay with a larger model.",
    blanks: [
      ["narrow, repetitive", "open-ended creative", "multi-domain research"],
      ["low latency and low cost", "the broadest world knowledge", "long multi-step reasoning"],
      ["close to the data, even at the edge", "only in one public region", "without any evaluation"],
    ],
    explanation: "Small language models do best on narrow, repeated tasks where low latency and cost matter, and their size lets them run close to the data, even on edge devices. Open-ended, broad-knowledge, and long-reasoning work suits larger models, small models are not limited to one region, and no model should ship without evaluation.",
    syllabus: cite("Develop the use cases for customized small language models for the solution", "https://learn.microsoft.com/azure/ai-foundry/concepts/fine-tuning-overview", "Fine-tuning in Microsoft Foundry"),
  }),
  choose({
    id: "ab-fm-p10", domain: "ab-plan", topic: "First candidates for autonomy",
    prompt: "Which two processes are strong first candidates for an autonomous agent in a business solution? Each correct answer presents part of the solution.",
    options: [
      "Matching supplier invoices to purchase orders within clear tolerances",
      "Routing inbound email to the right queue based on its content",
      "Approving employee terminations that line managers recommend each week",
      "Setting next year's pricing strategy for the whole product range",
      "Granting credit limit increases without any human review",
    ],
    explanation: "Invoice matching with clear tolerances and email routing are high-volume, rule-bounded, and reversible, which suits autonomy. Terminations, pricing strategy, and credit decisions carry significant consequences and judgment, so an agent can assist with them but should not decide alone.",
    syllabus: cite("Assess the use of agents in task automation, data analytics, and decision-making", "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process", "Process to build agents across your organization"),
  }),
  choose({
    id: "ab-fm-p11", domain: "ab-plan", topic: "Blocking data findings",
    prompt: "An HR agent will be grounded on 12,000 SharePoint documents. Which two findings should block launch until they are fixed? Each correct answer presents part of the solution.",
    options: [
      "Three conflicting versions of the leave policy are all published",
      "Salary files are shared with everyone in the organization",
      "Some documents use a different font from the corporate template",
      "The documents are spread across several SharePoint site collections",
      "Some of the files are PDFs rather than Word documents",
    ],
    explanation: "Conflicting published versions make answers inaccurate, and overshared salary files would let the agent surface them to anyone. Fonts, spreading content across site collections, and file formats do not affect whether answers are accurate or appropriately restricted.",
    syllabus: cite("Review data for grounding, including accuracy, relevance, timeliness, cleanliness, and availability", "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/data-architecture-plan", "Data architecture for AI agents"),
  }),
  choose({
    id: "ab-fm-p12", domain: "ab-plan", topic: "Starting the agent strategy",
    correctCount: 1,
    prompt: "A company's first agent initiative has many ideas and a small budget. What should the architect's strategy do first?",
    options: [
      "Rank use cases by value and feasibility, then start with one",
      "Build an agent for every department at the same time",
      "Choose the largest available model for every scenario",
      "Train a custom model before running any pilot at all",
      "Wait until a complete enterprise data platform has been finished",
    ],
    explanation: "Ranking use cases by business value and feasibility and starting with one proves value quickly within the budget. Building for every department spreads the budget thin, the largest model raises cost without addressing fit, a custom model before any pilot is premature, and waiting for a perfect data platform delays value indefinitely.",
    syllabus: cite("Design the strategy for building AI and agents in business solutions", "https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/ai/strategy", "AI adoption: Strategy"),
  }),
  choose({
    id: "ab-fm-p13", domain: "ab-plan", topic: "Center of Excellence elements",
    prompt: "Which two elements belong in a Microsoft AI Center of Excellence for agents? Each correct answer presents part of the solution.",
    options: [
      "An inventory of agents with owners and review dates",
      "Training and reusable templates for makers",
      "A rule that only the IT department may build agents",
      "One model that every scenario is required to use",
      "Disabling every environment that IT does not own",
    ],
    explanation: "A Center of Excellence balances governance, such as an owned and reviewed inventory, with enablement, such as training and reusable templates. Restricting building to IT, forcing one model everywhere, and disabling other environments block adoption instead of guiding it.",
    syllabus: cite("Include the elements of the Microsoft AI Center of Excellence", "https://learn.microsoft.com/power-platform/guidance/adoption/methodology", "Power Platform adoption methodology"),
  }),
  choose({
    id: "ab-fm-p14", domain: "ab-plan", topic: "Total cost of ownership",
    prompt: "Which two costs belong in the total cost of ownership of a Copilot Studio agent solution? Each correct answer presents part of the solution.",
    options: [
      "Copilot Studio capacity consumed by conversations and actions",
      "Ongoing effort to maintain knowledge sources and test sets",
      "Revenue earned from the customers who used the agent this year",
      "Hours that employees saved because of the agent",
      "Existing CRM licenses that do not change with the agent",
    ],
    explanation: "Total cost of ownership includes consumption, such as Copilot Studio capacity, and the ongoing effort to maintain knowledge and tests. Revenue and hours saved are benefits on the other side of the ROI calculation, and CRM licenses that exist regardless of the agent are not a cost of it.",
    syllabus: cite("Select ROI criteria for AI-powered business solutions, including the total cost of ownership", "https://learn.microsoft.com/microsoft-copilot-studio/requirements-messages-management", "Copilot Studio capacity and message management"),
  }),
  choose({
    id: "ab-fm-p15", domain: "ab-plan", topic: "Two Dynamics 365 apps",
    prompt: "A service agent needs data from Dynamics 365 Customer Service and Dynamics 365 Field Service. Which two design choices keep its answers consistent? Each correct answer presents part of the solution.",
    options: [
      "Use Dataverse as the shared data layer for both apps",
      "Define one owner for shared entities such as customer and asset",
      "Copy the case data into each app with a scheduled nightly batch job",
      "Let each app keep its own definition of the customer",
      "Let the agent write directly to both apps' databases",
    ],
    explanation: "Both apps run on Dataverse, so a shared data layer with one owner for each shared entity gives the agent a single, consistent version of customers and assets. Nightly copies drift, separate customer definitions conflict, and writing directly to databases bypasses business logic and security.",
    syllabus: cite("Design AI solutions that use multiple Dynamics 365 apps", "https://learn.microsoft.com/dynamics365/copilot/ai-get-started", "Agents, Copilot, and AI capabilities in Dynamics 365 apps"),
  }),

  // ===== Design AI-powered business solutions =====
  match({
    id: "ab-fm-d01", domain: "ab-design", topic: "Agent types",
    prompt: "Match each requirement to the type of Copilot Studio agent that fits it.",
    targets: [
      "Answer employee questions when someone asks",
      "Complete a defined multistep task when a user starts it",
      "Watch a shared mailbox and act on events with no user present",
    ],
    answers: ["Prompt and response agent", "Task agent", "Autonomous agent"],
    distractors: ["Static FAQ page", "Scheduled report"],
    explanation: "Prompt and response agents answer on request, task agents carry out a defined multistep task for a user, and autonomous agents react to triggers and act without a user present, within limits the design sets. A static FAQ page and a scheduled report are not agents.",
    syllabus: cite("Design autonomous agents", "https://learn.microsoft.com/microsoft-copilot-studio/guidance/autonomous-agents", "Design autonomous agent capabilities"),
  }),
  match({
    id: "ab-fm-d02", domain: "ab-design", topic: "Understanding approach",
    prompt: "Match each scenario to the language-understanding approach the architect should choose in Copilot Studio.",
    targets: [
      "A bank already owns a trained model with hundreds of intents",
      "Answers must combine knowledge, tools, and topics flexibly",
      "A handful of fixed topics triggered by clear phrases",
    ],
    answers: ["Conversational language understanding", "Generative orchestration", "Classic trigger phrases"],
    distractors: ["Regular expressions alone", "Keyword search in SharePoint"],
    explanation: "An existing CLU model with many intents can be reused through conversational language understanding, generative orchestration picks among knowledge, tools, and topics for open-ended requests, and a few well-defined topics work with classic trigger phrases. Regular expressions and keyword search do not understand intent.",
    syllabus: cite("Determine when to use standard natural language processing, conversational language understanding, or generative AI orchestration in Copilot Studio", "https://learn.microsoft.com/microsoft-copilot-studio/advanced-generative-actions", "Generative orchestration in Copilot Studio"),
  }),
  match({
    id: "ab-fm-d03", domain: "ab-design", topic: "Extending an agent",
    prompt: "Match each need to the Copilot Studio extensibility option that fits it.",
    targets: [
      "Call a partner REST API described by OpenAPI",
      "Use a server's tools that change often, without republishing",
      "Operate a desktop app that has no API",
      "Run a deterministic multistep business process",
    ],
    answers: ["Custom connector", "Model Context Protocol server", "Computer use", "Agent flow"],
    distractors: ["Knowledge source", "Adaptive card"],
    explanation: "A custom connector wraps an OpenAPI-described API, an MCP server exposes tools that the agent discovers dynamically, computer use operates interfaces with no API, and an agent flow runs deterministic steps. Knowledge sources provide content rather than actions, and adaptive cards display information.",
    syllabus: cite("Design agent extensibility in Copilot Studio", "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent", "Use tools with custom agents"),
  }),
  match({
    id: "ab-fm-d04", domain: "ab-design", topic: "Proposing Foundry Tools",
    prompt: "Match each requirement to the Foundry Tools service the architect should propose.",
    targets: [
      "Extract fields from scanned claim forms",
      "Translate product manuals and keep their formatting",
      "Transcribe call recordings with speaker labels",
    ],
    answers: ["Azure Content Understanding", "Azure Translator document translation", "Azure Speech batch transcription"],
    distractors: ["Azure AI Content Safety", "Azure AI Search semantic ranker"],
    explanation: "Content Understanding extracts structured fields from documents, document translation preserves formatting, and batch transcription processes recordings with diarization. Content Safety detects harmful content, and the semantic ranker reorders search results.",
    syllabus: cite("Propose Foundry Tools for a given requirement", "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq", "What is Foundry IQ?"),
  }),
  gaps({
    id: "ab-fm-d05", domain: "ab-design", topic: "Power Platform AI features",
    prompt: "Complete the architect's proposal for Power Platform AI features in the solution.",
    template: "Makers use {0} to find and reuse prompts and AI models, call a {1} from a Power Automate flow to classify incoming email, and use {2} to extract fields from standard invoices without training.",
    blanks: [
      ["AI hub", "solution explorer", "admin center analytics"],
      ["prompt", "canvas component", "business rule"],
      ["the prebuilt invoice processing model", "a custom object detection model", "a Power BI dataflow"],
    ],
    explanation: "AI hub is where makers discover and manage AI capabilities, a prompt can classify email from within a flow, and the prebuilt invoice processing model extracts invoice fields without training. Solution explorer and admin analytics manage components and usage, canvas components and business rules do not call models, a custom object detector needs training, and a dataflow prepares data.",
    syllabus: cite("Propose Microsoft Power Platform AI features, including AI hub", "https://learn.microsoft.com/ai-builder/overview", "AI Builder overview"),
  }),
  gaps({
    id: "ab-fm-d06", domain: "ab-design", topic: "Generative pages and agent feed",
    prompt: "Complete the design for a model-driven Power Apps solution that works alongside agents.",
    template: "Use {0} to create a custom page from a natural-language description, and add the {1} so that users can review and act on work that agents completed for them.",
    blanks: [
      ["generative pages", "canvas components", "business process flows"],
      ["agent feed", "timeline control", "command bar"],
    ],
    explanation: "Generative pages create code-first pages from a description, and the agent feed surfaces agent activity so users can review and act on it. Canvas components and business process flows are built by hand, the timeline shows record activities, and the command bar hosts actions rather than agent results.",
    syllabus: cite("Propose code-first generative pages and the use of an agent feed for apps", "https://learn.microsoft.com/power-platform/well-architected/intelligent-application/", "Intelligent application workload"),
  }),
  gaps({
    id: "ab-fm-d07", domain: "ab-design", topic: "Preparing grounding data",
    prompt: "Complete the data-processing design for grounding an agent solution.",
    template: "Before indexing, {0} the documents into chunks that keep their headings, attach {1} such as department and effective date, and {2} superseded versions so they are never retrieved.",
    blanks: [
      ["split", "encrypt", "compress"],
      ["metadata", "watermarks", "macros"],
      ["exclude", "duplicate", "translate"],
    ],
    explanation: "Splitting on structure keeps chunks meaningful, metadata such as department and effective date enables filtering and freshness, and excluding superseded versions stops outdated answers. Encryption and compression do not create retrievable units, watermarks and macros add nothing to retrieval, and duplicating or translating old versions spreads them further.",
    syllabus: cite("Design data processing for AI models and grounding", "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq", "What is Foundry IQ?"),
  }),
  gaps({
    id: "ab-fm-d08", domain: "ab-design", topic: "Prompt actions",
    prompt: "Complete the description of a prompt action in a Copilot Studio agent.",
    template: "A prompt action takes {0} as inputs, can ground its instructions on {1}, and returns {2} that the topic or agent flow uses in later steps.",
    blanks: [
      ["typed input variables", "the maker's credentials", "the whole tenant's content"],
      ["Dataverse or knowledge data", "other users' mailboxes", "unapproved websites"],
      ["text or JSON output", "a new environment", "a security role"],
    ],
    explanation: "Prompts accept typed inputs, can be grounded on Dataverse and knowledge data, and return text or JSON that later steps can use. They never take a maker's credentials or whole-tenant content, they do not reach into other users' mailboxes or unapproved sites, and they do not create environments or security roles.",
    syllabus: cite("Design prompt actions in Copilot Studio", "https://learn.microsoft.com/microsoft-copilot-studio/prompts-overview", "Prompts in Copilot Studio"),
  }),
  gaps({
    id: "ab-fm-d09", domain: "ab-design", topic: "Finance and operations chat knowledge",
    prompt: "Complete the design for letting the Dynamics 365 finance and operations Copilot chat answer from company procedures.",
    template: "Extend the chat in {0} by adding {1} as a knowledge source, then publish the change so that it appears in {2}.",
    blanks: [
      ["Copilot Studio", "Visual Studio", "Lifecycle Services"],
      ["the procedures SharePoint site", "every user's personal inbox", "a public search engine index"],
      ["the in-app Copilot pane", "a separate Teams app", "the Azure portal"],
    ],
    explanation: "The finance and operations Copilot experience is extended in Copilot Studio, where the procedures site is added as a knowledge source, and the published change appears in the in-app Copilot pane. Visual Studio and Lifecycle Services handle code and environments, personal inboxes and a public search index are not company procedures, and a Teams app or the Azure portal is not where users are working.",
    syllabus: cite("Design interoperability of the finance and operations agent chats to use additional knowledge sources", "https://learn.microsoft.com/dynamics365/fin-ops-core/fin-ops/copilot/copilot-generative-help", "Generative help and guidance with Copilot"),
  }),
  choose({
    id: "ab-fm-d10", domain: "ab-design", topic: "Designing for voice",
    prompt: "A Copilot Studio agent will handle voice calls in Dynamics 365 Contact Center. Which two design choices matter most for voice? Each correct answer presents part of the solution.",
    options: [
      "Short replies that confirm key details back to the caller",
      "A handoff to a representative that carries the conversation",
      "Adaptive cards that present each answer in a formatted layout",
      "Long lists of options that the caller hears read aloud in full",
      "A request for the caller to type their reference number",
    ],
    explanation: "Callers follow speech, so replies must be short and confirm details, and a handoff with context avoids making them repeat themselves. Adaptive cards are visual, long spoken lists are hard to follow, and callers cannot type during a voice call.",
    syllabus: cite("Design agents for integration with Dynamics 365 Contact Center channels", "https://learn.microsoft.com/dynamics365/contact-center/use/use-ask-a-question", "Use Copilot to ask a question in Contact Center"),
  }),
  choose({
    id: "ab-fm-d11", domain: "ab-design", topic: "When to propose MCP",
    prompt: "When should an architect propose a Model Context Protocol server as a tool for a Copilot Studio agent? Each correct answer presents part of the solution.",
    options: [
      "A partner already exposes its capabilities through an MCP server",
      "The tools change often and should update without republishing",
      "The agent only needs to answer questions from one static FAQ",
      "The team wants the tool to run without any authentication",
      "The action must run offline, on a single user's own device, every time",
    ],
    explanation: "MCP fits when a server already offers the tools and when the tool list changes, because the agent picks up changes without being republished. A static FAQ is a knowledge source, skipping authentication is never a design goal, and an offline, device-local action does not suit a remote server.",
    syllabus: cite("Design agent extensibility with Model Context Protocol in Copilot Studio", "https://learn.microsoft.com/microsoft-copilot-studio/agent-extend-action-mcp", "Extend an agent with Model Context Protocol"),
  }),
  choose({
    id: "ab-fm-d12", domain: "ab-design", topic: "Project agent in Microsoft 365",
    prompt: "A project team wants a no-code agent grounded on one SharePoint site that respects each person's file access. Which two choices fit? Each correct answer presents part of the solution.",
    options: [
      "Build the agent in Microsoft 365 Copilot with the site as knowledge",
      "Share the agent with the members of the project team",
      "Build a custom Foundry agent with its own copy of the site's files",
      "Grant everyone access to all files so the agent can always answer",
      "Copy the site's files to a public website that the agent can read",
    ],
    explanation: "An agent built in Microsoft 365 Copilot with the site as knowledge respects each user's permissions, and sharing it with the team gives them access without opening up the files. A Foundry agent with copied files abandons those permissions and needs code, granting everyone access overshares, and a public website exposes project content.",
    syllabus: cite("Optimize solution design by using agents in Microsoft 365, including Teams and SharePoint", "https://learn.microsoft.com/microsoft-365/copilot/extensibility/agent-builder-share-manage-agents", "Share and manage agents"),
  }),
  choose({
    id: "ab-fm-d13", domain: "ab-design", topic: "Consistent style at volume",
    correctCount: 1,
    prompt: "An insurer's claims agent must apply insurer-specific terminology and structure consistently across thousands of daily notes, and prompting alone is inconsistent. What should the architect propose for the AI solution?",
    options: [
      "Fine-tune a model in Microsoft Foundry on curated example notes",
      "Raise the temperature so the model varies its wording more often",
      "Add every past claim note to the agent's system instructions",
      "Switch to a larger model and remove all examples from the prompt",
      "Pretrain a new foundation model on the insurer's entire archive",
    ],
    explanation: "When prompting cannot hold a consistent style and terminology at volume, fine-tuning on curated examples is the proportionate step. A higher temperature adds variation, all past notes overflow the context, a larger model without examples is less consistent, and pretraining a foundation model is far beyond the need.",
    syllabus: cite("Design AI solutions by using custom models in Microsoft Foundry", "https://learn.microsoft.com/azure/ai-foundry/concepts/fine-tuning-overview", "Fine-tuning in Microsoft Foundry"),
  }),
  choose({
    id: "ab-fm-d14", domain: "ab-design", topic: "When to use computer use",
    prompt: "Which two conditions favor computer use in Copilot Studio over a connector for an agent? Each correct answer presents part of the solution.",
    options: [
      "The system offers no API and no connector",
      "The task follows stable screens completed the same way each time",
      "The system offers a well-documented REST API for the same task",
      "The task needs responses measured in milliseconds",
      "The screens change their layout every day",
    ],
    explanation: "Computer use suits systems with no programmable interface and tasks that follow stable screens. A documented API should be used through a connector instead, operating a user interface cannot meet millisecond response times, and daily layout changes make automation brittle.",
    syllabus: cite("Design agents to automate tasks in apps and websites by using Computer Use in Copilot Studio", "https://learn.microsoft.com/microsoft-copilot-studio/computer-use", "Computer use in Copilot Studio"),
  }),

  // ===== Deploy AI-powered business solutions =====
  sequence({
    id: "ab-fm-y01", domain: "ab-deploy", topic: "Customer service AI release",
    prompt: "Arrange the ALM steps for releasing Copilot features and agents in Dynamics 365 customer service apps.",
    steps: [
      "Configure the features and agents in development inside a solution",
      "Export the solution as managed through a pipeline",
      "Import it into test and run the end-to-end test set",
      "Promote it to production and enable it for the pilot group",
    ],
    distractors: ["Configure the features directly in production", "Import an unmanaged export into production"],
    explanation: "Configuration lives in a solution in development, moves as a managed solution through a pipeline, is validated in test, and reaches production for a pilot group first. Configuring directly in production and importing unmanaged solutions make changes impossible to track or reverse.",
    syllabus: cite("Design the ALM process for AI in Dynamics 365 apps for customer experience and service", "https://learn.microsoft.com/power-platform/alm/pipelines", "Pipelines in Power Platform"),
  }),
  match({
    id: "ab-fm-y02", domain: "ab-deploy", topic: "Monitoring tools",
    prompt: "Match each monitoring question to the tool the architect should recommend for the agent solution.",
    targets: [
      "Which topics a Copilot Studio agent triggers and how conversations end",
      "Traces and latency of a Microsoft Foundry agent",
      "Which sensitive data appears in AI interactions across the tenant",
    ],
    answers: ["Copilot Studio analytics", "Foundry observability with Application Insights", "Microsoft Purview DSPM for AI"],
    distractors: ["Windows Event Viewer", "Azure Advisor"],
    explanation: "Copilot Studio analytics reports topics, outcomes, and conversation metrics, Foundry observability sends agent traces to Application Insights, and Purview's data security posture management for AI shows sensitive data in AI interactions. Event Viewer records local operating system events, and Advisor recommends Azure resource optimizations.",
    syllabus: cite("Recommend the process and tools required for monitoring agents", "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard", "Monitor agents with the Agent Monitoring Dashboard"),
  }),
  match({
    id: "ab-fm-y03", domain: "ab-deploy", topic: "Acting on feedback",
    prompt: "Match each signal from a Copilot Studio agent to the action the team should take.",
    targets: [
      "Frequent thumbs-down reactions on HR answers",
      "Many sessions end in the Escalate topic",
      "A large theme of unanswered questions about travel",
    ],
    answers: [
      "Review the conversations behind the reactions and fix the content",
      "Add or improve topics for the requests that escalate",
      "Add the travel policy as a knowledge source",
    ],
    distractors: ["Remove the reaction buttons from the chat", "Raise the model temperature for every answer"],
    explanation: "Negative reactions point to specific answers whose content needs fixing, frequent escalations reveal requests that deserve better topics, and a theme of unanswered questions shows missing knowledge. Removing the buttons hides the signal, and a higher temperature makes answers less reliable.",
    syllabus: cite("Analyze backlog and user feedback of AI and agent usage", "https://learn.microsoft.com/microsoft-copilot-studio/analytics-themes", "Monitor user questions by theme"),
  }),
  match({
    id: "ab-fm-y04", domain: "ab-deploy", topic: "Fixing weak prompts",
    prompt: "Match each problem with a Copilot prompt to the best-practice fix.",
    targets: [
      "The output format changes from run to run",
      "Answers include facts from outside the supplied documents",
      "Responses are pitched at the wrong readers",
    ],
    answers: [
      "Specify the output format and include an example",
      "Instruct the model to answer only from the supplied context",
      "State the audience and the purpose of the response",
    ],
    distractors: ["Write the prompt in capital letters", "Make the prompt as short as possible"],
    explanation: "An explicit format with an example stabilizes the output, restricting answers to the supplied context keeps them grounded, and naming the audience and purpose sets the tone. Capital letters do not change behavior reliably, and shortening a prompt usually removes the guidance it needs.",
    syllabus: cite("Validate effective Copilot prompt best practices", "https://learn.microsoft.com/microsoft-copilot-studio/prompts-overview", "Prompts in Copilot Studio"),
  }),
  match({
    id: "ab-fm-y05", domain: "ab-deploy", topic: "Validating a tuned model",
    prompt: "Match each requirement for a fine-tuned claims model to the validation criterion that proves it.",
    targets: [
      "It must not invent facts",
      "It must perform equally well for every customer region",
      "It must not get worse at the tasks it already handles",
    ],
    answers: [
      "Groundedness above an agreed threshold",
      "Quality measured per region, with a maximum gap",
      "Comparison with the baseline model on a fixed test set",
    ],
    distractors: ["Training loss alone", "The number of training epochs"],
    explanation: "Groundedness measures invented content, per-region scores with a maximum gap show whether quality is even across regions, and a fixed test set compared with the baseline catches regressions. Training loss and epoch counts describe the training run, not behavior on the business task.",
    syllabus: cite("Create validation criteria of custom AI models", "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators", "Built-in evaluators reference"),
  }),
  match({
    id: "ab-fm-y06", domain: "ab-deploy", topic: "Securing a model",
    prompt: "Match each model security requirement to the control that meets it in the Microsoft Foundry solution.",
    targets: [
      "Only the ML team may start fine-tuning jobs",
      "Applications call the model without keys",
      "The model endpoint is unreachable from the internet",
    ],
    answers: [
      "A scoped Foundry role on the project",
      "Managed identity with Microsoft Entra ID",
      "A private endpoint with public access disabled",
    ],
    distractors: ["The API key shared in a team wiki", "An allow-all Azure services firewall rule"],
    explanation: "A scoped role limits who can tune the model, managed identities authenticate without keys, and a private endpoint with public access disabled keeps the endpoint off the internet. A key in a wiki is a leak, and allowing all Azure services opens the endpoint to any tenant's resources.",
    syllabus: cite("Design model security", "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry", "Role-based access control for Microsoft Foundry"),
  }),
  sequence({
    id: "ab-fm-y07", domain: "ab-deploy", topic: "Cross-app test scenario",
    prompt: "Arrange an end-to-end test scenario for an AI solution that spans Dynamics 365 Sales and Dynamics 365 Finance.",
    steps: [
      "A customer accepts a Copilot-drafted quote in Dynamics 365 Sales",
      "The order flows to Dynamics 365 Finance and an invoice is created",
      "The collections agent drafts a reminder for the overdue invoice",
      "The test checks that the customer record is consistent in both apps",
    ],
    distractors: ["Test each app's Copilot feature separately and stop there", "Skip the finance step because it contains no AI"],
    explanation: "An end-to-end scenario follows the business process across apps, from quote to invoice to collections, and then checks that shared data stayed consistent. Testing features in isolation misses the handoffs where cross-app failures occur, and skipping a step because it has no AI breaks the chain the agents depend on.",
    syllabus: cite("Design end-to-end test scenarios of AI solutions that use multiple Dynamics 365 apps", "https://learn.microsoft.com/dynamics365/copilot/ai-get-started", "Agents, Copilot, and AI capabilities in Dynamics 365 apps"),
  }),
  gaps({
    id: "ab-fm-y08", domain: "ab-deploy", topic: "Data policy groups",
    prompt: "Complete the Power Platform data policy design for the environments that host agents.",
    template: "Place the connectors agents may use in the {0} group, move unapproved connectors to {1}, and apply the policy to the {2} that hosts the agents.",
    blanks: [
      ["Business", "Non-business", "Blocked"],
      ["Blocked", "Business", "Non-business"],
      ["environment", "Teams channel", "user mailbox"],
    ],
    explanation: "Connectors in the Business group can be used together, Blocked connectors cannot be used at all, and data policies are scoped to environments. Non-business connectors cannot be combined with Business ones but are still usable, so they do not stop unapproved use, and data policies are not applied to Teams channels or mailboxes.",
    syllabus: cite("Design governance for agents", "https://learn.microsoft.com/power-platform/admin/wp-data-loss-prevention", "Data loss prevention policies"),
  }),
  gaps({
    id: "ab-fm-y09", domain: "ab-deploy", topic: "Managed Environments",
    prompt: "Complete the governance design for the production environment that hosts the Copilot Studio agents.",
    template: "Turn on {0} so the solution checker is enforced on import, limit {1} of agents to named security groups, and review the {2} of usage each week.",
    blanks: [
      ["Managed Environments", "tenant isolation", "developer environments"],
      ["sharing", "exporting", "renaming"],
      ["weekly digest", "error log", "billing invoice"],
    ],
    explanation: "Managed Environments add solution checker enforcement, sharing limits, and a weekly digest of usage. Tenant isolation controls cross-tenant connections and developer environments are personal sandboxes; export and rename permissions are not the sharing limits, and error logs and invoices do not summarize usage.",
    syllabus: cite("Design security for agents", "https://learn.microsoft.com/power-platform/admin/managed-environment-overview", "Managed Environments overview"),
  }),
  gaps({
    id: "ab-fm-y10", domain: "ab-deploy", topic: "Foundry agent ALM",
    prompt: "Complete the ALM design for agents built with Microsoft Foundry Agent Service.",
    template: "Keep each agent's definition and instructions in {0}, deploy it to test and production through {1}, and gate promotion on {2}.",
    blanks: [
      ["source control", "a shared spreadsheet", "the portal only"],
      ["a CI/CD pipeline", "manual copy and paste", "an email to the admin"],
      ["evaluation results", "the commit count", "the author's own approval"],
    ],
    explanation: "Source control versions agent definitions, a CI/CD pipeline deploys them the same way every time, and evaluation results show that a change is safe to promote. Spreadsheets and portal-only edits are untracked, manual copying and emailed requests are unrepeatable, and commit counts or an author's approval say nothing about quality.",
    syllabus: cite("Design the ALM process for Microsoft Foundry Agents service", "https://learn.microsoft.com/azure/foundry/agents/overview", "Microsoft Foundry Agent Service"),
  }),
  gaps({
    id: "ab-fm-y11", domain: "ab-deploy", topic: "Custom model lifecycle",
    prompt: "Complete the ALM design for a custom model in the AI solution.",
    template: "Version the {0} with each model, register evaluation results before {1}, and keep the {2} deployed so traffic can be moved back quickly.",
    blanks: [
      ["training data snapshot", "shared prompt library", "test chat log"],
      ["promotion to production", "the first training run", "data collection"],
      ["previous version", "oldest version", "training cluster"],
    ],
    explanation: "Versioning the training data with the model makes each version reproducible, recording evaluations before promotion documents why it shipped, and keeping the previous version deployed allows a fast rollback. A shared prompt library or a test chat log does not reproduce a model, evaluations belong at promotion rather than before training or collection, and the oldest version or a training cluster is not a rollback target.",
    syllabus: cite("Design the ALM process for custom AI models", "https://learn.microsoft.com/azure/ai-foundry/concepts/fine-tuning-overview", "Fine-tuning in Microsoft Foundry"),
  }),
  gaps({
    id: "ab-fm-y12", domain: "ab-deploy", topic: "Responsible AI review",
    prompt: "Complete the responsible AI review checklist for an agent solution.",
    template: "Check {0} by comparing outcomes across user groups, {1} by documenting what the agent can and cannot do, and {2} by naming who answers for its decisions.",
    blanks: [
      ["fairness", "reliability", "inclusiveness"],
      ["transparency", "privacy", "fairness"],
      ["accountability", "security", "transparency"],
    ],
    explanation: "Comparing outcomes across groups tests fairness, documenting capabilities and limits delivers transparency, and naming who is answerable establishes accountability. Reliability, inclusiveness, privacy, and security are also principles, but each is checked by other means, such as failure testing, accessibility review, and data protection.",
    syllabus: cite("Review solution for adherence to responsible AI principles", "https://learn.microsoft.com/azure/well-architected/ai/responsible-ai", "Responsible AI in the Well-Architected Framework"),
  }),
  gaps({
    id: "ab-fm-y13", domain: "ab-deploy", topic: "Reading telemetry",
    prompt: "Complete the guidance for interpreting agent telemetry in the AI solution.",
    template: "A rising {0} with steady traffic points to prompts or retrieval growing, rising {1} on one tool points to that dependency, and a falling {2} after a knowledge change points to content quality.",
    blanks: [
      ["token count per session", "number of users", "count of licenses assigned"],
      ["latency and error rate", "user satisfaction", "session count"],
      ["resolution rate", "session count", "token count"],
    ],
    explanation: "More tokens per session at steady traffic means each session is consuming more, slow or failing calls isolated to one tool implicate that dependency, and a drop in resolution after a knowledge change implicates the content. The number of users and the count of licenses assigned track adoption, satisfaction and session counts do not isolate a tool, and session or token counts do not measure answer quality.",
    syllabus: cite("Interpret telemetry data for performance and model tuning", "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard", "Monitor agents with the Agent Monitoring Dashboard"),
  }),
  gaps({
    id: "ab-fm-y14", domain: "ab-deploy", topic: "Generating test cases",
    prompt: "Complete the strategy for building an agent's test cases with Copilot.",
    template: "Use Copilot Studio to {0} test questions from the agent's knowledge and instructions, have {1} review and correct the expected answers, and {2} the set with real questions from production.",
    blanks: [
      ["generate", "delete", "encrypt"],
      ["subject-matter experts", "the model itself", "an unreviewed script"],
      ["extend", "replace", "hide"],
    ],
    explanation: "Copilot Studio can generate test questions from an agent's knowledge and instructions, subject-matter experts confirm the expected answers so the set is trustworthy, and adding real production questions keeps it representative. Letting the model grade its own expected answers or accepting an unreviewed script makes the set unreliable, and replacing or hiding cases loses coverage.",
    syllabus: cite("Build the strategy for creating test cases by using Copilot", "https://learn.microsoft.com/microsoft-copilot-studio/analytics-agent-evaluation-intro", "About agent evaluation"),
  }),
  choose({
    id: "ab-fm-y15", domain: "ab-deploy", topic: "Securing a Teams agent",
    prompt: "A Copilot Studio agent will be published to Teams for employees. Which two settings should the architect require? Each correct answer presents part of the solution.",
    options: [
      "Microsoft Entra ID sign-in for every user of the agent",
      "User credentials for actions that read user-specific data",
      "No authentication, to reduce sign-in friction for employees in Teams",
      "Editor permissions for everyone in the tenant",
      "A service account password stored inside a topic",
    ],
    explanation: "Entra ID sign-in identifies each user, and running user-specific actions with the user's own credentials means the agent never returns more than that user can see. No authentication makes every action anonymous, tenant-wide editor rights let anyone change the agent, and a password in a topic is exposed to every editor.",
    syllabus: cite("Design security for agents", "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication", "Configure user authentication"),
  }),
  choose({
    id: "ab-fm-y16", domain: "ab-deploy", topic: "Injection through email",
    prompt: "An autonomous agent processes incoming customer email. Which two mitigations reduce the risk of indirect prompt injection? Each correct answer presents part of the solution.",
    options: [
      "Treat email content as data and never as instructions",
      "Require approval for actions that send data outside the company",
      "Write a longer system prompt that describes safe behavior",
      "Give the agent read access to every mailbox in the whole organization",
      "Turn off logging so that email content is never retained",
    ],
    explanation: "Keeping email content in the data channel stops it from redefining the agent's instructions, and approval on outbound actions caps the damage if an injection succeeds. A longer prompt does not create a boundary, broad mailbox access widens exposure, and disabling logging removes the evidence needed to investigate.",
    syllabus: cite("Analyze solution and AI vulnerabilities and mitigations, including prompt manipulation", "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization", "Governance and security for AI agents"),
  }),
  choose({
    id: "ab-fm-y17", domain: "ab-deploy", topic: "Governing makers",
    prompt: "Makers across a company build Copilot Studio agents. Which two controls let the platform team govern agents without blocking makers? Each correct answer presents part of the solution.",
    options: [
      "Route new makers into their own developer environments",
      "Apply data policies that block unapproved connectors",
      "Remove Copilot Studio licenses from all makers",
      "Let every maker build directly in the production environment",
      "Review agents only after a complaint has been received",
    ],
    explanation: "Environment routing gives each maker a personal developer environment away from shared and production spaces, and data policies block risky connectors everywhere. Removing licenses stops building, building in production bypasses ALM, and waiting for complaints is not governance.",
    syllabus: cite("Design governance for agents", "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization", "Governance and security for AI agents"),
  }),
  choose({
    id: "ab-fm-y18", domain: "ab-deploy", topic: "Resolution, not deflection",
    prompt: "Which two metrics best show whether a customer service agent resolves issues rather than just deflecting them? Each correct answer presents part of the solution.",
    options: [
      "Resolution rate confirmed by the customer or the case outcome",
      "Escalation rate together with the reasons for escalating",
      "Total number of sessions that the agent handled over the past month",
      "Average length of the agent's messages in each session",
      "Number of topics that the makers have authored so far",
    ],
    explanation: "Confirmed resolution shows that problems were actually solved, and escalations with their reasons show where the agent falls short. Session totals, message length, and topic counts measure activity or effort rather than outcomes.",
    syllabus: cite("Monitor agent performance and metrics", "https://learn.microsoft.com/microsoft-copilot-studio/analytics-overview", "Copilot Studio analytics overview"),
  }),
  choose({
    id: "ab-fm-y19", domain: "ab-deploy", topic: "Checking EU residency",
    prompt: "Which two checks confirm that a Copilot Studio agent solution keeps its data in the EU? Each correct answer presents part of the solution.",
    options: [
      "The environment was created in an EU region",
      "Cross-region data movement for generative AI is turned off",
      "Users sign in from IP addresses located inside the EU",
      "The agent's display name includes the letters EU",
      "The maker's Windows region is set to Germany",
    ],
    explanation: "The environment's region determines where the agent's data is stored, and keeping cross-region data movement off stops generative AI features from processing outside that geography. Sign-in location, the agent's name, and the maker's Windows settings do not determine where data is stored or processed.",
    syllabus: cite("Validate data residency and movement compliance", "https://learn.microsoft.com/purview/ai-microsoft-purview", "Microsoft Purview for AI"),
  }),
  choose({
    id: "ab-fm-y20", domain: "ab-deploy", topic: "Record-level grounding",
    prompt: "An agent grounds its answers on Dataverse records. Which two controls ensure each user sees only records they are entitled to? Each correct answer presents part of the solution.",
    options: [
      "Query Dataverse with the signed-in user's own credentials",
      "Scope record access with security roles and business units",
      "Tell the agent in its instructions to hide other records",
      "Use a system account that can read every record in the tables",
      "Hide sensitive columns on the form while keeping them in queries",
    ],
    explanation: "Querying with the user's credentials applies Dataverse security, and security roles with business units define which records each user may read. Instructions cannot enforce access, a system account sees everything, and hiding columns on a form does not stop them being retrieved.",
    syllabus: cite("Design access controls on grounding data and model tuning", "https://learn.microsoft.com/power-platform/admin/wp-security-cds", "Dataverse security concepts"),
  }),
  choose({
    id: "ab-fm-y21", domain: "ab-deploy", topic: "When tests run",
    correctCount: 1,
    prompt: "When should an agent's evaluation test set run in the agent solution's release process?",
    options: [
      "Before release, whenever instructions, knowledge, or tools change",
      "Once, before the very first production release of the agent",
      "Only after users begin to complain about wrong answers",
      "Only after each change has already reached the production environment",
      "Once a year, during the organization's annual audit cycle",
    ],
    explanation: "Any change to instructions, knowledge, or tools can shift behavior, so the test set runs before every release. Testing only once, after complaints, after deployment, or annually lets regressions reach users first.",
    syllabus: cite("Recommend the process and metrics to test agents", "https://learn.microsoft.com/microsoft-copilot-studio/analytics-agent-evaluation-intro", "About agent evaluation"),
  }),
  choose({
    id: "ab-fm-y22", domain: "ab-deploy", topic: "AI-assisted diagnosis",
    prompt: "Which two Copilot Studio capabilities use AI to help identify why an agent answers poorly? Each correct answer presents part of the solution.",
    options: [
      "Agent evaluation with AI-graded quality on a test set",
      "Analytics themes that group similar user questions",
      "Reading every transcript by hand at the end of each week",
      "Counting the number of sessions that start each day",
      "Checking which users have been assigned licenses",
    ],
    explanation: "AI-graded evaluation scores answer quality across a test set, and themes cluster similar questions with their answer rates so weak areas stand out. Reading every transcript by hand does not scale, and session counts and license assignments say nothing about answer quality.",
    syllabus: cite("Apply AI-based tools to analyze and identify issues and perform tuning", "https://learn.microsoft.com/microsoft-copilot-studio/analytics-themes", "Monitor user questions by theme"),
  }),
  choose({
    id: "ab-fm-y23", domain: "ab-deploy", topic: "Weekly knowledge updates",
    prompt: "Knowledge files for a production agent are updated every week. Which two practices keep these releases safe? Each correct answer presents part of the solution.",
    options: [
      "Stage the updated files in test and run the evaluation set",
      "Keep the previous version available so you can roll back",
      "Edit the production files directly during business hours",
      "Delete the old files as soon as the new ones are uploaded",
      "Skip testing for any change that looks small to the author",
    ],
    explanation: "Staging and evaluating the new files catches regressions before users see them, and keeping the previous version makes rollback quick. Editing production directly, deleting old versions immediately, and skipping tests for small changes all remove the safety net.",
    syllabus: cite("Design the ALM process for data used in AI models and agents", "https://learn.microsoft.com/power-platform/guidance/adoption/environment-strategy", "Environment strategy"),
  }),
];
