import { AI103_SYLLABUS } from "./ai103-syllabus.ts";
import { buildersFor, citeFrom } from "./question-builders.ts";
import type { Question } from "./questions";

/**
 * MAINTAINED BY HAND. Standalone AI-103 items in the interactive formats the real exam
 * uses: multiple choice of five (one or two keyed answers), drag-and-drop matching and
 * ordering, and dropdown gap-fill over statements and code. Spread across the five
 * domains by published weight, favoring the least-cited syllabus bullets.
 *
 * Authoring convention (see question-builders.ts): the right answer comes first.
 */
const { choose, match, sequence, gaps } = buildersFor("ai103");
const cite = citeFrom(AI103_SYLLABUS);

const SECURITY = "Configure security, including managed identity, private networking, keyless credentials, and role policies";
const QUOTAS = "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads";
const RAG = "Implement retrieval-augmented generation (RAG) in an application";
const TOOLS = "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions";
const SAFEGUARDS = "Build autonomous or semiautonomous workflows with safeguards and approval flow controls";

export const AI103_FORMAT_QUESTIONS: Question[] = [
  // ===== Plan and manage an Azure AI solution =====
  match({
    id: "fm-p01", domain: "plan", topic: "Deployment types",
    prompt: "A global retailer has no data residency constraint. For each of its workloads, choose the Microsoft Foundry Models deployment type that fits.",
    targets: [
      "Pay per token with the highest default quota, processed in any region",
      "Reserved throughput with predictable latency for a steady workload",
      "Large asynchronous jobs at lower cost with a 24-hour turnaround",
    ],
    answers: ["Global Standard", "Global Provisioned", "Global Batch"],
    distractors: ["Developer", "Data Zone Standard"],
    explanation: "Global Standard is pay per token with the highest default quota and routes to any region, Global Provisioned reserves throughput for predictable latency, and Global Batch runs large asynchronous jobs at a discount within a 24-hour target. Developer deployments serve fine-tuned models for evaluation without an SLA, and Data Zone Standard restricts processing to a data zone, which these workloads do not require.",
    syllabus: cite("Choose appropriate deployment options", "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", "Deployment types for Microsoft Foundry Models"),
  }),
  match({
    id: "fm-p02", domain: "plan", topic: "Foundry built-in roles",
    prompt: "Match each person or application to the least-privileged Microsoft Foundry built-in role for what it does.",
    targets: [
      "A data scientist who builds and tests agents in one project",
      "A team lead who manages deployments and adds new developers",
      "A platform administrator who creates Foundry resources and rotates keys",
      "A line-of-business app that only calls a published agent",
    ],
    answers: ["Foundry User", "Foundry Project Manager", "Foundry Account Owner", "Foundry Agent Consumer"],
    distractors: ["Azure AI Developer", "Cognitive Services Contributor"],
    explanation: "Foundry User is the least-privileged role for building and testing, Foundry Project Manager adds project management and can assign Foundry User, Foundry Account Owner manages resources and keys, and Foundry Agent Consumer only calls agent endpoints. Azure AI Developer is scoped to Azure Machine Learning workspaces and hubs, and Cognitive Services roles target individual AI services resources rather than Foundry projects.",
    syllabus: cite(SECURITY, "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry", "Role-based access control for Microsoft Foundry"),
  }),
  sequence({
    id: "fm-p03", domain: "plan", topic: "Private Foundry access",
    prompt: "An application in an Azure virtual network must reach a Microsoft Foundry resource privately, and public access must end without an outage. Arrange the steps in order.",
    steps: [
      "Create a private endpoint for the Foundry resource in the virtual network",
      "Link the Foundry private DNS zones to the virtual network",
      "Confirm the endpoint resolves to a private IP from inside the network",
      "Disable public network access on the Foundry resource",
    ],
    distractors: ["Add the application's public IP to the resource firewall", "Create a service endpoint for Microsoft.CognitiveServices"],
    explanation: "The private endpoint comes first, DNS linking makes the Foundry hosts resolve to it, and resolution is confirmed from inside the network before public access is disabled, so traffic never loses its path. A firewall rule for a public IP keeps traffic on the internet, and a service endpoint does not give the resource a private address.",
    syllabus: cite(SECURITY, "https://learn.microsoft.com/azure/private-link/private-endpoint-dns", "Azure Private Endpoint private DNS zone values"),
  }),
  match({
    id: "fm-p04", domain: "plan", topic: "Guardrail selection",
    prompt: "Match each risk in a Microsoft Foundry chat application to the Azure AI Content Safety capability that addresses it.",
    targets: [
      "A user message tries to override the system instructions",
      "A retrieved web page hides instructions aimed at the agent",
      "The answer states facts that the retrieved sources do not contain",
      "The output reproduces copyrighted song lyrics",
    ],
    answers: [
      "Prompt Shields for user prompt attacks",
      "Prompt Shields for document attacks",
      "Groundedness detection",
      "Protected material detection",
    ],
    distractors: ["A custom blocklist of product names", "Language detection"],
    explanation: "Prompt Shields detects direct attacks in user prompts and indirect attacks embedded in documents, groundedness detection flags claims the sources do not support, and protected material detection finds known copyrighted text such as lyrics. A blocklist blocks listed terms without understanding intent, and language detection only identifies the language.",
    syllabus: cite("Configure safety filters, guardrails, risk detection, and content moderation", "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection", "Prompt Shields"),
  }),
  match({
    id: "fm-p05", domain: "plan", topic: "Agent evaluators",
    prompt: "A team evaluates a Microsoft Foundry agent before release. Match each question to the evaluator that answers it.",
    targets: [
      "Did the agent call the right tool with correct arguments?",
      "Did the agent understand what the user wanted?",
      "Did the agent follow its instructions and constraints?",
      "Did a retrieved document manipulate the agent's response?",
    ],
    answers: ["Tool call accuracy", "Intent resolution", "Task adherence", "Indirect attack"],
    distractors: ["BLEU score", "Fluency"],
    explanation: "Tool call accuracy checks tool choice and arguments, intent resolution checks whether the agent identified the user's goal, task adherence checks behavior against the instructions, and the indirect attack evaluator detects responses shaped by injected document content. BLEU compares wording with a reference translation, and fluency rates readability rather than agent behavior.",
    syllabus: cite("Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling", "https://learn.microsoft.com/azure/foundry/concepts/evaluation-evaluators/agent-evaluators", "Agent evaluators"),
  }),
  gaps({
    id: "fm-p06", domain: "plan", topic: "Quota and throttling",
    prompt: "Complete the statement about Microsoft Foundry Models quota and throttling.",
    template: "Quota is assigned per {0}, region, model, and deployment type. A deployment that exceeds its tokens-per-minute allocation returns HTTP {1}, and clients should wait for the time in the {2} header before retrying.",
    blanks: [
      ["subscription", "resource group", "project"],
      ["429", "403", "503"],
      ["Retry-After", "x-ms-region", "Content-Length"],
    ],
    explanation: "Foundry quota is a subscription-level allowance for each region, model, and deployment type, which you then allocate to deployments. Exceeding an allocation returns 429 Too Many Requests with a Retry-After header. A 403 means access is denied and a 503 means the service is unavailable; x-ms-region and Content-Length do not carry retry timing.",
    syllabus: cite(QUOTAS, "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits", "Foundry Models quotas and limits"),
  }),
  gaps({
    id: "fm-p07", domain: "plan", topic: "Keyless project client",
    prompt: "A Python service on Azure App Service must call a Microsoft Foundry project without keys. Complete the code.",
    language: "python",
    template: "from azure.identity import DefaultAzureCredential\nfrom azure.ai.projects import AIProjectClient\n\nproject = AIProjectClient(\n    endpoint=\"https://contoso.{0}/api/projects/claims\",\n    credential={1},\n)\nclient = project.{2}()",
    blanks: [
      ["services.ai.azure.com", "openai.azure.com", "cognitiveservices.azure.com"],
      ["DefaultAzureCredential()", "AzureKeyCredential(API_KEY)", "os.environ[\"FOUNDRY_KEY\"]"],
      ["get_openai_client", "get_azure_openai_client", "get_chat_client"],
    ],
    explanation: "The project endpoint is on services.ai.azure.com under /api/projects, DefaultAzureCredential uses the App Service managed identity with no stored key, and get_openai_client returns the project-scoped OpenAI-compatible client in SDK 2.x. The openai.azure.com and cognitiveservices.azure.com hosts address the resource rather than the project, AzureKeyCredential and an environment key are key-based, and get_azure_openai_client and get_chat_client are not 2.x members.",
    syllabus: cite(SECURITY, "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code", "Get started with the Microsoft Foundry SDK"),
  }),
  gaps({
    id: "fm-p08", domain: "plan", topic: "Model router",
    prompt: "A Microsoft Foundry team wants lower cost on a mixed workload without changing application code. Complete the design.",
    template: "Deploy {0} and call it by its deployment name. It picks an underlying model for each request based on {1}, and the model that served the request is reported in the response's {2} field.",
    blanks: [
      ["model router", "a fine-tuned small model", "a provisioned deployment"],
      ["the complexity of the prompt", "the caller's Azure region", "a fixed round-robin order"],
      ["model", "id", "usage"],
    ],
    explanation: "Model router is a deployable model that evaluates each prompt and routes it to a suitable underlying model, sending simple requests to smaller, cheaper ones; the response's model field shows which model answered. A fine-tuned small model or a provisioned deployment serves one model, routing is not based on region or round-robin order, and id and usage identify the response and its token counts.",
    syllabus: cite("Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools", "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router", "Model router for Microsoft Foundry"),
  }),
  gaps({
    id: "fm-p09", domain: "plan", topic: "Pipeline authentication and gates",
    prompt: "A GitHub Actions pipeline promotes Microsoft Foundry agent changes to production. Complete the design.",
    template: "The pipeline signs in to Azure with {0} so no client secret is stored in the repository, and it runs {1} as a quality gate that must pass before promotion.",
    blanks: [
      ["OpenID Connect workload identity federation", "a client secret in repository variables", "a Foundry API key in the workflow file"],
      ["a cloud evaluation against a fixed test dataset", "a load test against production traffic", "a manual chat review by the developer"],
    ],
    explanation: "Workload identity federation lets GitHub exchange its OIDC token for an Entra token, so no long-lived secret or key is stored. A cloud evaluation over a fixed dataset produces comparable scores each run and can block promotion automatically; load testing production traffic and a developer's chat review are not repeatable quality gates.",
    syllabus: cite("Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines", "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation", "Run evaluations in the cloud by using the Foundry SDK"),
  }),
  choose({
    id: "fm-p10", domain: "plan", topic: "Throttling at peak",
    prompt: "A Global Standard deployment in Microsoft Foundry returns HTTP 429 during daily peaks, while monthly usage is well within budget. Which two actions address the throttling? Each correct answer presents part of the solution.",
    options: [
      "Raise the deployment's TPM allocation within the subscription quota",
      "Retry with exponential backoff that honors the Retry-After header",
      "Raise max_output_tokens so that fewer requests are needed overall",
      "Turn off the deployment's content filter to shorten each request's processing time",
      "Move the Foundry resource into a different resource group",
    ],
    explanation: "Throttling at peak means the deployment's tokens-per-minute allocation is too small, so raise it within quota, and have clients back off using Retry-After instead of retrying immediately. Raising max_output_tokens increases the tokens each call reserves, the content filter does not govern rate limits, and the resource group has no effect on quota.",
    syllabus: cite(QUOTAS, "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits", "Foundry Models quotas and limits"),
  }),
  choose({
    id: "fm-p11", domain: "plan", topic: "EU processing",
    prompt: "An EU insurer requires prompts and completions to be processed only inside the EU while using pay-per-token Microsoft Foundry Models. Which two choices meet the requirement? Each correct answer presents part of the solution.",
    options: [
      "Deploy the model with the Data Zone Standard deployment type",
      "Create the Foundry resource in an EU Azure region",
      "Deploy the model with the Global Standard deployment type instead",
      "Enable customer-managed keys on the Foundry resource",
      "Store application logs in an EU storage account",
    ],
    explanation: "A Data Zone deployment processes requests only within the data zone of the resource's region, so the resource must be in an EU region and the deployment must use Data Zone Standard. Global Standard may process in any region, customer-managed keys control encryption rather than processing location, and log storage location says nothing about where inference runs.",
    syllabus: cite("Choose appropriate deployment options", "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", "Deployment types for Microsoft Foundry Models"),
  }),
  choose({
    id: "fm-p12", domain: "plan", topic: "Steady high throughput",
    correctCount: 1,
    prompt: "A call-center summarization workload runs at a steady 400,000 tokens per minute all day and needs consistent latency. Which Microsoft Foundry deployment approach fits best?",
    options: [
      "A provisioned throughput deployment sized from measured traffic",
      "A Global Batch deployment with a polling loop every hour",
      "Several Global Standard deployments behind a round-robin proxy",
      "A Developer deployment of a fine-tuned summarization model",
      "A Data Zone Standard deployment that keeps its default quota allocation",
    ],
    explanation: "Steady, high, latency-sensitive traffic is what provisioned throughput is for: reserved capacity gives predictable latency and cost. Global Batch is asynchronous, round-robin Standard deployments still share variable capacity, a Developer deployment has no SLA, and a default Data Zone Standard allocation would throttle at this volume.",
    syllabus: cite(QUOTAS, "https://learn.microsoft.com/azure/foundry/openai/concepts/provisioned-throughput", "What is provisioned throughput for Foundry Models?"),
  }),
  choose({
    id: "fm-p13", domain: "plan", topic: "Refund oversight",
    prompt: "A Microsoft Foundry agent can issue refunds through an OpenAPI tool. Which two controls keep refunds above $500 under human oversight? Each correct answer presents part of the solution.",
    options: [
      "Route refunds above $500 through an approval workflow first",
      "Have the refund API reject unapproved calls above $500",
      "Tell the agent in its instructions never to exceed $500",
      "Lower the model temperature for refund conversations",
      "Review the refund log at the end of each month",
    ],
    explanation: "An approval workflow puts a person in front of large refunds, and enforcing the limit in the API means a model error cannot bypass it. Instructions and a lower temperature only make compliance more likely, and a monthly log review finds problems after the money has left.",
    syllabus: cite("Govern agent behavior with oversight modes, constraints, and tool-access controls", "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice", "Best practices for using tools in Foundry Agent Service"),
  }),
  choose({
    id: "fm-p14", domain: "plan", topic: "Detecting quality drift",
    prompt: "Three weeks after launch, users say a Microsoft Foundry agent's answers have become less accurate, but no errors appear. Which two practices detect this kind of drift? Each correct answer presents part of the solution.",
    options: [
      "Run scheduled evaluations of sampled production traces",
      "Alert when evaluator scores fall below the launch baseline",
      "Alert on the HTTP 5xx rate of the agent endpoint",
      "Track the average number of tokens in each response",
      "Check the Azure status page for regional incidents",
    ],
    explanation: "Quality drift produces no errors, so it only shows up when production traces are scored regularly for qualities such as groundedness and relevance and compared with the launch baseline. A 5xx rate and service incidents measure availability, and response length changes for many reasons unrelated to accuracy.",
    syllabus: cite("Monitor model performance, drift, safety events, and grounding quality", "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard", "Monitor agents with the Agent Monitoring Dashboard"),
  }),

  // ===== Implement generative AI and agentic solutions =====
  match({
    id: "fm-g01", domain: "gen", topic: "Retrieval modes",
    prompt: "Match each retrieval need in an Azure AI Search RAG application to the query capability that meets it.",
    targets: [
      "Exact part numbers such as FB-440 must match",
      "Paraphrased questions must find passages with similar meaning",
      "Both signals must be merged into a single ranked list",
      "The top results must be reordered by meaning, with captions",
    ],
    answers: ["Full-text keyword search", "Vector search", "Hybrid search with Reciprocal Rank Fusion", "Semantic ranker"],
    distractors: ["Fuzzy search on every term", "A freshness scoring profile"],
    explanation: "Keyword search matches exact tokens such as part numbers, vector search matches meaning, hybrid search merges both result sets with Reciprocal Rank Fusion, and the semantic ranker reorders the top results and adds captions. Fuzzy search tolerates misspellings and would loosen exact matching, and a freshness profile boosts recent documents rather than relevant ones.",
    syllabus: cite(RAG, "https://learn.microsoft.com/azure/search/hybrid-search-overview", "Hybrid search in Azure AI Search"),
  }),
  match({
    id: "fm-g02", domain: "gen", topic: "Agent tool types",
    prompt: "Match each capability a Microsoft Foundry agent needs to the tool type that provides it.",
    targets: [
      "Query an existing Azure AI Search index",
      "Call a partner REST API described by an OpenAPI 3 document",
      "Run Python to analyze an uploaded CSV file",
      "Use tools hosted on a remote Model Context Protocol server",
    ],
    answers: ["Azure AI Search tool", "OpenAPI tool", "Code Interpreter", "MCP tool"],
    distractors: ["File search over a vector store", "Grounding with Bing Search"],
    explanation: "The Azure AI Search tool queries an existing index, the OpenAPI tool calls APIs from their specification, Code Interpreter runs Python in a sandbox, and the MCP tool connects to a remote MCP server. File search indexes uploaded files in its own vector store rather than an existing index, and Bing grounding searches the public web.",
    syllabus: cite(TOOLS, "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/toolbox", "Foundry Toolbox"),
  }),
  sequence({
    id: "fm-g03", domain: "gen", topic: "Function calling loop",
    prompt: "An application built on the Microsoft Foundry Responses API exposes a getOrderStatus function. Arrange the function-calling steps in order.",
    steps: [
      "Send the request with the function's JSON schema in tools",
      "Read the function_call item that the model returns",
      "Run the function in application code with the parsed arguments",
      "Send the result back as function_call_output to get the final answer",
    ],
    distractors: ["Let the model run the function inside the Foundry service", "Parse the function name out of the model's output_text"],
    explanation: "The model only proposes a call: the application declares the schema, reads the function_call item, runs the function itself, and returns the result as function_call_output with the matching call_id so the model can finish its answer. Functions are never executed by the model, and the call arrives as a structured item rather than text to be parsed.",
    syllabus: cite(TOOLS, "https://learn.microsoft.com/azure/foundry/openai/how-to/responses", "Responses API in Microsoft Foundry"),
  }),
  match({
    id: "fm-g04", domain: "gen", topic: "Orchestration patterns",
    prompt: "A team coordinates several Microsoft Foundry agents with Microsoft Agent Framework. Match each requirement to the orchestration pattern that fits it.",
    targets: [
      "Specialists run one after another, each refining the previous output",
      "Several specialists work on the same input at once and results are combined",
      "The active agent transfers the conversation to a specialist based on context",
      "Agents debate in a shared conversation that a manager moderates",
    ],
    answers: ["Sequential", "Concurrent", "Handoff", "Group chat"],
    distractors: ["Round-robin load balancing", "Batch scheduling"],
    explanation: "Sequential passes output forward in a fixed order, concurrent runs agents in parallel and aggregates the results, handoff transfers control to the agent best suited to the context, and group chat lets agents collaborate in one managed conversation. Round-robin load balancing and batch scheduling distribute work but do not coordinate agents.",
    syllabus: cite("Implement orchestrated multi-agent solutions", "https://learn.microsoft.com/agent-framework/workflows/orchestrations/", "Workflow orchestrations"),
  }),
  match({
    id: "fm-g05", domain: "gen", topic: "Generation controls",
    prompt: "Match each goal for a Microsoft Foundry model call to the setting that achieves it.",
    targets: [
      "Let a reasoning model think longer on hard problems",
      "Cap the reply length, including reasoning tokens",
      "Keep a non-reasoning model's wording consistent across runs",
      "Guarantee the reply conforms to a JSON schema",
    ],
    answers: ["High reasoning effort", "max_output_tokens", "A low temperature", "Structured outputs in strict mode"],
    distractors: ["A larger top_logprobs value", "Streaming the response"],
    explanation: "Reasoning effort controls how much a reasoning model thinks, max_output_tokens caps visible and reasoning tokens together, a low temperature reduces variation in a non-reasoning model, and strict structured outputs enforce a schema. top_logprobs returns token probabilities without changing the output, and streaming changes delivery rather than content.",
    syllabus: cite("Tune generation behavior, such as prompt engineering and adjusting model parameters", "https://learn.microsoft.com/azure/foundry/openai/how-to/reasoning", "Azure OpenAI reasoning models"),
  }),
  gaps({
    id: "fm-g06", domain: "gen", topic: "Conversation state",
    prompt: "A Microsoft Foundry support app must continue a conversation without resending earlier turns. Complete the code.",
    language: "python",
    template: "first = client.responses.create(model=\"support-prod\", input=\"My order 5521 arrived damaged.\")\nfollow_up = client.responses.create(\n    model=\"support-prod\",\n    input=\"What are my options?\",\n    {0}=first.{1},\n)\nprint(follow_up.{2})",
    blanks: [
      ["previous_response_id", "conversation_history", "context_id"],
      ["id", "output_text", "model"],
      ["output_text", "choices[0].text", "message"],
    ],
    explanation: "Passing the earlier response's id as previous_response_id lets the service chain the conversation state, so earlier turns are not resent, and output_text returns the new reply. conversation_history and context_id are not Responses parameters, passing output_text or model would not identify the stored response, and choices[0].text belongs to the legacy completions shape.",
    syllabus: cite("Build agents that integrate retrieval, function-calling, and conversation memory", "https://learn.microsoft.com/azure/foundry/openai/how-to/responses", "Responses API in Microsoft Foundry"),
  }),
  gaps({
    id: "fm-g07", domain: "gen", topic: "Remote MCP tools",
    prompt: "A Microsoft Foundry app connects to an ERP Model Context Protocol server. Only two read-only tools may be exposed, and they may run without a human in the loop. Complete the tool definition.",
    language: "python",
    template: "tools=[{\n    \"type\": \"{0}\",\n    \"server_label\": \"erp\",\n    \"server_url\": \"https://erp.contoso.com/mcp\",\n    \"{1}\": [\"get_order\", \"get_invoice\"],\n    \"require_approval\": \"{2}\",\n}]",
    blanks: [
      ["mcp", "function", "openapi"],
      ["allowed_tools", "tool_choice", "include"],
      ["never", "always", "auto"],
    ],
    explanation: "A remote MCP server is declared with type mcp, allowed_tools limits which of the server's tools the model can see, and require_approval set to never lets these read-only calls run without a person approving each one; always, the default, would pause every call. Function and openapi describe other tool kinds, tool_choice forces a call rather than filtering tools, include selects extra output, and auto is not a valid approval value.",
    syllabus: cite(TOOLS, "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/model-context-protocol", "Connect agents to Model Context Protocol servers"),
  }),
  gaps({
    id: "fm-g08", domain: "gen", topic: "Comparing prompt versions",
    prompt: "A team must choose between two system prompts for a Microsoft Foundry RAG app. Complete the evaluation plan.",
    template: "Run both versions against the same {0}, score them with {1} to catch fabricated claims and with {2} to check that each answer addresses the question, and promote the version that improves without new safety failures.",
    blanks: [
      ["versioned test dataset", "latest sample of production traffic", "developer's chat history"],
      ["groundedness", "fluency", "coherence"],
      ["relevance", "similarity", "F1 score"],
    ],
    explanation: "A fixed, versioned dataset makes the two runs comparable, groundedness detects claims unsupported by retrieved context, and relevance measures whether the answer addresses the query. A shifting production sample or chat history changes between runs, fluency and coherence judge style, and similarity and F1 compare wording with a reference answer.",
    syllabus: cite("Evaluate models and apps, including detecting fabrications, relevance, quality, and safety", "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators", "Built-in evaluators reference"),
  }),
  gaps({
    id: "fm-g09", domain: "gen", topic: "Error analysis",
    prompt: "About 5 percent of a deployed Microsoft Foundry agent's conversations fail. Complete the error-analysis process.",
    template: "Filter traces to {0}, group the failed runs by {1}, and add representative failures to the {2} so that the fix is verified in the next release.",
    blanks: [
      ["failed runs and low evaluator scores", "the newest traces only", "the longest conversations"],
      ["the step that failed", "the user's browser version", "the deployment's region"],
      ["regression evaluation dataset", "system prompt as examples", "content filter blocklist"],
    ],
    explanation: "Failures and low scores identify the conversations worth studying, grouping them by the step that failed separates tool problems from retrieval or reasoning problems, and a regression dataset proves the fix holds in later releases. Recency, conversation length, browser, and region do not explain failures, pasting failures into the system prompt does not verify anything, and a blocklist filters content.",
    syllabus: cite("Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis", "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard", "Monitor agents with the Agent Monitoring Dashboard"),
  }),
  gaps({
    id: "fm-g10", domain: "gen", topic: "Hybrid LLM and rules",
    prompt: "A lender combines a Microsoft Foundry model with its credit policy. Complete the orchestration design.",
    template: "The model {0} the applicant's free-text answers into structured fields, a {1} applies the credit-policy thresholds, and the model {2} the decision letter from the rule outcome.",
    blanks: [
      ["extracts", "approves", "rejects"],
      ["deterministic rules engine", "larger reasoning model", "vector index"],
      ["drafts", "decides", "overrides"],
    ],
    explanation: "The model is good at turning free text into structure and at drafting prose, while a deterministic rules engine applies policy thresholds consistently and auditably. The model should never approve, reject, decide, or override the policy outcome, a larger model is still probabilistic, and a vector index retrieves content rather than applying rules.",
    syllabus: cite("Orchestrate multiple models, flows, or hybrid LLM and rules engines", "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization", "Governance and security for AI agents"),
  }),
  choose({
    id: "fm-g11", domain: "gen", topic: "Chunking for procedures",
    prompt: "An Azure AI Search RAG app over 300-page manuals often retrieves chunks that cut a procedure in half. Which two changes improve retrieval? Each correct answer presents part of the solution.",
    options: [
      "Chunk on headings from the layout Markdown",
      "Add overlap between consecutive chunks",
      "Raise the top parameter from 5 to 50 results",
      "Switch to a larger embedding model without re-chunking",
      "Remove the semantic ranker from the query",
    ],
    explanation: "Chunking on headings keeps each procedure together, and overlap preserves context across chunk boundaries. Returning 50 results adds noise without repairing split chunks, a larger embedding model still embeds broken chunks, and removing the semantic ranker makes ranking worse.",
    syllabus: cite(RAG, "https://learn.microsoft.com/azure/search/vector-search-how-to-chunk-documents", "Chunk documents for vector search"),
  }),
  choose({
    id: "fm-g12", domain: "gen", topic: "What to remember",
    prompt: "A Microsoft Foundry support agent must remember a customer's open case across sessions but forget payment details when the call ends. Which two design choices fit? Each correct answer presents part of the solution.",
    options: [
      "Store the case ID in durable per-customer memory",
      "Keep payment details only in the current conversation state",
      "Add every past transcript to the system instructions",
      "Share one conversation thread across all customers",
      "Save payment details in the agent's long-term memory",
    ],
    explanation: "Durable, per-customer memory holds the case ID across sessions, while payment details live only in the conversation state that ends with the call. Pasting every transcript into the instructions bloats the prompt and leaks history, a shared thread mixes customers, and long-term memory would keep the payment details the requirement says to forget.",
    syllabus: cite("Define agent roles, goals, conversation-tracking approach, and tool schemas", "https://learn.microsoft.com/azure/foundry/agents/overview", "Microsoft Foundry Agent Service"),
  }),
  choose({
    id: "fm-g13", domain: "gen", topic: "Tool schema quality",
    prompt: "A Microsoft Foundry agent often calls createTicket without a priority or with a free-text category. Which two schema changes reduce these errors? Each correct answer presents part of the solution.",
    options: [
      "Mark priority as required in the function's JSON schema",
      "Define category as an enum of the allowed values",
      "Remove the function description to shorten the prompt",
      "Rename the function to create_ticket_v2 for clarity",
      "Accept any string and correct the values after the call returns",
    ],
    explanation: "Required fields and enums tell the model exactly which arguments it must supply and which values are valid, and strict schemas enforce them. Removing the description gives the model less guidance, a new name changes nothing about the arguments, and fixing values afterward accepts bad calls instead of preventing them.",
    syllabus: cite("Define agent roles, goals, conversation-tracking approach, and tool schemas", "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice", "Best practices for using tools in Foundry Agent Service"),
  }),
  choose({
    id: "fm-g14", domain: "gen", topic: "Autonomous safeguards",
    prompt: "An autonomous Microsoft Foundry agent reorders stock every night. Which two safeguards limit the damage if it misbehaves? Each correct answer presents part of the solution.",
    options: [
      "A spending cap per run enforced by the purchasing API",
      "A kill switch that disables the agent's tools without redeploying",
      "A longer system prompt that describes good purchasing behavior in detail",
      "A higher reasoning effort for the nightly run",
      "An email report to the buyer once orders have been placed",
    ],
    explanation: "A cap enforced by the API bounds the cost of any single run, and a kill switch stops the agent immediately without a release. A longer prompt and more reasoning effort only make good behavior more likely, and a report after orders are placed arrives too late to prevent them.",
    syllabus: cite(SAFEGUARDS, "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice", "Best practices for using tools in Foundry Agent Service"),
  }),
  choose({
    id: "fm-g15", domain: "gen", topic: "Testing a fine-tuned model",
    correctCount: 1,
    prompt: "A team wants to evaluate a fine-tuned small model in Microsoft Foundry at the lowest cost, with low volume and no SLA required. Which deployment type fits?",
    options: [
      "Developer",
      "Regional Provisioned",
      "Data Zone Provisioned",
      "Global Batch",
      "Global Provisioned",
    ],
    explanation: "The Developer deployment type exists for evaluating fine-tuned models cheaply, with no SLA and limited capacity. Provisioned types reserve paid capacity that a low-volume test does not need, and Global Batch is for large asynchronous jobs rather than interactive evaluation.",
    syllabus: cite("Deploy and consume LLMs, small models, code models, and multimodal models", "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", "Deployment types for Microsoft Foundry Models"),
  }),
  choose({
    id: "fm-g16", domain: "gen", topic: "Self-critique loop",
    prompt: "A Microsoft Foundry pipeline drafts compliance summaries. Which two techniques implement a self-critique loop that catches unsupported claims before release? Each correct answer presents part of the solution.",
    options: [
      "A second pass that checks each claim against the source",
      "A groundedness gate that sends failing drafts back for revision",
      "Showing the model's hidden reasoning to end users as a citation",
      "Generating five drafts and releasing whichever one is the longest",
      "Raising the maximum output tokens so drafts include more detail",
    ],
    explanation: "Reflection means critiquing a draft against evidence and revising it, either through a second model pass or an evaluator gate that sends weak drafts back. Exposing hidden reasoning is not a quality control, the longest draft is not the most accurate, and more output tokens only make drafts longer.",
    syllabus: cite("Implement model reflection, chain-of-thought evaluations, and self-critique loops", "https://learn.microsoft.com/azure/foundry/concepts/observability", "Observability in generative AI"),
  }),
  choose({
    id: "fm-g17", domain: "gen", topic: "Explaining a cost jump",
    prompt: "Costs for a Microsoft Foundry agent rose sharply last week. Which two signals should the observability dashboard break out to explain the increase? Each correct answer presents part of the solution.",
    options: [
      "Input and output tokens for each agent run",
      "Model calls and tool calls made during each run",
      "The average user satisfaction score by week",
      "The count of responses blocked by content filters",
      "The number of Foundry projects in the subscription",
    ],
    explanation: "Cost follows tokens, and tokens multiply with the number of model and tool calls per run, so those two breakdowns show whether prompts grew or the agent started looping. Satisfaction scores, filter blocks, and the project count do not measure consumption.",
    syllabus: cite("Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns", "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup", "How to set up tracing in Microsoft Foundry"),
  }),

  // ===== Implement computer vision solutions =====
  match({
    id: "fm-v01", domain: "vision", topic: "Image request settings",
    prompt: "Match each goal to the Azure OpenAI gpt-image-1 request setting that achieves it.",
    targets: [
      "Keep a person's face consistent when editing a portrait",
      "Return an image with a transparent background",
      "Show partial previews while the image renders",
    ],
    answers: ["input_fidelity set to high", "background set to transparent with PNG output", "stream with partial_images"],
    distractors: ["n set to 10", "quality set to low"],
    explanation: "High input fidelity preserves features such as faces from the input image, a transparent background requires PNG output, and streaming with partial_images returns previews as the image renders. Setting n requests more images, and low quality trades detail for speed without any of these effects.",
    syllabus: cite("Select and apply appropriate generation and editing controls provided by the platform", "https://learn.microsoft.com/azure/foundry/openai/how-to/dall-e", "Generate images with Foundry Models"),
  }),
  match({
    id: "fm-v02", domain: "vision", topic: "Accessible descriptions",
    prompt: "A web team uses a Microsoft Foundry multimodal model to write image descriptions. Match each image to the description approach that meets accessibility guidelines.",
    targets: [
      "A decorative divider between page sections",
      "A product photo in a catalog grid",
      "A complex revenue chart in an annual report",
    ],
    answers: ["An empty alt attribute", "Short alt text naming the product and its key attribute", "Brief alt text plus an extended description of the data"],
    distractors: ["The image file name as the alt text", "A full paragraph in every alt attribute"],
    explanation: "Decorative images get an empty alt so screen readers skip them, informative images get concise alt text, and complex images such as charts get short alt text plus a longer description of the data. File names say nothing useful, and long paragraphs in every alt attribute overload screen-reader users.",
    syllabus: cite("Configure generation of alt‑text and extended image descriptions aligned to accessibility guidelines", "https://learn.microsoft.com/azure/foundry/openai/how-to/responses", "Responses API in Microsoft Foundry"),
  }),
  gaps({
    id: "fm-v03", domain: "vision", topic: "Image input",
    prompt: "A Microsoft Foundry app answers questions about photos of control panels, using only what the photo shows. Complete the Responses API request.",
    language: "python",
    template: "response = client.responses.create(\n    model=\"vision-prod\",\n    input=[{\n        \"role\": \"user\",\n        \"content\": [\n            {\"type\": \"{0}\", \"text\": \"Which valve is open? Answer only from the photo.\"},\n            {\"type\": \"{1}\", \"image_url\": f\"data:image/jpeg;base64,{b64}\"},\n        ],\n    }],\n)",
    blanks: [
      ["input_text", "text", "output_text"],
      ["input_image", "image_url", "image_file"],
    ],
    explanation: "In the Responses API, user content parts are typed input_text and input_image, and an image can be passed as a base64 data URL. text and image_url are the Chat Completions content types, output_text describes model output rather than input, and image_file is not a Responses input type.",
    syllabus: cite("Implement a solution that enables question‑answering grounded in visual evidence", "https://learn.microsoft.com/azure/foundry/openai/how-to/responses", "Responses API in Microsoft Foundry"),
  }),
  gaps({
    id: "fm-v04", domain: "vision", topic: "Video segments",
    prompt: "A training team analyzes a 60-minute safety video with Azure Content Understanding. Complete the design.",
    template: "The video analyzer {0} the video into segments, returns {1} for each one so results link back to the moment, and uses a field with the {2} method to describe what happens in each segment.",
    blanks: [
      ["splits", "transcodes", "compresses"],
      ["start and end timestamps", "file checksums", "bounding polygons only"],
      ["generate", "extract", "classify"],
    ],
    explanation: "Video analyzers split content into segments with start and end times, so each result links back to a moment in the video. Describing what happens is free-form content, so it uses generate; extract is supported for documents only, and classify picks from a fixed set of labels. Transcoding, compression, checksums, and polygons alone do not describe events.",
    syllabus: cite("Implement video analysis workflows to process and interpret video segments", "https://learn.microsoft.com/azure/ai-services/content-understanding/video/overview", "Content Understanding video solutions"),
  }),
  choose({
    id: "fm-v05", domain: "vision", topic: "Text hidden in photos",
    prompt: "A Microsoft Foundry agent reads photos that customers upload. Which two controls mitigate instructions hidden in the text of those photos? Each correct answer presents part of the solution.",
    options: [
      "Run Prompt Shields document-attack checks on the extracted text",
      "Pass extracted text to the model as delimited, untrusted data",
      "Convert every photo to grayscale before the model analyzes it",
      "Raise the image detail setting from auto to high for every photo",
      "Ask customers to confirm that their uploaded photos contain no text",
    ],
    explanation: "Text read from an image is an indirect-injection channel, so Prompt Shields screens it for document attacks and the prompt marks it as untrusted data rather than instructions. Grayscale and higher detail change image processing without stopping injected text, and a customer's confirmation cannot be relied on.",
    syllabus: cite("Detect and mitigate indirect prompt injection by using embedded text in images", "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection", "Prompt Shields"),
  }),
  choose({
    id: "fm-v06", domain: "vision", topic: "Marketplace image policy",
    prompt: "A marketplace must block uploaded images with sexual content at medium severity or above, and images of counterfeit logos. Which two Azure configurations meet this? Each correct answer presents part of the solution.",
    options: [
      "Content Safety image analysis with the sexual threshold at medium",
      "A Content Safety custom category trained on counterfeit examples",
      "A Content Safety text blocklist containing the protected brand names",
      "Prompt Shields document-attack checks applied to every image upload",
      "Groundedness detection run against the generated image captions",
    ],
    explanation: "Image analysis scores the standard sexual category, so a medium threshold blocks that content, and a custom category trained on examples detects counterfeit logos, which no standard category covers. A text blocklist applies to text, Prompt Shields detects prompt attacks, and groundedness detection checks claims against sources.",
    syllabus: cite("Implement filters to classify unsafe or disallowed visual content", "https://learn.microsoft.com/azure/ai-services/content-safety/overview", "What is Azure AI Content Safety?"),
  }),
  choose({
    id: "fm-v07", domain: "vision", topic: "Two caption lengths",
    correctCount: 1,
    prompt: "A news archive needs a one-line caption for each thumbnail and a detailed description for its accessibility page, both from the same photo. Which Microsoft Foundry approach fits?",
    options: [
      "Two multimodal prompts with explicit length and detail instructions",
      "OCR on the photo, using the recognized text as both captions",
      "Image generation from the photo's existing headline text",
      "A single detailed caption that is truncated to fit each thumbnail view",
      "Content Safety image analysis to label the photo's content",
    ],
    explanation: "A multimodal model can produce both a concise caption and a detailed description when each prompt states the length and level of detail required. OCR reads only the text in a photo, image generation creates new images, truncating one caption loses meaning, and Content Safety labels harm categories rather than describing scenes.",
    syllabus: cite("Configure apps to produce concise or detailed captions for single or multiple images", "https://learn.microsoft.com/azure/foundry/openai/how-to/responses", "Responses API in Microsoft Foundry"),
  }),

  // ===== Implement text analysis solutions =====
  match({
    id: "fm-l01", domain: "language", topic: "Language features",
    prompt: "A support team analyzes customer text with Azure Language. Match each analysis goal to the capability that delivers it.",
    targets: [
      "Pull product names and dates out of support emails",
      "Condense a 30-minute chat into three sentences",
      "Find the main talking points in survey comments",
    ],
    answers: ["Named entity recognition", "Abstractive summarization", "Key phrase extraction"],
    distractors: ["Speech translation", "Text to speech"],
    explanation: "Named entity recognition returns typed entities such as products and dates, abstractive summarization writes a short new summary, and key phrase extraction lists the main topics in each comment. Speech translation and text to speech work with audio rather than analyzing text.",
    syllabus: cite("Implement solutions to extract entities, topics, summaries, and structured JSON outputs by using generative prompting and Foundry Tools", "https://learn.microsoft.com/azure/ai-services/language-service/named-entity-recognition/overview", "What is named entity recognition (NER) in Azure Language?"),
  }),
  match({
    id: "fm-l02", domain: "language", topic: "Translation options",
    prompt: "A legal firm localizes content with Azure Translator. Pair each localization need with the Translator feature built for it.",
    targets: [
      "Translate 500 Word contracts and keep their formatting",
      "Use the company's approved terms for product names",
      "Translate one chat message into three languages in one call",
    ],
    answers: ["Document translation", "A glossary or a Custom Translator model", "Text translation with several target languages"],
    distractors: ["Transliteration", "Language detection only"],
    explanation: "Document translation processes whole files asynchronously and preserves their formatting, glossaries and Custom Translator models enforce domain terminology, and text translation accepts several target languages in one request. Transliteration converts scripts without translating, and language detection only identifies the source language.",
    syllabus: cite("Build solutions that translate text by using Azure Translator in Foundry Tools or LLM‑powered translation flows", "https://learn.microsoft.com/azure/ai-services/translator/document-translation/overview", "Document translation"),
  }),
  gaps({
    id: "fm-l03", domain: "language", topic: "Mid-call language switching",
    prompt: "Callers to an Azure Speech voice agent sometimes switch languages mid-call. Complete the Speech SDK code.",
    language: "python",
    template: "auto_detect = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(\n    languages=[\"en-US\", \"es-ES\", \"fr-FR\"])\nspeech_config.set_property(\n    speechsdk.PropertyId.SpeechServiceConnection_LanguageIdMode, \"{0}\")\nrecognizer = speechsdk.SpeechRecognizer(\n    speech_config=speech_config,\n    {1}=auto_detect,\n    audio_config=audio_config)\nrecognizer.{2}()",
    blanks: [
      ["Continuous", "AtStart", "Always"],
      ["auto_detect_source_language_config", "source_language_config", "language_detection_config"],
      ["start_continuous_recognition", "recognize_once", "start_keyword_recognition"],
    ],
    explanation: "Continuous language identification keeps detecting the language throughout the audio, whereas AtStart identifies it once in the first few seconds. The configuration is passed as auto_detect_source_language_config; source_language_config pins one fixed language, and language_detection_config is not a recognizer parameter. Continuous recognition processes the whole call; recognize_once stops after one utterance and keyword recognition waits for a wake word. Always is not a valid mode.",
    syllabus: cite("Integrate speech as an agent modality, including custom speech models", "https://learn.microsoft.com/azure/ai-services/speech-service/language-identification", "Language identification with Speech"),
  }),
  gaps({
    id: "fm-l04", domain: "language", topic: "Aspect-level sentiment",
    prompt: "A hotel group must know which aspects of a stay guests liked or disliked, not just overall sentiment. Complete the Azure Language request.",
    language: "json",
    template: "{\n  \"kind\": \"{0}\",\n  \"parameters\": { \"{1}\": true },\n  \"analysisInput\": { \"documents\": [\n    { \"id\": \"1\", \"language\": \"en\",\n      \"text\": \"The room was clean but the Wi-Fi kept dropping.\" }\n  ] }\n}",
    blanks: [
      ["SentimentAnalysis", "KeyPhraseExtraction", "EntityRecognition"],
      ["opinionMining", "loggingOptOut", "stringIndexType"],
    ],
    explanation: "Sentiment analysis with opinionMining set to true returns each aspect, such as the room or the Wi-Fi, with its own sentiment and the opinion words behind it. Key phrase extraction and entity recognition find topics and entities without sentiment, loggingOptOut controls service logging, and stringIndexType sets how text offsets are counted.",
    syllabus: cite("Configure detection of sentiment, tone, safety issues, and sensitive content", "https://learn.microsoft.com/azure/ai-services/language-service/sentiment-opinion-mining/overview", "Sentiment analysis and opinion mining"),
  }),
  gaps({
    id: "fm-l05", domain: "language", topic: "Multi-label classification",
    prompt: "A bank tags each complaint with every regulation it concerns, and one complaint can concern several. Complete the Azure Language design.",
    template: "Train a {0} custom text classification project, split the labeled documents into {1} sets, deploy the model, and call it with the {2} task.",
    blanks: [
      ["multi-label", "single-label", "conversational language understanding"],
      ["training and testing", "production and staging", "primary and backup"],
      ["CustomMultiLabelClassification", "CustomSingleLabelClassification", "CustomEntityRecognition"],
    ],
    explanation: "Because one complaint can carry several regulations, the project must be multi-label and is called with the CustomMultiLabelClassification task; single-label assigns only one class. Labeled data is split into training and testing sets so the model is evaluated on documents it has not seen. Conversational language understanding and custom entity recognition solve different problems, and production, staging, primary, and backup are not data splits.",
    syllabus: cite("Customize language model outputs for domain tasks, such as compliance summarization and domain extraction", "https://learn.microsoft.com/azure/ai-services/language-service/custom-text-classification/overview", "Custom text classification"),
  }),
  choose({
    id: "fm-l06", domain: "language", topic: "Tone from audio",
    prompt: "A Microsoft Foundry app must flag calls where the customer sounds angry, even when the words are polite. Which two components are appropriate? Each correct answer presents part of the solution.",
    options: [
      "An audio-input model deployment that receives the call audio",
      "A prompt asking for tone labels from a fixed set, with timestamps",
      "Sentiment analysis with opinion mining on the call transcript alone",
      "Text to speech of the transcript so a reviewer can listen to it",
      "Language detection on the recorded call audio to label each call",
    ],
    explanation: "Tone lives in the audio, so an audio-capable model has to hear it, and a prompt with fixed labels and timestamps makes the output consistent and reviewable. Transcript sentiment misses anger expressed through voice when the words are polite, text to speech discards the original voice, and language detection says nothing about tone.",
    syllabus: cite("Enable multimodal reasoning from audio inputs", "https://learn.microsoft.com/azure/foundry/openai/audio-completions-quickstart", "Get started with Azure OpenAI audio generation"),
  }),
  choose({
    id: "fm-l07", domain: "language", topic: "Spoken translation",
    prompt: "A conference app built on Azure Speech must show live Spanish captions of English talks and also speak the translation aloud. Which two settings are needed? Each correct answer presents part of the solution.",
    options: [
      "Add es as a target language on SpeechTranslationConfig",
      "Set a Spanish voice name for synthesized translation output",
      "Set the speech recognition language to es-ES",
      "Enable speaker diarization for the translation session",
      "Add the Spanish words to a phrase list on the recognizer",
    ],
    explanation: "Adding es as a target produces Spanish text, and setting a Spanish voice name makes the translation recognizer synthesize the translated audio. The recognition language must stay English because the talks are in English, diarization labels speakers, and a phrase list improves recognition of the source language rather than producing translation.",
    syllabus: cite("Translate speech into other languages by using language models and Foundry Tools", "https://learn.microsoft.com/azure/ai-services/speech-service/speech-translation", "Speech translation"),
  }),

  // ===== Implement information extraction solutions =====
  sequence({
    id: "fm-e01", domain: "extract", topic: "OCR enrichment order",
    prompt: "An Azure AI Search indexer processes scanned PDFs with image normalization turned on. Arrange the enrichment steps for one document in order.",
    steps: [
      "The indexer cracks the document and normalizes its images",
      "The OCR skill reads text from each normalized image",
      "The Merge skill inserts the OCR text into the page content",
      "The Split skill chunks the merged content",
    ],
    distractors: ["The semantic ranker reorders the finished chunks", "A Translator skill detects the language of the file name"],
    explanation: "Document cracking produces the normalized images the OCR skill reads, the Merge skill combines the recognized text with the page content, and the Split skill chunks the complete text. The semantic ranker runs at query time rather than during enrichment, and the language of a file name is irrelevant.",
    syllabus: cite("Configure RAG ingestion flow, including documents and using optical character recognition (OCR)", "https://learn.microsoft.com/azure/search/search-indexer-overview", "Indexers in Azure AI Search"),
  }),
  match({
    id: "fm-e02", domain: "extract", topic: "Field attributes",
    prompt: "Match each Azure AI Search requirement to the index field attribute that enables it.",
    targets: [
      "Restrict results to one department",
      "Match keywords in the policy text",
      "Order results by effective date",
      "Show document counts by category in the UI",
    ],
    answers: ["filterable", "searchable", "sortable", "facetable"],
    distractors: ["retrievable", "key"],
    explanation: "Filterable fields support filter expressions, searchable fields are tokenized for full-text search, sortable fields support ordering, and facetable fields return category counts. Retrievable only controls whether a field is returned in results, and key identifies each document uniquely.",
    syllabus: cite("Configure semantic search, hybrid search, and vector search for grounding", "https://learn.microsoft.com/azure/search/vector-search-how-to-create-index", "Create a vector index"),
  }),
  gaps({
    id: "fm-e03", domain: "extract", topic: "Vector field definition",
    prompt: "An Azure AI Search index stores embeddings from text-embedding-3-small at its default size. Complete the field definition.",
    language: "json",
    template: "{\n  \"name\": \"contentVector\",\n  \"type\": \"{0}\",\n  \"dimensions\": {1},\n  \"vectorSearchProfile\": \"hnsw-profile\",\n  \"searchable\": true\n}",
    blanks: [
      ["Collection(Edm.Single)", "Collection(Edm.String)", "Edm.String"],
      ["1536", "768", "3072"],
    ],
    explanation: "Vector fields use a collection of single-precision floats, Collection(Edm.Single), and the dimensions must equal the embedding size, which is 1,536 for text-embedding-3-small by default. String types cannot hold vectors, 3,072 is text-embedding-3-large's default, and 768 matches neither model.",
    syllabus: cite("Configure semantic search, hybrid search, and vector search for grounding", "https://learn.microsoft.com/azure/search/vector-search-how-to-create-index", "Create a vector index"),
  }),
  gaps({
    id: "fm-e04", domain: "extract", topic: "Content for RAG",
    prompt: "A team feeds mixed PDFs to an Azure AI Search RAG index by using Azure Content Understanding. Complete the design.",
    template: "Analyze each file to get layout-aware {0}, chunk on its {1}, and keep each chunk's {2} so that answers can cite their source.",
    blanks: [
      ["Markdown", "plain text without structure", "base64 page images"],
      ["section headings", "fixed 200-character windows", "file names"],
      ["page numbers", "file sizes", "upload times"],
    ],
    explanation: "Content Understanding returns layout-aware Markdown that preserves headings and tables, chunking on section headings keeps related content together, and page numbers make citations verifiable. Plain text loses structure, page images are not searchable text, fixed character windows split sections, and file names, sizes, and upload times cannot anchor a citation.",
    syllabus: cite("Produce clean, grounded representations to use with agents and RAG by using Content Understanding", "https://learn.microsoft.com/azure/ai-services/content-understanding/document/elements", "Document elements and spans"),
  }),
  choose({
    id: "fm-e05", domain: "extract", topic: "Keeping an index current",
    prompt: "An Azure AI Search index must stay current as 5,000 blobs change each day, and deleted blobs must disappear from search. Which two indexer configurations are required? Each correct answer presents part of the solution.",
    options: [
      "An indexer schedule that relies on blob change detection",
      "A deletion detection policy such as native blob soft delete",
      "A reset of the indexer before every scheduled run",
      "A higher replica count on the search service",
      "A scoring profile that boosts the modified-date field",
    ],
    explanation: "Blob indexers detect new and changed blobs from their last-modified time, so a schedule keeps the index current, and a deletion detection policy removes documents whose blobs were deleted. Resetting before each run reprocesses everything, replicas add query capacity, and a scoring profile changes ranking rather than content.",
    syllabus: cite("Ingest and index content, such as documents, images, audio, and video", "https://learn.microsoft.com/azure/search/search-howto-schedule-indexers", "Schedule an indexer"),
  }),
  choose({
    id: "fm-e06", domain: "extract", topic: "Custom and layout skills",
    prompt: "An Azure AI Search pipeline must tag each document with an internal product code from a company-hosted classifier and extract tables with their structure. Which two skills fit? Each correct answer presents part of the solution.",
    options: [
      "A custom Web API skill",
      "The Document Layout skill",
      "The Key Phrase Extraction skill",
      "The Entity Linking skill",
      "The Custom Entity Lookup skill",
    ],
    explanation: "A custom Web API skill calls any external endpoint, such as the company's classifier, and the Document Layout skill returns tables and sections with their structure intact. Key phrase extraction and entity linking analyze text without calling the classifier or preserving tables, and Custom Entity Lookup only matches terms from a fixed list rather than running the company's model.",
    syllabus: cite("Implement enrichment by using custom or built-in skills for text, images, and layout", "https://learn.microsoft.com/azure/search/cognitive-search-skill-document-intelligence-layout", "Document Layout skill"),
  }),
  choose({
    id: "fm-e07", domain: "extract", topic: "Varied invoice layouts",
    correctCount: 1,
    prompt: "A shipping firm receives invoices from 400 vendors, each with a different layout, and needs the vendor, total, and due date with confidence scores. Which Azure approach fits?",
    options: [
      "A Content Understanding analyzer with a three-field schema",
      "Azure AI Search with only the OCR skill in its skillset",
      "A separate template for each vendor in a rules engine",
      "Text translation of each invoice followed by regex parsing of fields",
      "Speech to text run on each scanned invoice image",
    ],
    explanation: "A Content Understanding analyzer extracts the schema's fields regardless of layout and can return confidence and source for each one. OCR alone returns unstructured text, 400 vendor templates are brittle to maintain, translation and regex add no understanding of layout, and speech to text does not read images.",
    syllabus: cite("Extract information by using multimodal pipelines that combine OCR, layout analysis, and field extraction", "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/analyzer-reference", "What is a Content Understanding analyzer?"),
  }),
];
