import type { CodeSample, Difficulty, DomainId, Question, QuestionCollection, SyllabusRef } from "./questions";

/**
 * MAINTAINED BY HAND. The generator that first produced this file no longer exists,
 * so edit the questions here directly.
 *
 * Claude-authored questions. Opt-in: they only enter a session when the
 * "Claude questions" checkbox is selected on the setup screen.
 *
 * Every item cites a verbatim bullet from the published AI-103 skills-measured
 * outline (see AI103_SYLLABUS in ./questions) plus a Microsoft Learn page for the
 * feature under test. The bank concentrates on syllabus bullets the original banks
 * do not reach, and on code-level Foundry SDK usage.
 */
const q = (
  id: string,
  collection: QuestionCollection,
  domain: DomainId,
  topic: string,
  difficulty: Difficulty,
  prompt: string,
  options: string[],
  explanation: string,
  syllabus: SyllabusRef,
  code?: CodeSample,
): Question => {
  // The correct answer is always authored first, then rotated to a deterministic
  // position so the answer key stays balanced across the bank.
  const shift = [...id].reduce((sum, character) => sum + character.charCodeAt(0), 0) % options.length;
  return {
    id,
    collection,
    source: "claude",
    domain,
    topic,
    difficulty,
    prompt,
    options: options.map((_, index) => options[(index + shift) % options.length]),
    correct: [(0 - shift + options.length) % options.length],
    explanation,
    syllabus,
    ...(code ? { code } : {}),
  };
};

export const CLAUDE_QUESTIONS: Question[] = [
  // --- Plan and manage an Azure AI solution ---
  q("cl-p01", "core", "plan", "Small language models", "Advanced",
    "A Foundry workload classifies 4 million short support tickets per day into twelve fixed categories. Accuracy is already acceptable on a small model in offline tests. Which model choice fits the task?",
    [
      "Deploy a small language model sized for the classification task",
      "Deploy the largest frontier reasoning model for every ticket",
      "Deploy a multimodal model and send each ticket as an image",
      "Deploy an embedding model and read its vectors as labels",
    ],
    "High-volume, narrow, well-specified tasks are what small language models are for. Frontier reasoning capacity is wasted spend here, and neither a multimodal nor an embedding deployment produces a category label directly.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Choose the appropriate Foundry services for generative AI and agents",
      bullet: "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router",
      docTitle: "Model router for Microsoft Foundry",
    },
  ),
  q("cl-p02", "core", "plan", "Foundry Tools selection", "Advanced",
    "An Azure team must redact patient identifiers from clinical notes with an auditable, versioned detection contract rather than free-form model judgment. Which Foundry choice matches the requirement?",
    [
      "A Foundry Tools service with a documented entity contract",
      "A general chat model prompted to remove anything sensitive",
      "An embedding model with a similarity cutoff for identifiers",
      "A fine-tuned image model applied to rendered note pages",
    ],
    "Deterministic, auditable detection with a published contract is the Foundry Tools case. A prompted chat model gives no stable contract, and embeddings or image models do not perform typed entity detection.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Choose the appropriate Foundry services for generative AI and agents",
      bullet: "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router",
      docTitle: "Model router for Microsoft Foundry",
    },
  ),
  q("cl-p03", "core", "plan", "Retrieval method", "Advanced",
    "An Azure AI Search corpus mixes product codes such as XR-4410B with long descriptive prose. Pure vector search misses the exact codes. Which retrieval method should the team adopt?",
    [
      "Hybrid retrieval that merges keyword and vector results with RRF",
      "Vector-only retrieval with a substantially larger embedding dimension",
      "Keyword-only retrieval with the semantic ranker switched off",
      "Vector-only retrieval with the similarity threshold lowered",
    ],
    "Hybrid search runs text and vector queries in parallel and fuses them with Reciprocal Rank Fusion, which fixes exact-token recall on SKUs while keeping conceptual matching. Vector-only retrieval misses the exact code regardless of threshold or embedding size, and keyword-only retrieval with the semantic ranker off loses the paraphrase.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Choose the appropriate Foundry services for generative AI and agents",
      bullet: "Choose an appropriate method for retrieval and indexing",
      docUrl: "https://learn.microsoft.com/azure/search/hybrid-search-overview",
      docTitle: "Hybrid search using vectors and full text",
    },
  ),
  q("cl-p04", "core", "plan", "Agent memory services", "Advanced",
    "A Foundry agent must recall a user's stated delivery preference across sessions that occur weeks apart, while policy documents stay in Azure AI Search. Which integration split is correct?",
    [
      "Durable agent memory for user preference; search for policy grounding",
      "Azure AI Search for user preference; agent memory for policy grounding",
      "One Azure AI Search index holding preferences and policies together",
      "The model system prompt holding preferences and policies together",
    ],
    "Per-user state that must survive sessions belongs in a durable memory store keyed to the identity, while shared reference content belongs in the retrieval index. Merging them into one index or the prompt breaks isolation and freshness.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Choose the appropriate Foundry services for generative AI and agents",
      bullet: "Choose appropriate memory, tool, and knowledge integration services for agent solutions",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq",
      docTitle: "What is Foundry IQ",
    },
  ),
  q("cl-p05", "core", "plan", "CI/CD promotion", "Advanced",
    "A Foundry project must promote agent changes from test to production through Azure Pipelines with no manual portal edits. Which pipeline design meets the requirement?",
    [
      "Version agent definitions and infrastructure, then gate on evaluation runs",
      "Export the production agent and hand-edit it in the portal each release",
      "Run the same agent definition and skip evaluation on minor prompt edits",
      "Publish directly to production and roll back after user reports arrive",
    ],
    "Treating agent definitions, prompts, and infrastructure as versioned artifacts and gating promotion on evaluation is what makes a release repeatable. Exporting and hand-editing in the portal is not reproducible, skipping evaluation on minor prompt edits removes the gate exactly where behaviour changes, and publishing first and rolling back on user reports makes production the test.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Set up AI solutions in Foundry",
      bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
      docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
      docTitle: "Run evaluations in the cloud by using the Foundry SDK",
    },
  ),
  q("cl-p06", "core", "plan", "Deployment options", "Advanced",
    "An Azure workload must keep model inference processing inside the EU data boundary and needs reserved, predictable throughput for a latency-sensitive agent. Which Foundry deployment type fits?",
    [
      "Data Zone Provisioned",
      "Global Provisioned Throughput",
      "Data Zone Batch",
      "Global Standard",
    ],
    "Data Zone constrains processing to the specified data zone and the provisioned tier reserves PTU capacity for predictable latency. Global types can process anywhere, Batch is asynchronous, and Developer carries no SLA.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Set up AI solutions in Foundry",
      bullet: "Choose appropriate deployment options",
      docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
      docTitle: "Deployment types for Microsoft Foundry Models",
    },
  ),
  q("cl-p07", "core", "plan", "Model drift monitoring", "Advanced",
    "A Foundry agent scored well at launch, but six months later users report degraded answers although no code changed. Which Azure monitoring design detects this earliest?",
    [
      "Continuous evaluation sampling live traffic against quality metrics",
      "A one-time predeployment evaluation repeated only after a code change",
      "Availability alerts on the model endpoint response status codes",
      "Monthly review of aggregate token consumption in cost reports",
    ],
    "Drift shows up as declining answer quality on unchanged code, so it needs continuous evaluation of sampled production traffic. Uptime and token totals stay healthy while quality falls.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Manage, monitor, and secure AI systems",
      bullet: "Monitor model performance, drift, safety events, and grounding quality",
      docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard",
      docTitle: "Monitor agents with the Agent Monitoring Dashboard",
    },
  ),
  q("cl-p08", "core", "plan", "Index health monitoring", "Advanced",
    "An Azure AI Search index behind a RAG app silently stopped receiving new documents, and grounding answers went stale. Which monitoring signal surfaces the problem first?",
    [
      "Indexer execution history with document counts and failure reasons",
      "Model deployment token-per-minute consumption on the chat completions endpoint",
      "Average response latency measured at the web application gateway",
      "Content Safety severity distribution across generated completions",
    ],
    "Ingestion health is an indexer concern: run history exposes stalled runs, skipped documents, and errors. Token, latency, and safety metrics stay normal while the corpus goes stale.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Manage, monitor, and secure AI systems",
      bullet: "Monitor data ingestion quality, search index health, and relevance performance",
      docUrl: "https://learn.microsoft.com/azure/search/search-indexer-overview",
      docTitle: "Indexers in Azure AI Search",
    },
  ),
  q("cl-p09", "core", "plan", "Oversight modes", "Advanced",
    "A Foundry agent may issue refunds up to a threshold automatically but larger refunds need a named approver. Where must that boundary be enforced?",
    [
      "In the tool authorization layer that validates amount and approval",
      "In the agent instructions describing when to request an approval",
      "In the Content Safety severity threshold applied to the response",
      "In the model temperature setting configured for the refund conversation",
    ],
    "An authorization boundary has to be enforced by code and identity outside the model. Instructions, safety filters, and sampling parameters are not access controls and can be talked around.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Implement responsible AI across generative AI and agentic systems",
      bullet: "Govern agent behavior with oversight modes, constraints, and tool-access controls",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
      docTitle: "Best practices for using tools in Foundry Agent Service",
    },
  ),

  // --- Implement generative AI and agentic solutions ---
  q("cl-g01", "core", "gen", "Parameter tuning", "Advanced",
    "A Foundry extraction service must return the same field values for the same invoice text on every call. Which generation parameter change best supports that?",
    [
      "Lower the sampling temperature and constrain the output schema",
      "Raise the sampling temperature and widen the output token budget",
      "Raise top_p toward one and remove the response format constraint",
      "Leave sampling at defaults and retry until two responses agree",
    ],
    "Deterministic extraction comes from reducing sampling randomness and constraining the output shape. Raising temperature or top_p increases variation, and retry-until-agreement multiplies cost without a guarantee.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Tune generation behavior, such as prompt engineering and adjusting model parameters",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs",
      docTitle: "Structured outputs",
    },
  ),
  q("cl-g02", "core", "gen", "Reasoning effort", "Advanced",
    "An Azure OpenAI reasoning deployment answers simple FAQ lookups with high latency and large token bills. Which adjustment addresses it without replacing the deployment?",
    [
      "Lower the reasoning effort for the simple request category",
      "Raise the reasoning effort so answers resolve in fewer turns",
      "Increase max output tokens so the model stops re-deliberating",
      "Send FAQ text as an image so the model reads it in one pass",
    ],
    "Reasoning effort controls how much internal work a reasoning model performs. Simple lookups do not need high effort, and raising effort or output limits increases cost rather than reducing it.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Tune generation behavior, such as prompt engineering and adjusting model parameters",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/reasoning",
      docTitle: "Azure OpenAI reasoning models",
    },
  ),
  q("cl-g03", "core", "gen", "Hybrid rules engines", "Advanced",
    "An Azure lending workflow must apply a fixed regulatory eligibility rule set and then have a Foundry model explain the outcome to the applicant. Which orchestration is correct?",
    [
      "Evaluate eligibility in the rules engine, then have the model explain it",
      "Have the model decide eligibility and cite the regulation in its answer",
      "Run rules and model in parallel and publish whichever finishes first",
      "Encode the regulation in the prompt and average both determinations",
    ],
    "Regulated determinations must come from deterministic, auditable rules, with the model communicating the outcome. Having the model decide and cite the regulation makes it the decision-maker, running both in parallel and publishing whichever finishes first is arbitrary, and averaging two determinations has no regulatory meaning.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Orchestrate multiple models, flows, or hybrid LLM and rules engines",
      docUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization",
      docTitle: "Governance and security for AI agents",
    },
  ),
  q("cl-g04", "core", "gen", "Model orchestration by cost", "Advanced",
    "A Foundry chat product handles a mix of trivial greetings and deep multi-step analysis on one endpoint, and spend is dominated by frontier-model calls. Which approach reduces cost with least code?",
    [
      "Deploy model router and let it select a model for each request",
      "Deploy only the smallest model and accept lower analysis quality",
      "Deploy only the frontier model and shorten every system prompt",
      "Deploy two endpoints and let the client alternate between them per request",
    ],
    "Model router is a single deployment that picks an underlying model per request based on prompt complexity, capturing savings on simple traffic while keeping frontier capability available.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Orchestrate multiple models, flows, or hybrid LLM and rules engines",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router",
      docTitle: "Model router for Microsoft Foundry",
    },
  ),
  q("cl-g05", "core", "gen", "Self-critique loops", "Advanced",
    "A Foundry summarizer occasionally states facts absent from the source document. Which reflection design reduces that without a second product?",
    [
      "Add a critique pass that checks each claim against the source text",
      "Add a critique pass that rates the summary's tone, style, and readability",
      "Regenerate the summary twice and publish the longer of the two",
      "Increase temperature so the model explores alternative phrasings",
    ],
    "A reflection pass only helps if it verifies claims against the grounding text. Rating tone, style, and readability checks nothing factual, publishing the longer of two regenerations is a length heuristic, and raising temperature increases variation rather than accuracy.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Implement model reflection, chain-of-thought evaluations, and self-critique loops",
      docUrl: "https://learn.microsoft.com/azure/foundry/concepts/observability",
      docTitle: "Observability in generative AI",
    },
  ),
  q("cl-g06", "core", "gen", "Reflection cost control", "Advanced",
    "A Foundry self-critique loop sometimes runs many revision rounds and blows the per-request latency budget. Which control keeps it production-safe?",
    [
      "Bound the revision rounds and return the best result with its state",
      "Allow unbounded revisions until the critic reports no further issues",
      "Remove the critic entirely and rely on the content filter to catch errors",
      "Run every revision round in parallel and merge the resulting texts",
    ],
    "Reflection loops need an explicit iteration ceiling and a defined outcome when the ceiling is hit. Unbounded loops break latency budgets, and the content filter does not judge factual quality.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Implement model reflection, chain-of-thought evaluations, and self-critique loops",
      docUrl: "https://learn.microsoft.com/azure/foundry/concepts/observability",
      docTitle: "Observability in generative AI",
    },
  ),
  q("cl-g07", "core", "gen", "Token analytics", "Advanced",
    "A Foundry agent's monthly spend tripled and the team must find which conversation step is responsible. Which telemetry design answers that?",
    [
      "Emit per-span token counts attributed to each model and tool step",
      "Emit one monthly total of prompt and completion tokens per project",
      "Emit the final assistant text for every conversation to a log table",
      "Emit request counts per endpoint without any token attribution",
    ],
    "Attributing prompt and completion tokens to individual spans is what localizes cost to a step. Project-level totals, response text, and bare request counts cannot isolate the offending stage.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Optimize and operationalize generative AI systems",
      bullet: "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns",
      docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
      docTitle: "How to set up tracing in Microsoft Foundry",
    },
  ),
  q("cl-g08", "core", "gen", "Conversation memory", "Advanced",
    "A stateless Foundry web tier must continue a multi-turn agent conversation after the pod restarts mid-dialogue. Which application design preserves continuity?",
    [
      "Persist the service conversation identifier bound to the signed-in user",
      "Persist the full prompt text in a client cookie and replay every past turn",
      "Persist the model deployment name and start a fresh conversation",
      "Persist the Application Insights operation identifier for that turn",
    ],
    "Continuation depends on durable service-side conversation state referenced by an identifier bound to the authenticated session. The deployment name identifies a model, the Application Insights operation identifier is telemetry, and replaying the full prompt text from a cookie re-bills every previous turn.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
  ),
  q("cl-g09", "core", "gen", "Tool schema design", "Advanced",
    "A Foundry agent frequently passes a customer identifier where an order identifier is required because both tool parameters are typed as plain strings named id1 and id2. What should change first?",
    [
      "Give each parameter a distinct name, description, and validation",
      "Raise the model temperature so the agent varies its argument choices",
      "Merge both parameters into one free-text field the model fills in",
      "Move both identifiers into the agent instructions as static values",
    ],
    "Tool selection and argument binding are driven by parameter names, descriptions, and types. Clear semantics plus server-side validation fix argument confusion; merging or hard-coding the values makes it worse.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
      docTitle: "Best practices for using tools in Foundry Agent Service",
    },
  ),
  q("cl-g10", "core", "gen", "Approval flow controls", "Advanced",
    "A semiautonomous Foundry agent drafts supplier payments overnight and a controller approves them each morning. Which design keeps the approval authoritative?",
    [
      "Persist drafts as pending records that a scoped approval API releases",
      "Let the agent mark its own drafts approved once its checks pass",
      "Treat a successful content-safety scan as the controller's approval",
      "Store an approval flag that any conversation turn is allowed to set true",
    ],
    "Approval must be durable state changed only through an authorized path. Letting the agent mark its own drafts approved removes the control, treating a content-safety scan as approval confuses harm with authorization, and a flag any conversation turn can set is settable by the requester.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
      docUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process",
      docTitle: "Process to build agents across your organization",
    },
  ),
  q("cl-g11", "core", "gen", "Agent error analysis", "Advanced",
    "A deployed Foundry agent fails roughly one in twenty conversations and the team must classify why. Which observability approach supports that analysis?",
    [
      "Correlate failed conversations to traces and score them with evaluators",
      "Count the total failed requests per day without conversation-level detail",
      "Read a sample of user satisfaction ratings with no linked telemetry",
      "Inspect only the model endpoint status codes for the failing window",
    ],
    "Error analysis needs the failing conversations joined to their traces and graded by evaluators so failures can be grouped by cause. Daily counts, unlinked ratings, and status codes do not explain why.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis",
      docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard",
      docTitle: "Monitor agents with the Agent Monitoring Dashboard",
    },
  ),

  // --- Implement computer vision solutions ---
  q("cl-v01", "core", "vision", "Alt-text generation", "Advanced",
    "A public-sector Azure portal must publish alt text for every uploaded product image to meet accessibility obligations. Which design produces accessible descriptions at ingestion time?",
    [
      "Call a Foundry multimodal model with an accessibility-scoped prompt per image",
      "Reuse the Azure AI Search semantic caption returned for the indexed image record",
      "Reuse the Azure AI Content Safety category label assigned to the image",
      "Reuse the uploaded file name and let assistive technology infer context",
    ],
    "Alt text is a generation task: a multimodal model prompted for a concise, purpose-aware description produces it. Search captions describe query relevance and Content Safety labels describe harm categories, so neither is an accessible description.",
    {
      domain: "Implement computer vision solutions (10–15%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Configure generation of alt‑text and extended image descriptions aligned to accessibility guidelines",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
  ),
  q("cl-v02", "core", "vision", "Extended descriptions", "Advanced",
    "An Azure learning platform needs a short alt attribute plus a long description for complex engineering diagrams. Which Foundry approach satisfies both needs?",
    [
      "Request a brief alt string and a separate detailed description per image",
      "Request one long description and truncate it to fill the alt attribute",
      "Request one brief alt string and repeat it as the long description",
      "Request optical character recognition text and use it to fill both fields",
    ],
    "Short alt text and an extended description serve different assistive purposes, so each is generated to its own brief. Truncating the long one produces a broken sentence, repeating the short one wastes the detail page, and raw optical character recognition text describes rendered characters rather than the diagram.",
    {
      domain: "Implement computer vision solutions (10–15%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Configure generation of alt‑text and extended image descriptions aligned to accessibility guidelines",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
  ),
  q("cl-v03", "core", "vision", "Content Understanding pro mode", "Advanced",
    "An Azure claim workflow must reconcile a policy schedule, a repair estimate, and an inspection report into one validated field set. Which Content Understanding configuration fits?",
    [
      "A pro mode analyzer that reasons across the multiple input documents",
      "A standard mode analyzer run once per file with results merged later",
      "A standard mode analyzer with the confidence threshold raised to one",
      "A classifier that splits each file and returns the page ranges only",
    ],
    "Pro mode adds reasoning across multiple input documents and reference knowledge, which is what cross-document reconciliation requires. Standard mode analyzes one file at a time, and a classifier only splits and routes.",
    {
      domain: "Implement computer vision solutions (10–15%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Configure single‑task and pro‑mode Content Understanding pipelines",
      docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/whats-new",
      docTitle: "What's new in Azure Content Understanding",
    },
  ),
  q("cl-v04", "core", "vision", "Video editing workflow", "Advanced",
    "An Azure marketing team has an approved generated video and needs the same scene with a warmer color palette, keeping framing and motion intact. Which operation fits?",
    [
      "Remix the completed video by its identifier with one targeted prompt",
      "Create a new video from the original text prompt at a higher resolution",
      "Create several new videos in parallel and select the closest match",
      "Extract the frames, recolor each one, and reassemble them as a file",
    ],
    "Remix references a completed video by identifier and applies a narrow adjustment while preserving structure, motion, and framing. Creating a new video from the original prompt at higher resolution discards the approved composition, generating several in parallel and picking one is wasteful and still unmoored, and extracting and recolouring frames by hand is not a platform operation.",
    {
      domain: "Implement computer vision solutions (10–15%)",
      skill: "Design and implement image- and video-generation solutions",
      bullet: "Implement workflows to edit generated videos",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/video-generation",
      docTitle: "Video generation with Sora 2",
    },
  ),
  q("cl-v05", "core", "vision", "Region identification", "Advanced",
    "An Azure inspection app must report which component in a photographed control panel is damaged and where it sits in the frame. Which output shape does the workflow need?",
    [
      "Identified components returned with their bounding regions in the image",
      "A single sentence describing the overall condition of the whole control panel",
      "A single similarity vector computed across the whole uploaded photo",
      "A harm category severity rating computed for the uploaded photo",
    ],
    "Locating a component requires per-object identification with region coordinates. A whole-image sentence, an image-level embedding, and a safety severity rating all discard the spatial information the task needs.",
    {
      domain: "Implement computer vision solutions (10–15%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Implement solutions that identify objects, components, or regions within images or video",
      docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/analyzer-reference",
      docTitle: "What is a Content Understanding analyzer?",
    },
  ),

  // --- Implement text analysis solutions ---
  q("cl-l01", "core", "language", "Audio input reasoning", "Advanced",
    "An Azure support tool must judge whether a recorded caller sounded frustrated, not merely what words were said. Which Foundry model configuration fits?",
    [
      "An audio-enabled model that accepts the recording as a direct input",
      "A text-only model reading a transcript produced by batch transcription",
      "A text-to-speech voice replaying the recording before classification",
      "A translation flow converting the recording into a second language",
    ],
    "Prosody and delivery survive only when the audio itself reaches the model, which is what audio-enabled deployments accept. A transcript discards the acoustic signal, and synthesis or translation add nothing.",
    {
      domain: "Implement text analysis solutions (10–15%)",
      skill: "Implement speech solutions",
      bullet: "Enable multimodal reasoning from audio inputs",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/audio-completions-quickstart",
      docTitle: "Get started with Azure OpenAI audio generation",
    },
  ),
  q("cl-l02", "core", "language", "Audio versus transcription", "Advanced",
    "An Azure compliance archive needs verbatim, speaker-labeled text of four-hour Teams recordings for later keyword search. Which Azure approach is most appropriate?",
    [
      "Batch transcription with diarization writing results after the job ends",
      "An audio-enabled chat model asked to summarize the full recording",
      "Real-time recognition held open for the entire duration of each recording",
      "A translation flow producing target-language text for each recording",
    ],
    "Verbatim archival text over long prerecorded audio is the batch transcription case, and diarization supplies speaker labels. An audio chat model summarizes rather than transcribes, and holding a real-time session open is fragile.",
    {
      domain: "Implement text analysis solutions (10–15%)",
      skill: "Implement speech solutions",
      bullet: "Enable multimodal reasoning from audio inputs",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/audio-completions-quickstart",
      docTitle: "Get started with Azure OpenAI audio generation",
    },
  ),
  q("cl-l03", "core", "language", "Compliance summarization", "Advanced",
    "An Azure bank needs deal-memo summaries that always contain the same six regulator-mandated headings in the same order. Which approach best enforces that?",
    [
      "Constrain the model to a structured schema naming each required heading",
      "Ask the model in prose to include all six headings somewhere in the text",
      "Generate a free-form summary and have a reviewer reorder the headings",
      "Generate six independent summaries and concatenate them in any order",
    ],
    "A structured output schema makes the required sections and their order part of the response contract rather than a request the model may drop. Prose instructions and manual reordering do not guarantee the shape.",
    {
      domain: "Implement text analysis solutions (10–15%)",
      skill: "Apply language model text analysis",
      bullet: "Customize language model outputs for domain tasks, such as compliance summarization and domain extraction",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs",
      docTitle: "Structured outputs",
    },
  ),
  q("cl-l04", "core", "language", "Tone and sensitive content", "Advanced",
    "An Azure moderation pipeline must flag customer messages that are hostile and separately flag messages that disclose payment card numbers. Which design is correct?",
    [
      "Run tone detection and sensitive-entity detection as separate signals",
      "Run tone detection alone and treat any hostile message as a disclosure",
      "Run sensitive-entity detection alone and infer hostility from its score",
      "Run one prompt asking the model for a single combined risk percentage",
    ],
    "Hostility and sensitive-data disclosure are independent conditions with different downstream handling, so each needs its own signal. Collapsing them into one score destroys the distinction the pipeline acts on.",
    {
      domain: "Implement text analysis solutions (10–15%)",
      skill: "Apply language model text analysis",
      bullet: "Configure detection of sentiment, tone, safety issues, and sensitive content",
      docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/analyzer-reference",
      docTitle: "What is a Content Understanding analyzer?",
    },
  ),

  // --- Implement information extraction solutions ---
  q("cl-e01", "core", "extract", "Multimodal ingestion", "Advanced",
    "An Azure knowledge base must make recorded webinars searchable alongside PDFs so answers can cite a timestamp in a recording. What must ingestion produce?",
    [
      "Transcribed segments indexed with their timestamps as retrievable fields",
      "A single embedding computed over each of the complete webinar recording files",
      "The webinar file names indexed without any transcribed segment text",
      "A summary paragraph per webinar with the source recording discarded",
    ],
    "Citing a moment requires the transcript to be chunked into segments whose timestamps are indexed and retrievable. One whole-file embedding, bare file names, and lone summaries all lose the position evidence.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Ingest and index content, such as documents, images, audio, and video",
      docUrl: "https://learn.microsoft.com/azure/search/vector-search-how-to-chunk-documents",
      docTitle: "Chunk documents for vector search",
    },
  ),
  q("cl-e02", "core", "extract", "Hybrid versus vector", "Advanced",
    "An Azure AI Search grounding layer must find both paraphrased concepts and exact contract clause numbers such as 7.4(b). Which query configuration is appropriate?",
    [
      "A hybrid query with semantic ranking applied to the fused result set",
      "A vector-only query with the nearest-neighbor candidate count raised",
      "A keyword-only query with the vector fields excluded from the index",
      "A vector-only query with a stricter similarity threshold per field",
    ],
    "Hybrid retrieval fuses keyword precision on exact tokens with vector recall on paraphrase, and semantic ranking reorders the merged set for relevance. Either mode alone drops one of the two required behaviors.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Configure semantic search, hybrid search, and vector search for grounding",
      docUrl: "https://learn.microsoft.com/azure/search/hybrid-search-how-to-query",
      docTitle: "Create a hybrid query in Azure AI Search",
    },
  ),
  q("cl-e03", "core", "extract", "Custom skill enrichment", "Advanced",
    "An Azure AI Search skillset must call an internal parts-taxonomy service during indexing to normalize each extracted component name. Which skillset element fits?",
    [
      "A custom skill that calls the internal service during enrichment",
      "A built-in key phrase skill applied to the extracted component name field",
      "A scoring profile that boosts documents with normalized names",
      "A synonym map that rewrites component names at query time only",
    ],
    "Calling proprietary logic during indexing is exactly what a custom skill provides. Key phrase extraction does not normalize, and scoring profiles and synonym maps act at query time rather than enriching stored content.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Implement enrichment by using custom or built-in skills for text, images, and layout",
      docUrl: "https://learn.microsoft.com/azure/search/search-indexer-overview",
      docTitle: "Indexers in Azure AI Search",
    },
  ),
  q("cl-e04", "core", "extract", "Retrieval as agent tool", "Advanced",
    "A Foundry agent must ground answers in an Azure AI Search knowledge base and return the passages it used as citations. Which integration is appropriate?",
    [
      "Attach the knowledge base as a retrieval tool that returns references",
      "Copy the indexed passages into the agent instruction text each release",
      "Let the model recall the indexed passages from its pretrained weights",
      "Return only the relevance scores and ask the model to reconstruct text",
    ],
    "Wiring the knowledge base in as a retrieval tool keeps grounding data current and returns source references for citation. Pasting content into instructions goes stale, and model recall is not grounding.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Connect retrieval pipelines directly to workflows and agent tools",
      docUrl: "https://learn.microsoft.com/azure/search/agentic-retrieval-overview",
      docTitle: "Agentic retrieval in Azure AI Search",
    },
  ),
  q("cl-e05", "core", "extract", "Markdown analyzers", "Advanced",
    "An Azure agent reasons over scanned regulatory filings where section nesting and table structure change the meaning. Which Content Understanding output should the analyzer produce?",
    [
      "Layout-aware Markdown that preserves heading levels and table structure",
      "A flat list of recognized text lines with heading and table cues removed",
      "One embedding vector per page with no human-readable text retained",
      "A rendered page image per section with no extracted text retained",
    ],
    "Downstream reasoning depends on structure, so the analyzer should emit layout-aware Markdown that keeps headings and tables intact. Flattened lines, bare vectors, and page images all discard that structure.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Extract content from documents",
      bullet: "Implement analyzers for generating structured or markdown outputs for downstream reasoning by using Content Understanding",
      docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/overview",
      docTitle: "Content Understanding document solutions",
    },
  ),

  // --- Foundry SDK track ---
  q("cl-s01", "sdk", "plan", "Project configuration", "Applied",
    "A containerized Azure service reads its Foundry project endpoint from configuration. Which value belongs in FOUNDRY_PROJECT_ENDPOINT for the new Foundry experience?",
    [
      "https://contoso.services.ai.azure.com/api/projects/support",
      "https://contoso.openai.azure.com/openai/v1/projects/support",
      "https://ai.azure.com/projects/contoso/support/endpoints",
      "https://support.cognitiveservices.azure.com/foundry/api",
    ],
    "The Foundry project client targets the project-scoped services.ai.azure.com host ending in /api/projects/<project>. The other hosts address the Azure OpenAI resource, the portal, or a classic Cognitive Services resource.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Set up AI solutions in Foundry",
      bullet: "Design Azure infrastructure for AI apps and agent-based solutions",
      docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
      docTitle: "Create a Foundry project",
    },
  ),
  q("cl-s02", "sdk", "gen", "Responses API call", "Applied",
    "A Foundry project deploys gpt-5-mini under the deployment name support-prod. Which call completes this Python snippet correctly?",
    [
      "client.responses.create(model=\"support-prod\", input=question)",
      "client.responses.create(model=\"gpt-5-mini\", prompt=question)",
      "client.completions.invoke(deployment=\"support-prod\", text=question)",
      "project.responses.run(deployment=\"support-prod\", message=question)",
    ],
    "Runtime inference targets the deployment name, not the catalog model name, and the Responses API takes the request content in input. The OpenAI-compatible client owns responses.create, not the project client.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build generative applications by using Foundry",
      bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
    {
      language: "python",
      snippet: "from azure.ai.projects import AIProjectClient\nfrom azure.identity import DefaultAzureCredential\n\nproject = AIProjectClient(endpoint=PROJECT_ENDPOINT, credential=DefaultAzureCredential())\nclient = project.get_openai_client()\n\nresponse = ___\nprint(response.output_text)",
    },
  ),
  q("cl-s03", "sdk", "gen", "Response streaming", "Advanced",
    "A Foundry chat interface must render tokens as they arrive and still keep the completed response object. What belongs where this snippet is marked?",
    [
      "Handle each typed event and keep the completed response from the stream",
      "Poll response.output_text on a timer while the request is still open",
      "Ignore the events and issue a second nonstreaming request afterwards",
      "Collect every event and discard them all once the first token is displayed",
    ],
    "The Responses stream emits typed events processed in order, with the terminal event carrying the completed response. Polling output_text while the create request is still pending reads an incomplete object, issuing a second nonstreaming request bills twice, and discarding the events once the first token appears loses the final state.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build generative applications by using Foundry",
      bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
    {
      language: "python",
      snippet: "stream = client.responses.create(\n    model=\"support-prod\",\n    input=question,\n    stream=True,\n)\n\nfor event in stream:\n    ___",
    },
  ),
  q("cl-s04", "sdk", "gen", "Structured outputs", "Advanced",
    "A Foundry service must return an object with exactly the fields in this schema and no others. Which detail of the snippet makes the contract strict?",
    [
      "additionalProperties is false and every field is listed as required",
      "The schema name is descriptive and the field types are all set to string",
      "The temperature is left at its default for the chosen deployment",
      "The input text repeats the field names the model should populate",
    ],
    "Strict structured output requires additionalProperties set to false and every property marked required. A descriptive schema name with string field types constrains nothing, leaving temperature at its default does not bound the shape, and repeating field names in the input is a request rather than a contract.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build generative applications by using Foundry",
      bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs",
      docTitle: "Structured outputs",
    },
    {
      language: "python",
      snippet: "schema = {\n    \"type\": \"object\",\n    \"properties\": {\n        \"vendor\": {\"type\": \"string\"},\n        \"total\":  {\"type\": \"number\"},\n    },\n    \"required\": [\"vendor\", \"total\"],\n    \"additionalProperties\": False,\n}\n\nresponse = client.responses.create(\n    model=\"extract-prod\",\n    input=invoice_text,\n    text={\"format\": {\"type\": \"json_schema\", \"name\": \"invoice\",\n                     \"schema\": schema, \"strict\": True}},\n)",
    },
  ),
  q("cl-s05", "sdk", "gen", "Function tool round trip", "Advanced",
    "The function named by a Foundry tool call raises an exception. What should the application send back so the conversation can continue correctly?",
    [
      "A tool output describing the failure so the model can respond to it",
      "Nothing, leaving the tool call unanswered until the user asks again",
      "The original arguments once more so the platform retries the call",
      "A fresh response request that omits the tools array altogether",

    ],
    "A tool call is an open turn, so the failure is reported back as that tool's output and the model explains it to the user. Leaving it unanswered strands the conversation, resubmitting arguments assumes a platform retry that does not exist, and dropping the tools array discards the call rather than answering it.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
      docTitle: "Best practices for using tools in Foundry Agent Service",
    },
    {
      language: "python",
      snippet: "for item in response.output:\n    if item.type == \"function_call\":\n        try:\n            result = dispatch(item.name, json.loads(item.arguments))\n        except ToolError as error:\n            ___",
    },
  ),
  q("cl-s06", "sdk", "plan", "Credential chain", "Applied",
    "This Foundry snippet works on a developer laptop but fails with a credential error in Azure Container Apps. What is the most likely cause?",
    [
      "No managed identity is assigned, so the chain finds no Azure credential",
      "DefaultAzureCredential cannot be used outside of local development",
      "The endpoint must be passed as a keyword argument named project_url",
      "The azure-identity package must be replaced by an interactive credential",
    ],
    "DefaultAzureCredential picks the Azure CLI identity locally and managed identity in Azure. Without an assigned identity and a project role, the chain has nothing to use in the container.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Manage, monitor, and secure AI systems",
      bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
      docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
      docTitle: "Get started with Microsoft Foundry SDK",
    },
    {
      language: "python",
      snippet: "from azure.ai.projects import AIProjectClient\nfrom azure.identity import DefaultAzureCredential\n\nproject = AIProjectClient(\n    endpoint=os.environ[\"FOUNDRY_PROJECT_ENDPOINT\"],\n    credential=DefaultAzureCredential(),\n)",
    },
  ),
  q("cl-s07", "sdk", "gen", "Async client lifecycle", "Applied",
    "A high-concurrency Foundry API creates a client per request as shown. Which correction avoids exhausting network resources?",
    [
      "Build the client once at startup and close it during shutdown",
      "Build a client per request and let collection reclaim the transport",
      "Build a client per request and reuse one event loop across threads",
      "Build the client inside the retry callback and keep it afterwards",
    ],
    "Async clients hold pooled connections, so build one at startup, reuse it, and close it deterministically. Reusing a single event loop across per-request clients does not stop the leak, leaving transport cleanup to collection is non-deterministic, and clients built inside retry callbacks are never released.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build generative applications by using Foundry",
      bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
      docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
      docTitle: "Get started with Microsoft Foundry SDK",
    },
    {
      language: "python",
      snippet: "async def handle(question: str) -> str:\n    project = AIProjectClient(endpoint=ENDPOINT, credential=cred)\n    client = project.get_openai_client()\n    response = await client.responses.create(model=\"support-prod\", input=question)\n    return response.output_text",
    },
  ),
  q("cl-s08", "sdk", "extract", "File search tool", "Advanced",
    "Files in a Foundry vector store are replaced monthly, and superseded versions must stop appearing in answers. What must the refresh design do?",
    [
      "Delete the superseded files from the vector store during the refresh",
      "Raise the file search result count so newer files outrank old ones",
      "Recreate the agent so that it points at the newest uploaded files",
      "Add an instruction telling the agent to prefer the recent documents",

    ],
    "File search answers from whatever the vector store holds, so removing the superseded files is what stops them being retrieved. Returning more results surfaces the old ones alongside the new, recreating the agent does not change the store it reads, and an instruction cannot suppress what retrieval already returned.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Connect retrieval pipelines directly to workflows and agent tools",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/file-search",
      docTitle: "File search tool for agents",
    },
    {
      language: "python",
      snippet: "store = client.vector_stores.create(name=\"policies\")\nclient.vector_stores.files.upload_and_poll(vector_store_id=store.id, file=open(\"2026.pdf\", \"rb\"))\n\n# monthly refresh\n___",
    },
  ),
  q("cl-s09", "sdk", "gen", "Code interpreter", "Applied",
    "A Foundry agent must compute quartiles from an uploaded CSV and return a rendered chart image. Which tool belongs in this snippet?",
    [
      "Code interpreter, which runs Python in a sandbox and emits files",
      "File search, which retrieves passages from an uploaded document",
      "A knowledge source, which grounds answers in indexed content",
      "A connected agent, which forwards the request to another agent",
    ],
    "Statistical computation and chart generation over a data file are what the sandboxed code interpreter provides. Retrieval tools return passages and cannot produce a plotted image.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/code-interpreter",
      docTitle: "Code Interpreter tool for Foundry agents",
    },
    {
      language: "python",
      snippet: "uploaded = client.files.create(file=open(\"sales.csv\", \"rb\"), purpose=\"assistants\")\n\nresponse = client.responses.create(\n    model=\"analytics-prod\",\n    input=\"Compute quartiles and plot them as a bar chart.\",\n    tools=[___],\n)",
    },
  ),
  q("cl-s10", "sdk", "gen", "MCP tool registration", "Advanced",
    "A Foundry agent registers an MCP server that exposes both read and delete operations. Which addition keeps authorization off the prompt?",
    [
      "Allow only the read tools and enforce identity checks at the server",
      "Allow every tool and describe deletion as discouraged in instructions",
      "Allow every tool and give the agent an administrator access token",
      "Allow every tool and rely on the content filter to block deletions",
    ],
    "Least privilege has to be expressed in the exposed tool set and enforced by the MCP server against the caller's identity. Instructions and content filters are not access controls.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
      docTitle: "Best practices for using tools in Foundry Agent Service",
    },
    {
      language: "python",
      snippet: "tools = [{\n    \"type\": \"mcp\",\n    \"server_label\": \"inventory\",\n    \"server_url\": MCP_SERVER_URL,\n    ___\n}]\n\nresponse = client.responses.create(model=\"ops-prod\", input=turn, tools=tools)",
    },
  ),
  q("cl-s11", "sdk", "gen", "Conversation continuation", "Advanced",
    "A Foundry web tier stores state in Redis so a conversation survives a restart. Which value must be persisted where this snippet is marked?",
    [
      "The conversation identifier returned by the previous response",
      "The full text of every previous prompt and completion pair",
      "The deployment name used for the first turn of the conversation",
      "The bearer token acquired when the first turn was submitted",
    ],
    "Continuation works by referencing the service-side conversation state through its identifier. Replaying full history re-bills every turn, and deployment names or tokens carry no dialogue state.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
    {
      language: "python",
      snippet: "previous = redis.get(f\"conv:{user_id}\")\n\nresponse = client.responses.create(\n    model=\"support-prod\",\n    input=question,\n    conversation=previous,\n)\n\nredis.set(f\"conv:{user_id}\", ___)",
    },
  ),
  q("cl-s12", "sdk", "extract", "Evaluation run polling", "Advanced",
    "A Foundry cloud evaluation is submitted from a job that may be restarted by the scheduler. Which handling belongs where this snippet is marked?",
    [
      "Persist the run identifier, then poll terminal state with a bounded loop",
      "Hold the request open and resubmit the evaluation after each timeout",
      "Create a new evaluation definition on every single status check that is made",
      "Treat the accepted submission response as the scored result dataset",
    ],
    "Cloud evaluation is asynchronous, so a durable run identifier plus bounded polling lets a restarted process resume instead of duplicating work. The submission response is not the scored output.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Connect retrieval pipelines directly to workflows and agent tools",
      docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
      docTitle: "Run evaluations in the cloud by using the Foundry SDK",
    },
    {
      language: "python",
      snippet: "evaluation = client.evals.create(name=\"grounding-suite\", data_source_config=CONFIG,\n                                testing_criteria=GRADERS)\nrun = client.evals.runs.create(eval_id=evaluation.id, data_source=DATASET)\n\n___",
    },
  ),
  q("cl-s13", "sdk", "gen", "JavaScript project client", "Applied",
    "A Node.js Foundry service must reach the project-scoped OpenAI-compatible surface. Which call completes this snippet?",
    [
      "project.getOpenAIClient()",
      "project.getResponsesManagementClient()",
      "AIProjectClient.fromOpenAIEndpoint(project)",
      "project.agents.createChatClient()",
    ],
    "The JavaScript project client exposes getOpenAIClient() for project-scoped OpenAI-shaped operations such as responses.create. getResponsesManagementClient, fromOpenAIEndpoint, and agents.createChatClient are not members of the client.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build generative applications by using Foundry",
      bullet: "Configure an application to connect to a Foundry project",
      docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
      docTitle: "Get started with Microsoft Foundry SDK",
    },
    {
      language: "javascript",
      snippet: "import { AIProjectClient } from \"@azure/ai-projects\";\nimport { DefaultAzureCredential } from \"@azure/identity\";\n\nconst project = new AIProjectClient(endpoint, new DefaultAzureCredential());\nconst client = ___;\n\nconst response = await client.responses.create({\n  model: \"support-prod\",\n  input: question,\n});",
    },
  ),
  q("cl-s14", "sdk", "plan", "Package selection", "Advanced",
    "A .NET Foundry project fails to build with ambiguous OpenAI response types after two packages were added. Which correction follows current guidance?",
    [
      "Remove the preview package and keep the stable OpenAI extensions package",
      "Keep both packages and alias each of the overlapping OpenAI response namespaces",
      "Remove both packages and call the project REST endpoint with HttpClient",
      "Keep both packages and pin them to the same major version number",
    ],
    "The stable and preview OpenAI integration packages define overlapping types and are not meant to be installed together. Aliasing or version pinning does not remove the duplicate definitions.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Set up AI solutions in Foundry",
      bullet: "Design Azure infrastructure for AI apps and agent-based solutions",
      docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
      docTitle: "Get started with Microsoft Foundry SDK",
    },
    {
      language: "csharp",
      snippet: "<ItemGroup>\n  <PackageReference Include=\"Azure.AI.Projects\" Version=\"2.0.0\" />\n  <PackageReference Include=\"Azure.AI.Extensions.OpenAI\" Version=\"1.0.0\" />\n  <PackageReference Include=\"Azure.AI.Projects.OpenAI\" Version=\"1.0.0-beta.1\" />\n</ItemGroup>",
    },
  ),
  q("cl-s15", "sdk", "plan", "Tracing enablement", "Advanced",
    "Foundry tracing is enabled on a project and the team must find why one agent turn took nine seconds. What must the trace contain to answer that?",
    [
      "Child spans timing each model, tool, and retrieval call in the turn",
      "The total token count for the conversation the turn belonged to",
      "The final assistant message with its content-filter annotations",
      "The model deployment name and the region that served the request",

    ],
    "Latency is attributed by timing each dependency separately within the turn, which is what correlated child spans provide. A conversation token total has no time dimension, the final message with its filter annotations describes output rather than duration, and the deployment name and region identify where it ran rather than what was slow.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Manage, monitor, and secure AI systems",
      bullet: "Monitor model performance, drift, safety events, and grounding quality",
      docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
      docTitle: "How to set up tracing in Microsoft Foundry",
    },
  ),
  q("cl-s16", "sdk", "plan", "Connection enumeration", "Applied",
    "A Foundry diagnostic utility must list the connections configured in a project and may receive credentials. Which handling is appropriate?",
    [
      "Request credentials only when required, keep them out of logs and traces",
      "Request credentials always and attach them to traces for later reproduction",
      "Request credentials always and return them to the browser over HTTPS",
      "Request credentials always and cache them keyed by the project name",
    ],
    "Connection credentials are secrets, so retrieve them only when required and keep them out of logs and traces. Returning them to the browser exposes them over the wire, caching them keyed by project keeps them resident, and attaching them to traces persists them in telemetry.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Manage, monitor, and secure AI systems",
      bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
      docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
      docTitle: "Create a Foundry project",
    },
  ),

  // --- Copilot Studio track ---
  q("cl-c01", "copilot", "gen", "Autonomous triggers", "Advanced",
    "A Copilot Studio agent may prepare supplier record changes overnight, but a steward must release them. Which design keeps that approval authoritative?",
    [
      "Queue the changes as pending records a scoped approval step releases",
      "Let the agent apply the changes and notify the steward afterwards",
      "Have the agent apply only the changes it rates as high confidence",
      "Record the steward's approval in a variable the conversation can set",

    ],
    "Approval is authoritative only when the change cannot take effect until an authorized step releases it. Applying first and notifying makes the steward a reviewer of completed work, a confidence rating is the agent judging itself, and a conversation-settable variable can be set by whoever is asking.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/autonomous-agents",
      docTitle: "Design autonomous agent capabilities",
    },
  ),
  q("cl-c02", "copilot", "gen", "Connected versus child agents", "Advanced",
    "A Copilot Studio procurement agent must call a finance agent that already exists in another Power Platform environment with its own tools and permissions. Which relationship applies?",
    [
      "A connected agent, which keeps its own orchestration and permissions",
      "A child agent, which always inherits the parent's full conversation",
      "A classic topic, which reproduces the finance logic inside the parent",
      "A knowledge source, which indexes the finance agent's documentation",
    ],
    "A separately owned agent with its own tools and privileges is consumed as a connected agent, and its context inclusion is configured explicitly. A child agent always receives the parent's context.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Implement orchestrated multi-agent solutions",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/multi-agent-patterns",
      docTitle: "Multi-agent orchestration patterns and best practices",
    },
  ),
  q("cl-c03", "copilot", "extract", "Knowledge versus live data", "Advanced",
    "A Copilot Studio agent answers both stable warranty-policy questions and questions about a specific customer's open ticket. Which source mapping is correct?",
    [
      "Knowledge for the policy text; an authenticated tool for the ticket state",
      "An authenticated tool for the policy text; knowledge for the ticket state",
      "Trigger phrases for the policy text and also for the live ticket state",
      "Model pretrained knowledge for the policy text and the ticket state",
    ],
    "Stable explanatory content suits a governed knowledge source, while per-customer live state must come from its authenticated system of record. Trigger phrases and pretrained recall are neither current nor authorized.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Connect retrieval pipelines directly to workflows and agent tools",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-copilot-studio",
      docTitle: "Knowledge sources in Copilot Studio",
    },
  ),
  q("cl-c04", "copilot", "plan", "Dataverse row security", "Advanced",
    "A Copilot Studio connector can both read and write to a finance system, but only reading was sanctioned. Which control enforces that boundary?",
    [
      "Expose only the read operations and scope the connection to match",
      "An agent instruction stating that write operations must not be used",
      "A topic condition evaluated after the connector call has returned",
      "A review of the connector's run history at the end of each month",

    ],
    "Tool access is bounded by what the connector exposes and what its connection is permitted to do, both enforced outside the model. An instruction not to write is guidance the model can depart from, a condition after the call runs once the write has happened, and a monthly run-history review detects misuse rather than preventing it.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Implement responsible AI across generative AI and agentic systems",
      bullet: "Govern agent behavior with oversight modes, constraints, and tool-access controls",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/security-and-governance",
      docTitle: "Copilot Studio security and governance",
    },
  ),
  q("cl-c05", "copilot", "gen", "Agent flows", "Advanced",
    "A Copilot Studio process must run a fixed six-step update with branching and connector calls, and ship inside a managed solution. Which component fits?",
    [
      "An agent flow, which is deterministic and solution-aware",
      "A generative answer, which composes a reply from knowledge",
      "A public website knowledge source refreshed on each publish",
      "An analytics conversation theme derived from production traffic",
    ],
    "Deterministic multistep automation that participates in Power Platform ALM is an agent flow. Generative answers, knowledge sources, and analytics views do not execute a branching update.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Implement orchestrated multi-agent solutions",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent",
      docTitle: "Use tools with custom agents",
    },
  ),
  q("cl-c06", "copilot", "gen", "MCP server governance", "Advanced",
    "An MCP server behind a Copilot Studio agent adds two tools and renames a third. What must the agent design account for before the change ships?",
    [
      "Re-validating selection, because names and descriptions drive it",
      "Republishing every topic that referred to the renamed tool by name",
      "Nothing, because the agent rediscovers the catalog at run time",
      "Enlarging the agent's context window to hold the bigger catalog",

    ],
    "Generative selection reads tool names and descriptions, so a rename or an addition changes which tool gets chosen and must be re-validated. Rediscovery finds the tools without confirming the agent still picks correctly, topics do not bind MCP tools by name, and catalog size is not what makes the choice wrong.",
    {
      domain: "Implement generative AI and agentic solutions (30–35%)",
      skill: "Build agents by using Foundry",
      bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent",
      docTitle: "Use tools with custom agents",
    },
  ),
  q("cl-c07", "copilot", "plan", "On-behalf-of tokens", "Advanced",
    "A Copilot Studio topic must hand the signed-in user's token to a trusted flow so a Microsoft Graph call runs as that user. Which authentication setting supplies it?",
    [
      "Authenticate manually, which exposes the user access token variable",
      "Authenticate with Microsoft, which exposes the user access token variable",
      "No authentication, with the user identifier collected in a question node",
      "Teams channel sharing, with the user identity read from the channel",
    ],
    "The user access token variable is available only with manual authentication. Authenticate with Microsoft supplies identity properties such as the user identifier but not the raw token.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Manage, monitor, and secure AI systems",
      bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication",
      docTitle: "Configure user authentication",
    },
  ),
  q("cl-c08", "copilot", "extract", "Evaluation test sets", "Advanced",
    "A Copilot Studio team must compare two agent versions on the same multi-turn scenarios before each release. Which capability supports that?",
    [
      "Agent evaluation with a reusable, versioned test set and scoring",
      "Ad hoc conversations in the test chat repeated before each release",
      "Post-release satisfaction surveys collected from production users",
      "Connector run-success percentages read from the flow run history",
    ],
    "Repeatable release gating needs a stored test set that is scored the same way across versions. Ad hoc chats are not comparable, and surveys or connector success rates measure something else.",
    {
      domain: "Implement information extraction solutions (10–15%)",
      skill: "Build retrieval and grounding pipelines",
      bullet: "Connect retrieval pipelines directly to workflows and agent tools",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/security-scan",
      docTitle: "Automatic security scan in Copilot Studio",
    },
  ),
  q("cl-c09", "copilot", "plan", "Environment promotion", "Advanced",
    "A Copilot Studio release pipeline currently checks only that the managed solution imports. What should the architect add so behaviour regressions are caught before production?",
    [
      "A scored agent evaluation run against a versioned test set",
      "A longer soak period in the test environment before promotion",
      "A larger set of test-chat conversations run by the maker",
      "A check that every topic carries at least one trigger phrase",

    ],
    "An import check proves the package is well formed, not that the agent still answers correctly, which needs a scored evaluation against stable cases. A soak period waits without measuring, maker test chats are not repeatable, and trigger phrase counts say nothing about answer quality.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Set up AI solutions in Foundry",
      bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/admin-data-loss-prevention",
      docTitle: "Configure data policies for agents",
    },
  ),
  q("cl-c10", "copilot", "plan", "Production governance", "Advanced",
    "An external auditor asks a Copilot Studio team to show what an agent did on a date eleven months ago and who approved it. Which retention design answers that?",
    [
      "Immutable trace and approval records kept for the whole audit period",
      "Analytics dashboards showing usage trends across the same period",
      "The current agent definition exported from the production solution",
      "Conversation transcripts retained in the authoring maker's environment",

    ],
    "Reconstructing a past action needs the trace and the approval record for that moment, held where the team cannot alter them. Usage trend dashboards aggregate away the individual action, a current definition export describes today rather than eleven months ago, and maker-held transcripts are neither complete nor tamper-evident.",
    {
      domain: "Plan and manage an Azure AI solution (25–30%)",
      skill: "Implement responsible AI across generative AI and agentic systems",
      bullet: "Implement auditing through trace logging, provenance metadata, and approval workflows",
      docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/admin-logging-copilot-studio",
      docTitle: "View Copilot Studio audit logs",
    },
  ),

  // --- Coverage completion: the last four uncited skills-measured bullets ---
  q("cl-p10", "core", "plan", "Service selection", "Advanced",
    "An Azure team must ground an agent in ten thousand internal documents, and separately needs one endpoint that answers questions about uploaded screenshots. Which service split fits?",
    [
      "Azure AI Search for document grounding; a multimodal model for the screenshots",
      "Azure AI Search for both the document grounding and the uploaded screenshots",
      "A multimodal model for both the document grounding and the screenshots",
      "Azure Content Safety for document grounding; Azure Translator for screenshots",
    ],
    "Vector and hybrid retrieval over a large private corpus is what Azure AI Search provides, while interpreting an arbitrary uploaded image is a multimodal model task. Neither service does the other's job, and Content Safety and Translator do neither.",
    {
      domain: "Plan and manage an Azure AI solution (25\u201330%)",
      skill: "Choose the appropriate Foundry services for generative AI and agents",
      bullet: "Choose the appropriate Foundry services for generative tasks, grounding, vector search, agent workflows, or multimodal processing",
      docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq",
      docTitle: "What is Foundry IQ?",
    },
  ),
  q("cl-v06", "core", "vision", "Caption detail level", "Applied",
    "An Azure media library shows a one-line summary under each thumbnail and a fuller paragraph on the detail page. Which approach produces both from the same image?",
    [
      "Request a concise caption and a detailed caption as two separate generations",
      "Request one detailed caption and truncate it at the thumbnail character limit",
      "Request one concise caption and repeat that same text on the detail page",
      "Request the extracted optical character recognition text for both surfaces",
    ],
    "Concise and detailed captions are separate outputs with different briefs, so each is generated to its own length and purpose. Truncating a long caption produces a broken sentence, and repeating the short one wastes the detail page.",
    {
      domain: "Implement computer vision solutions (10\u201315%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Configure apps to produce concise or detailed captions for single or multiple images",
      docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/image/overview",
      docTitle: "Content Understanding image solutions",
    },
  ),
  q("cl-v07", "core", "vision", "Visual question answering", "Advanced",
    "An Azure field application must answer free-form questions about a photographed wiring panel and point to the part of the image each answer relies on. Which design fits?",
    [
      "Send the image with the question and require the answer to cite visible evidence",
      "Send only a pregenerated caption of the image along with the user's question",
      "Send only the optical character recognition text found on the panel labels",
      "Send the image with no question and classify it against a fixed label set",
    ],
    "Grounded visual question answering needs both the image and the question in the same request, with the response constrained to cite what is visible. A caption or the label text alone answers only what those artifacts happened to capture.",
    {
      domain: "Implement computer vision solutions (10\u201315%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Implement a solution that enables question‑answering grounded in visual evidence",
      docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
      docTitle: "Responses API in Microsoft Foundry",
    },
  ),
  q("cl-v08", "core", "vision", "Video segment analysis", "Advanced",
    "An Azure training platform must let learners jump to the moment a specific procedure is demonstrated in a two-hour recording. What must the video analysis produce?",
    [
      "Segmented output with per-segment descriptions and their time ranges",
      "One overall summary paragraph describing the complete recording",
      "One embedding vector computed across the entire recording file",
      "A single representative keyframe extracted from the whole recording",
    ],
    "Jumping to a moment requires the video to be interpreted as timed segments whose descriptions carry their time ranges. A whole-video summary, one embedding, or a single keyframe all discard the position information the feature depends on.",
    {
      domain: "Implement computer vision solutions (10\u201315%)",
      skill: "Design and implement multimodal understanding workflows",
      bullet: "Implement video analysis workflows to process and interpret video segments",
      docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/video/overview",
      docTitle: "Content Understanding video solutions",
    },
  ),

];
