/**
 * Exam glossary, grouped by the same documentation trees as the Learn map, so both
 * reinforce one mental model. Each entry is the shortest definition that separates the
 * term from what it is confused with; `vs` names that neighbour where one exists.
 *
 * MAINTAINED BY HAND.
 */
export interface GlossaryEntry { term: string; definition: string; vs?: string; }
export interface GlossaryArea { key: string; label: string; root: string; entries: GlossaryEntry[]; }

export const GLOSSARY: GlossaryArea[] = [
  {
    key: "foundry", label: "Microsoft Foundry", root: "/azure/foundry/",
    entries: [
      { term: "AIProjectClient", definition: "The client for Foundry-native project operations: connections, project properties, and tracing setup.", vs: "The OpenAI-compatible client, which owns responses, agents, evaluations, and fine-tuning." },
      { term: "Cloud evaluation", definition: "Separates the evaluation definition from each run. Create the eval, create a run, poll to a terminal state, then retrieve scored results." },
      { term: "Code interpreter", definition: "Sandboxed Python execution that can run calculations over an uploaded file and emit artifacts such as charts.", vs: "File search, which returns passages and cannot compute or plot." },
      { term: "Continuous evaluation", definition: "Samples live production traffic and scores it against quality metrics. The only thing that catches drift, since nothing else changed.", vs: "Predeployment evaluation, which runs only when a release happens." },
      { term: "Conversation identifier", definition: "The service-side handle that lets a stateless tier resume a multi-turn conversation. Persist it bound to the signed-in user.", vs: "Replaying full prompt history, which works but re-bills every prior turn." },
      { term: "Data Zone", definition: "Processing stays inside a named boundary such as the United States, European Union, or Asia Pacific.", vs: "Global types, which may process in any region the model is deployed to." },
      { term: "DefaultAzureCredential", definition: "A credential chain that lands on the Azure CLI identity locally and on managed identity inside Azure. Code that works locally and fails in Azure usually has no identity assigned." },
      { term: "Deployment name", definition: "What you called the model when you deployed it. This is what runtime inference targets.", vs: "The catalog model name, which is what you picked from the shelf. The exam usually makes them differ." },
      { term: "Deployment type", definition: "Answers three questions at once: where data is processed (global, data zone, or single region), how you pay (standard, provisioned, or batch), and the performance profile." },
      { term: "Developer deployment", definition: "For evaluating a fine-tuned model. Twenty-four hour lifetime, no service-level agreement, no data residency guarantee." },
      { term: "Drift", definition: "Answer quality degrading over months with no code change. Uptime, token totals, and latency all stay healthy while it happens." },
      { term: "Evaluator", definition: "A built-in or custom grader. Column mappings bind dataset fields to the input names an evaluator expects." },
      { term: "File search", definition: "Managed retrieval over uploaded files through a vector store, with chunking and embedding handled for you.", vs: "Azure AI Search, which you reach for when you need control over the index schema and query." },
      { term: "Fine-tuning", definition: "Training a model on your own labeled data. Justified only when the task depends on private patterns no prompt can supply, and it creates permanent evaluation and retraining obligations." },
      { term: "Foundry Account Owner", definition: "Manages the resource: creates accounts, deploys models, rotates keys. Cannot build in projects without also holding Foundry User." },
      { term: "Foundry Agent Consumer", definition: "Least-privilege role for identities that only call an agent endpoint, without development access." },
      { term: "Foundry Agent Service", definition: "Hosts agents with instructions, tools, and conversation state, rather than you orchestrating the loop yourself." },
      { term: "Foundry IQ", definition: "A managed, permission-aware knowledge layer for agents, built on Azure AI Search.", vs: "Direct Azure AI Search, which you use when you need lower-level schema and query control." },
      { term: "Foundry project", definition: "The scope everything else hangs off. Roles are granted on it, tracing is configured on it, and project-scoped calls inherit its content filters and tool context." },
      { term: "Foundry project endpoint", definition: "https://<resource>.services.ai.azure.com/api/projects/<project>. The host is services.ai.azure.com; the path ends in /api/projects/.", vs: "The Azure OpenAI resource endpoint, which is <resource>.openai.azure.com." },
      { term: "Foundry Toolbox", definition: "A managed MCP endpoint for reusing a tool across agents and runtimes, with centralized credentials, versioning, and policy. Its tool search avoids sending every schema on every request." },
      { term: "Foundry User", definition: "The project data-plane role: build and test with pre-deployed models, no management writes.", vs: "Foundry Project Manager, which adds project creation, agent publishing, and model deployment." },
      { term: "Function calling", definition: "The model returns a request to call your function with JSON arguments. Your code validates, authorizes, executes, and returns the result. The platform never runs your function." },
      { term: "Global Batch", definition: "Asynchronous processing at roughly half the price, with up to a 24-hour turnaround." },
      { term: "Global Standard", definition: "Any region, pay per token. The default starting point: highest quota, broadest model availability, and new models land here first." },
      { term: "HTTP 429", definition: "Too many requests. Honor Retry-After, back off with bounded exponential delay plus jitter, and queue or shed load rather than retrying immediately." },
      { term: "Inpainting", definition: "Mask-based image editing. The mask defines the region to change; pixels outside it must be preserved." },
      { term: "Microsoft Foundry", definition: "The platform holding your models, agents, evaluations, tracing, connections, and project. The project is the unit of scope: access, tracing, content filters, and tools all attach to it." },
      { term: "Model Context Protocol", definition: "MCP. A standard for exposing a catalog of tools from several back-end systems through one protocol. The server keeps enforcing authentication and authorization." },
      { term: "Model router", definition: "A single deployment that picks an underlying model per request based on prompt complexity. Modes are balanced, cost, and quality." },
      { term: "Model subset", definition: "The allow-list of models a router may select from. It doubles as the failover set, so pick at least two." },
      { term: "OpenAI-compatible client", definition: "Obtained from the project client via get_openai_client() in Python or getOpenAIClient() in JavaScript. Owns the OpenAI-shaped surface.", vs: "AIProjectClient, which owns project metadata rather than inference." },
      { term: "output_text", definition: "Convenience property aggregating the text output items of a response into one string." },
      { term: "Provisioned throughput", definition: "Reserved capacity sized in PTUs, giving predictable latency. PTUs are model-independent and region-specific, and the throughput a given count delivers varies by model.", vs: "Standard, which is pay-per-token with no reservation." },
      { term: "Quota", definition: "Capacity scoped by subscription, region, model, and offer. Unused capacity in one region does not help another." },
      { term: "Reasoning effort", definition: "How much internal deliberation a reasoning model performs on a request. Lower it for simple lookups.", vs: "Reasoning mode (standard or pro), which is a separate control." },
      { term: "Remix", definition: "Applies one targeted change to a completed video by its identifier, preserving framing, motion, and scene structure.", vs: "Regenerating from the original prompt, which discards the approved composition." },
      { term: "Responses API", definition: "The inference surface. client.responses.create(model=..., input=...). The model field takes the deployment name, not the catalog model name.", vs: "Chat Completions, the older surface where a schema goes in response_format rather than text.format." },
      { term: "Small language model", definition: "A narrow, cheap, fast model. The right answer when volume is high, the task is fixed, and offline testing already shows sufficient accuracy." },
      { term: "Sora 2", definition: "Video generation. Create returns a job you poll to a terminal state, then download." },
      { term: "Structured outputs", definition: "Constrains a response to a JSON Schema. Strict adherence needs every property listed as required and additionalProperties set to false.", vs: "JSON mode, which guarantees valid JSON but not your schema." },
      { term: "Task adherence", definition: "The Foundry agent evaluator measuring whether the agent followed its instructions and acted at the right time.", vs: "Azure AI Content Safety, which assesses content harm rather than whether an action was appropriate." },
      { term: "Trace and span", definition: "A trace is one end-to-end operation; a span is one step inside it. Per-span token counts are what localize cost or latency to a step." },
      { term: "Vector store", definition: "The managed container file search retrieves from. Superseded files must be deleted from it or they keep being returned." },
    ],
  },
  {
    key: "search", label: "Azure AI Search", root: "/azure/search/",
    entries: [
      { term: "Agentic retrieval", definition: "A multi-query pipeline: a knowledge base plans subqueries, runs them in parallel across knowledge sources, reranks, and returns merged content with references.", vs: "Classic RAG, which is a single hybrid query with semantic ranking." },
      { term: "Chunking", definition: "Subdividing large documents so portions match independently. If you want to cite a page or timestamp, the chunk must carry it as a retrievable field." },
      { term: "Custom skill", definition: "Your own code called over HTTP during enrichment. The way to bring proprietary logic into indexing." },
      { term: "Data source", definition: "Where the content actually lives: Blob Storage, a database, SharePoint, and so on." },
      { term: "Hybrid search", definition: "Runs keyword and vector queries in parallel in one request and fuses the results. The standard answer when you need both exact-token recall and paraphrase." },
      { term: "Index", definition: "The searchable structure: fields, types, and attributes such as searchable, filterable, and retrievable.", vs: "The indexer, which is the process that fills it." },
      { term: "Index projection", definition: "Maps one enriched source document to many child chunk documents, keeping parent-child relationships and provenance." },
      { term: "Indexer", definition: "Pulls from a data source, runs the skillset, and writes into the index, on a schedule or on demand. Its execution history is where stalled ingestion shows up." },
      { term: "Integrated vectorization", definition: "Azure AI Search generates the embeddings during indexing via a configured vectorizer, rather than you computing them and pushing them in." },
      { term: "Knowledge base", definition: "Orchestrates agentic retrieval: references knowledge sources and defines retrieval behavior.", vs: "A knowledge source, which defines the content itself." },
      { term: "Knowledge source", definition: "Defines content for retrieval. Indexed sources are backed by a search index; remote sources are queried live from an external platform." },
      { term: "OData filter", definition: "Restricts the result set. Built from verified identity claims, this is the mechanism behind security trimming." },
      { term: "Reciprocal Rank Fusion", definition: "RRF. The algorithm that merges the parallel keyword and vector result sets into one ranked list." },
      { term: "Retrieval reasoning effort", definition: "Controls how much planning the pipeline does: minimal skips the planning model entirely, low is the default, medium maximizes relevance." },
      { term: "Scoring profile", definition: "Boosts specific fields or criteria at query time." },
      { term: "Security trimming", definition: "Filtering retrieval by verified identity before generation, so unauthorized content never enters model context.", vs: "Instructing the model to omit content, which means it was already retrieved." },
      { term: "Semantic ranker", definition: "Level-two reranking that re-scores merged results by meaning. Requires a semantic configuration naming the title and content fields.", vs: "Hybrid search, which is about running both query types; the ranker is about reordering what comes back." },
      { term: "Skillset", definition: "The enrichment pipeline the indexer runs, made of built-in and custom skills. Skills run at indexing time.", vs: "Scoring profiles and synonym maps, which act at query time." },
      { term: "vectorFilterMode", definition: "preFilter applies the filter before the vector search, which is what you want when the filter is highly selective and you cannot afford to miss matches.", vs: "postFilter, which filters after and can return too few results." },
      { term: "Vectorizer", definition: "The component that turns query text into a vector at query time. It must match the embedding model and vector profile used at indexing time." },
    ],
  },
  {
    key: "tools", label: "Foundry Tools and Azure AI services", root: "/azure/ai-services/",
    entries: [
      { term: "Alt text", definition: "A concise, purpose-aware description written for someone who cannot see the image. A generation task.", vs: "A search semantic caption, which explains query relevance, and a Content Safety label, which names a harm category." },
      { term: "Analyzer", definition: "The unit of Content Understanding configuration. Its field schema defines what structured data comes out." },
      { term: "Audio-enabled model", definition: "Accepts the recording itself as input, so prosody and delivery reach the model. Needed when the signal is acoustic rather than lexical.", vs: "A transcript, which discards everything but the words." },
      { term: "Azure AI Content Safety", definition: "Harm detection: content filters, blocklists, groundedness detection, protected material detection, and Prompt Shields." },
      { term: "Azure Content Understanding", definition: "Extraction from documents, images, video, and audio into typed fields plus clean markdown." },
      { term: "Azure Speech", definition: "Speech to text, text to speech, translation, diarization, and custom speech." },
      { term: "Azure Translator", definition: "Text translation is synchronous, for strings. Document Translation is asynchronous, for whole files with formatting preserved." },
      { term: "Batch transcription", definition: "Asynchronous transcription of long prerecorded audio. Pair with diarization for speaker labels.", vs: "Fast transcription, which is synchronous for prerecorded audio you want back in one call." },
      { term: "Classifier", definition: "Splits one file containing several documents into logical documents and routes each to a field-extraction analyzer.", vs: "Pro mode, which reconciles across separate documents rather than splitting one." },
      { term: "Content filter", definition: "Severity thresholds across the standard harm categories, configured per deployment.", vs: "A blocklist, which covers your own terms that the standard categories do not." },
      { term: "Continuous recognition", definition: "Real-time recognition emitting recognizing events for interim partial text and recognized events for final text per segment.", vs: "Batch transcription, which is asynchronous and for long prerecorded audio." },
      { term: "Custom Translator", definition: "Trains and publishes a domain model so brand names and industry terminology survive translation." },
      { term: "Diarization", definition: "Speaker labeling: which speaker said which phrase." },
      { term: "Field method", definition: "Per-field extraction behavior. extract copies a value as it appears, generate synthesizes an interpretive value, classify chooses from a set." },
      { term: "Foundry Tools", definition: "The purpose-built services: Content Understanding, Content Safety, Speech, Translator, Language. Reach for one when the requirement wants an auditable, versioned contract rather than free-form model judgment." },
      { term: "Groundedness detection", definition: "Checks whether a generated claim actually appears in the supplied source material. The fabrication check." },
      { term: "Indirect prompt injection", definition: "Instructions hidden in content the system reads — a document, an image's embedded text, a tool response. Treat retrieved text as data, never as instruction." },
      { term: "Language identification", definition: "Detects which language is being spoken from a bounded candidate list. Constraining the candidates matters for latency." },
      { term: "Layout-aware Markdown", definition: "Output preserving heading levels and table structure, so downstream reasoning keeps the structure that carries meaning." },
      { term: "Phrase list", definition: "A lightweight runtime hint improving recognition of a small set of specific terms. The first thing to try.", vs: "Custom speech, which trains a model and is warranted only when broader domain errors remain." },
      { term: "PII detection", definition: "Azure AI Language capability finding personally identifiable information, used to redact before storage or downstream processing." },
      { term: "Pro mode", definition: "Content Understanding mode adding reasoning across multiple input documents plus an external knowledge base for linking and validation.", vs: "Standard mode, which analyzes one file at a time. Also unrelated to reasoning-model pro mode." },
      { term: "Prompt Shields", definition: "Detects prompt injection, both direct jailbreak attempts and indirect injection arriving through documents, images, or tool output." },
      { term: "SSML", definition: "Speech Synthesis Markup Language. Controls pronunciation, emphasis, pauses, and rate in text to speech." },
    ],
  },
  {
    key: "copilot", label: "Copilot Studio", root: "/microsoft-copilot-studio/",
    entries: [
      { term: "Agent evaluation", definition: "Runs a reusable, versioned test set and scores it, which is what makes two agent versions comparable across releases.", vs: "Test chat, which is exploratory and not repeatable." },
      { term: "Agent flow", definition: "Deterministic multi-step automation with branching and connector calls that participates in Power Platform solutions and ALM.", vs: "A topic, which handles conversation rather than execution." },
      { term: "Authenticate with Microsoft", definition: "Supplies Microsoft 365 and Teams identity properties such as User.ID and User.DisplayName.", vs: "Authenticate manually, which is the only option that exposes User.AccessToken." },
      { term: "Autonomous agent", definition: "Reacts to a configured event trigger with no user in the conversation. Requires scoped permissions, decision boundaries, and auditability." },
      { term: "Classic orchestration", definition: "Deterministic routing: the utterance matches authored trigger phrases and one topic executes." },
      { term: "Computer use", definition: "Automates applications and websites that expose no programmable interface, by driving the interface as a person would." },
      { term: "Connected agent", definition: "A separate agent with its own orchestration, tools, and permissions. Its context-inclusion setting controls whether it receives conversation history.", vs: "A child agent, which always receives the parent's context." },
      { term: "Fallback topic", definition: "The system topic handling utterances that match no topic. Where escalation is authored under classic orchestration." },
      { term: "Generative orchestration", definition: "Plans across multiple topics, tools, connected agents, and knowledge in one interaction. Selection is driven by component names and descriptions.", vs: "Classic orchestration, which matches an utterance to one authored topic." },
      { term: "Prompt action", definition: "Runs a reusable prompt as one step inside a topic, with typed inputs and outputs available to the rest of the flow." },
      { term: "Publish", definition: "Authentication and configuration changes take effect when the agent is published, not when the settings pane is saved." },
      { term: "Topic", definition: "A conversational unit with trigger phrases, nodes, and variables. Returns a typed output when the orchestrator needs to combine its result with other components." },
      { term: "User.AccessToken", definition: "The signed-in user's token, available only with manual authentication. Needed for on-behalf-of calls from a topic." },
      { term: "Variable scope", definition: "Topic scope stays inside one topic and exposes values only through explicit outputs; global is shared across a session; user persists across sessions." },
    ],
  },
  {
    key: "business", label: "Business applications and governance", root: "/dynamics365/ · /power-platform/",
    entries: [
      { term: "AI Builder", definition: "Power Platform's low-code AI capability, including prompts invoked from a canvas app so a draft returns into the form." },
      { term: "AI Center of Excellence", definition: "Scales governance through shared standards, reusable assets, and enablement rather than headcount. Not an approval board and not a central build team." },
      { term: "Build, buy, or extend", definition: "Favors the smallest custom surface that meets the requirement. Extending one gap keeps vendor support; rebuilding transfers permanent maintenance." },
      { term: "Business terms", definition: "A curated organizational vocabulary so domain abbreviations resolve consistently in Dynamics 365 Copilot rather than being guessed per conversation." },
      { term: "Cloud Adoption Framework", definition: "The AI adoption sequence: strategy, then plan, then ready, with govern and manage running continuously alongside adoption." },
      { term: "Connection reference", definition: "Keeps credentials outside the solution so one managed package promotes cleanly between environments." },
      { term: "Copilot for Sales and for Service", definition: "Role-specific experiences that pair with their audiences. Both read the same customer record system, so that connection is configured once." },
      { term: "Copilot hub", definition: "The Copilot area of the Power Platform admin center: usage insight and governance controls for AI features across environments." },
      { term: "Data policy", definition: "Power Platform DLP. Enforces which connectors, channels, and knowledge sources may be combined, at environment scope, regardless of maker intent." },
      { term: "Dataverse", definition: "The governed data platform behind Power Platform. Row-level authorization is enforced by its security roles in the signed-in user's context, never by agent instructions." },
      { term: "Environment variable", definition: "An ALM construct resolved per environment, keeping endpoints outside the deployable logic.", vs: "A global variable, which is conversation state within a session." },
      { term: "In-app help and guidance", definition: "Generative help in finance and operations apps, which can be supplemented with the organization's own approved documentation alongside product content." },
      { term: "Managed Environment", definition: "Applies stronger governance selectively to the environments where risk is highest, without slowing experimentation elsewhere." },
      { term: "Microsoft 365 Copilot", definition: "The employee-facing surface. Retrieval runs in the signed-in user's context, so existing permissions are enforced by the platform." },
      { term: "Microsoft Purview", definition: "Discovery, classification, and policy across AI interactions, which is what compliance needs rather than per-agent logs." },
      { term: "Power Platform pipelines", definition: "Promote managed solutions between environments with checks, rather than importing unmanaged solutions directly into production." },
      { term: "Power Platform Well-Architected", definition: "The framework for intelligent application workloads. Trade-offs between pillars are decided deliberately and recorded with their rationale." },
      { term: "Prebuilt agent", definition: "A supported capability that shortens time to value. Adopt it and scope build effort to the genuine remainder." },
      { term: "Task agent", definition: "Carries a bounded, repeatable process to completion, pausing cleanly when the process leaves its bounds.", vs: "A conversational assistant, where a person still drives the outcome." },
      { term: "Total cost of ownership", definition: "Build plus platform consumption plus the recurring cost of monitoring, evaluating, and tuning. The recurring part is what a first ROI model usually omits." },
    ],
  },
  {
    key: "cross", label: "Cross-cutting principles", root: "—",
    entries: [
      { term: "Access review", definition: "Periodic comparison of granted scope against current need, because access granted at launch drifts as reasons change." },
      { term: "ALM", definition: "Application lifecycle management. Agent definitions, prompts, tool configuration, grounding data, and infrastructure are all versioned artifacts that move together." },
      { term: "Approval boundary", definition: "Durable state changed only through an authorized path. An agent marking its own work approved, a safety scan, or a conversation-settable flag are not approvals." },
      { term: "Audit trail", definition: "Who changed what, when, and which version was live for each decision, held append-only outside the control of the team it records." },
      { term: "Data residency", definition: "Holds only if every processing and storage point honors it, including telemetry destinations, which teams most often overlook." },
      { term: "Enforced outside the model", definition: "The recurring principle: authorization lives in code and identity, never in instructions, content filters, or sampling parameters. It answers more exam questions than any single service name." },
      { term: "Held-out data", definition: "Data withheld from training, the only basis for estimating how a model behaves on cases it has not seen.", vs: "Training-set scores, which overstate performance." },
      { term: "Idempotency key", definition: "Makes a state-changing call safe to retry after an uncertain timeout. Pair it with an operation-status lookup before retrying." },
      { term: "Managed solution", definition: "The controlled, reversible promotion path with checks before production.", vs: "An unmanaged solution, which imported directly into production removes that boundary." },
      { term: "Separation of duties", definition: "No single identity should author, approve, and change the data a release depends on." },
      { term: "Shadow evaluation", definition: "Running a candidate model on live traffic without serving its answers, to compare it against production with no user exposure." },
    ],
  },
];

export const GLOSSARY_TERM_COUNT = GLOSSARY.reduce((n, area) => n + area.entries.length, 0);
