import type { ExamId } from "./questions";

/**
 * Microsoft Learn navigation map, generated by scripts/build-learn-map.mjs from the
 * citations already carried by every question. Regenerate with:
 *
 *   npm run build:learn-map
 *
 * Learn is available during associate and expert role-based exams, but no extra time
 * is given, so this map exists to make the handful of lookups you can afford fast.
 */
export interface LearnPage { url: string; title: string; questions: number; bullets: number; }
export interface LearnTree { root: string; rootUrl: string; label: string; questions: number; pages: LearnPage[]; }
export interface FastPath { answers: string; url: string; title: string; find: string; }
export interface LearnMapExam { code: string; name: string; totalQuestions: number; coreTrees: string[]; coreShare: number; trees: LearnTree[]; fastPaths: FastPath[]; }

export const LEARN_RULES: string[] = ["100 minutes, roughly 40 to 60 questions. That is about two minutes per question.","No extra time is added for Learn, and the exam timer keeps running while you read.","Microsoft states that using Learn on every question means you will not finish, by design.","The Learn pane opens at the home page every time. No bookmarks, no history, no sign-in.","Browsing is restricted to learn.microsoft.com. Q&A, Practice Assessments, and your profile are blocked.","Ctrl+F and Command+F find text on the current page only. They are not a site search.","You can open several Learn tabs and keep them open, and you can resize or maximize the pane.","After a break you cannot return to any question you have already seen."];
export const LEARN_BUDGET = "Five to eight lookups across the whole exam. Spend them on facts you cannot derive.";
export const LEARN_TRIAGE: { lookUp: string[]; dontLookUp: string[] } = {"lookUp":["Exact names from a table: deployment types, Foundry roles, evaluator names, analyzer methods.","Numeric limits: quotas, tokens per minute, service limits, page and size caps.","Availability: which model, feature, or deployment type exists in which region.","Strict API constraints: structured-output rules, supported models for a capability.","Locale and language support for Speech and Translator."],"dontLookUp":["Design and judgment questions asking which approach is best. You know the principle or you do not.","Anything inside a case study. The case text is the source and the clock is worst there.","Questions where you have already eliminated two options. Answer, flag, and move on.","Concepts you have never met. Reading an overview cold will cost three minutes and still not decide it."]};
export const LEARN_TAB_STRATEGY = "On your first lookup, open your exam's top two tree roots in separate tabs and leave them open. Every later lookup then starts one click from the right place instead of from the Learn home page.";
export const LEARN_DONT_BOTHER: string[] = ["Overview and 'What is' pages. They define the service without giving you the value you need.","Quickstarts and tutorials. They are step-by-step and never contain the comparison table.","Training modules under /training/. They are long-form learning, not reference.","Anything that needs more than one screen of reading to answer the question.","The certification study guides. You already know the objectives; they hold no product facts."];

export const LEARN_MAP: Record<ExamId, LearnMapExam> = {
  ai103: {
    code: "AI-103",
    name: "Developing AI Apps and Agents on Azure",
    totalQuestions: 438,
    coreTrees: ["azure/foundry","azure/ai-services","microsoft-copilot-studio","azure/search"],
    coreShare: 94,
    trees: [
      {
        root: "azure/foundry", rootUrl: "https://learn.microsoft.com/azure/foundry/", label: "Microsoft Foundry", questions: 230,
        pages: [
          { url: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses", title: "Responses API in Microsoft Foundry", questions: 31, bullets: 8 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice", title: "Best practices for using tools in Foundry Agent Service", questions: 27, bullets: 5 },
          { url: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code", title: "Get started with the Microsoft Foundry SDK", questions: 21, bullets: 6 },
          { url: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup", title: "How to set up tracing in Microsoft Foundry", questions: 17, bullets: 5 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry", title: "Authentication and authorization in Microsoft Foundry", questions: 14, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation", title: "Run evaluations in the cloud by using the Foundry SDK", questions: 13, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", title: "Deployment types for Microsoft Foundry Models", questions: 11, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry", title: "Role-based access control for Microsoft Foundry", questions: 10, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/how-to/create-projects", title: "Create a project for Microsoft Foundry", questions: 7, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits", title: "Foundry Models quotas and limits", questions: 7, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard", title: "Monitor agents with the Agent Monitoring Dashboard", questions: 7, bullets: 4 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs", title: "Structured outputs", questions: 7, bullets: 5 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators", title: "Built-in evaluators reference", questions: 6, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/how-to/dall-e", title: "Generate images with Foundry Models", questions: 6, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router", title: "Model router for Microsoft Foundry", questions: 5, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/concepts/video-generation", title: "Video generation with Sora 2", questions: 5, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/evaluation-evaluators/agent-evaluators", title: "Agent evaluators", questions: 4, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/code-interpreter", title: "Code Interpreter tool for Foundry agents", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/observability", title: "Observability in generative AI", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/file-search", title: "File search tool for agents", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/audio-completions-quickstart", title: "Get started with Azure OpenAI audio generation", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq", title: "What is Foundry IQ?", questions: 3, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/how-to/reasoning", title: "Azure OpenAI reasoning models", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/toolbox", title: "Foundry Toolbox", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/overview", title: "Microsoft Foundry Agent Service", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/manage-costs", title: "Plan and manage costs for Microsoft Foundry", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/how-to/evaluate-generative-ai-app", title: "Run evaluations from the Microsoft Foundry portal", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/concepts/provisioned-throughput", title: "What is provisioned throughput for Foundry Models?", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/how-to/agent-applications", title: "Agent applications in Microsoft Foundry", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/model-context-protocol", title: "Connect agents to Model Context Protocol servers", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/reference/region-support", title: "Feature availability across cloud regions", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "azure/ai-services", rootUrl: "https://learn.microsoft.com/azure/ai-services/", label: "Azure AI services and Foundry Tools", questions: 77,
        pages: [
          { url: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection", title: "Prompt Shields", questions: 8, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/overview", title: "Content Understanding document solutions", questions: 6, bullets: 4 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/analyzer-reference", title: "What is a Content Understanding analyzer?", questions: 6, bullets: 4 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/elements", title: "Document elements and spans", questions: 4, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/language-identification", title: "Language identification with Speech", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-translation", title: "Speech translation", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-safety/overview", title: "What is Azure AI Content Safety?", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/video/overview", title: "Content Understanding video solutions", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/custom-categories", title: "Custom categories in Azure AI Content Safety", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/language-service/personally-identifiable-information/overview", title: "Detect personally identifiable information", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/groundedness", title: "Groundedness detection", questions: 3, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/batch-transcription", title: "Batch transcription", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/language-service/custom-text-classification/overview", title: "Custom text classification", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/translator/document-translation/overview", title: "Document translation", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/fast-transcription-create", title: "Fast transcription", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/improve-accuracy-phrase-list", title: "Improve recognition accuracy with phrase lists", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/quickstart/use-rest-api", title: "Quickstart: Use Content Understanding", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/language-service/sentiment-opinion-mining/overview", title: "Sentiment analysis and opinion mining", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-synthesis-markup", title: "Speech Synthesis Markup Language", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-to-text", title: "Speech to text", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/overview", title: "What is Azure Content Understanding in Foundry Tools?", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/ai-services/translator/translator-overview", title: "What is Azure Translator in Foundry Tools?", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/image/overview", title: "Content Understanding image solutions", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/translator/custom-translator/overview", title: "Custom Translator", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/language-service/language-detection/overview", title: "Language detection", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/prebuilt-analyzers", title: "Prebuilt analyzers in Content Understanding", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/speech-service/get-started-stt-diarization", title: "Real-time diarization", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/language-service/named-entity-recognition/overview", title: "What is named entity recognition (NER) in Azure Language?", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/ai-services/content-understanding/whats-new", title: "What's new in Azure Content Understanding", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "microsoft-copilot-studio", rootUrl: "https://learn.microsoft.com/microsoft-copilot-studio/", label: "Microsoft Copilot Studio", questions: 54,
        pages: [
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication", title: "Configure user authentication", questions: 6, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-copilot-studio", title: "Knowledge sources in Copilot Studio", questions: 5, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent", title: "Use tools with custom agents", questions: 5, bullets: 3 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/advanced-generative-actions", title: "Generative orchestration in Copilot Studio", questions: 4, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-solutions-overview", title: "Solutions and ALM in Copilot Studio", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/admin-data-loss-prevention", title: "Configure data policies for agents", questions: 3, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-create-edit-topics", title: "Create and edit topics", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/admin-logging-copilot-studio", title: "View Copilot Studio audit logs", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-agent-evaluation-intro", title: "About agent evaluation", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-add-dataverse", title: "Add Dataverse as a knowledge source", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-overview", title: "Copilot Studio analytics overview", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/security-and-governance", title: "Copilot Studio security and governance", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/autonomous-agents", title: "Design autonomous agent capabilities", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-variables", title: "Work with variables", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-add-other-agents", title: "Add other agents overview", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/flows-overview", title: "Agent flows overview", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/security-scan", title: "Automatic security scan in Copilot Studio", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/requirements-messages-management", title: "Copilot Studio capacity and message management", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/agent-extend-action-mcp", title: "Extend an agent with Model Context Protocol", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/multi-agent-patterns", title: "Multi-agent orchestration patterns and best practices", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/publication-fundamentals-publish-channels", title: "Publish your agent", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-test-bot", title: "Test an agent", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-system-topics", title: "Use system topics", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "azure/search", rootUrl: "https://learn.microsoft.com/azure/search/", label: "Azure AI Search", questions: 50,
        pages: [
          { url: "https://learn.microsoft.com/azure/search/search-security-trimming-for-azure-search", title: "Security trimming for Azure AI Search", questions: 5, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/hybrid-search-overview", title: "Hybrid search in Azure AI Search", questions: 4, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/search-indexer-overview", title: "Indexers in Azure AI Search", questions: 4, bullets: 4 },
          { url: "https://learn.microsoft.com/azure/search/agentic-retrieval-overview", title: "Agentic retrieval in Azure AI Search", questions: 3, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/search/hybrid-search-how-to-query", title: "Create a hybrid query", questions: 3, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/vector-search-how-to-create-index", title: "Create a vector index", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/search-how-to-define-index-projections", title: "Define an index projection", questions: 3, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/cognitive-search-common-errors-warnings", title: "Indexer errors and warnings", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/vector-search-how-to-chunk-documents", title: "Chunk documents for vector search", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/vector-search-how-to-configure-vectorizer", title: "Configure a vectorizer", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/search-security-rbac", title: "Connect to Azure AI Search using roles", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/cognitive-search-skill-document-intelligence-layout", title: "Document Layout skill", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/vector-search-integrated-vectorization", title: "Integrated vectorization", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/search-howto-managed-identities-data-sources", title: "Managed identities for indexer connections", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/multimodal-search-overview", title: "Multimodal search in Azure AI Search", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/azure/search/search-howto-schedule-indexers", title: "Schedule an indexer", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/semantic-how-to-configure", title: "Configure semantic ranking", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/vector-search-how-to-query", title: "Create a vector query", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/search-filters", title: "Filters in Azure AI Search", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/search-query-overview", title: "Query types and composition", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/retrieval-augmented-generation-overview", title: "RAG in Azure AI Search", questions: 1, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/search/semantic-search-overview", title: "Semantic ranking in Azure AI Search", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "azure/cloud-adoption-framework", rootUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/", label: "Cloud Adoption Framework", questions: 9,
        pages: [
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process", title: "Process to build agents across your organization", questions: 6, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization", title: "Governance and security for AI agents", questions: 3, bullets: 1 },
        ],
      },
      {
        root: "agent-framework", rootUrl: "https://learn.microsoft.com/agent-framework/", label: "Microsoft Agent Framework", questions: 7,
        pages: [
          { url: "https://learn.microsoft.com/agent-framework/integrations/by-component/agent-services/foundry", title: "Foundry Agent Service in Agent Framework", questions: 5, bullets: 1 },
          { url: "https://learn.microsoft.com/agent-framework/workflows/orchestrations/", title: "Workflow orchestrations", questions: 2, bullets: 1 },
        ],
      },
      {
        root: "azure/ai-foundry", rootUrl: "https://learn.microsoft.com/azure/ai-foundry/", label: "Foundry (classic paths)", questions: 5,
        pages: [
          { url: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/content-filters", title: "Configure content filters", questions: 5, bullets: 3 },
        ],
      },
      {
        root: "azure/storage", rootUrl: "https://learn.microsoft.com/azure/storage/", label: "Azure Storage", questions: 2,
        pages: [
          { url: "https://learn.microsoft.com/azure/storage/blobs/storage-blob-user-delegation-sas-create-cli", title: "Create a user delegation SAS", questions: 2, bullets: 2 },
        ],
      },
      {
        root: "azure/private-link", rootUrl: "https://learn.microsoft.com/azure/private-link/", label: "azure/private-link", questions: 2,
        pages: [
          { url: "https://learn.microsoft.com/azure/private-link/private-endpoint-dns", title: "Azure Private Endpoint private DNS zone values", questions: 2, bullets: 1 },
        ],
      },
      {
        root: "power-apps", rootUrl: "https://learn.microsoft.com/power-apps/", label: "Power Apps", questions: 2,
        pages: [
          { url: "https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables", title: "Environment variables overview", questions: 2, bullets: 1 },
        ],
      },
    ],
    fastPaths: [
      { answers: "Which deployment type, and where data is processed", url: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", title: "Deployment types for Foundry Models", find: "Data Zone" },
      { answers: "Which Foundry role grants what", url: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry", title: "Role-based access control for Microsoft Foundry", find: "Project Manager" },
      { answers: "Quota, rate limits, tokens per minute", url: "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits", title: "Foundry Models quotas and limits", find: "tokens per minute" },
      { answers: "Which model is available in which region", url: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/models-sold-directly-by-azure-region-availability", title: "Region availability for Foundry Models sold by Azure", find: "the region name" },
      { answers: "What a model can do, and its context limits", url: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/models-sold-directly-by-azure", title: "Foundry Models sold by Azure", find: "the model name" },
      { answers: "Strict structured-output rules", url: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs", title: "Structured outputs", find: "additionalProperties" },
      { answers: "Content Understanding limits and pro mode", url: "https://learn.microsoft.com/azure/ai-services/content-understanding/service-limits", title: "Content Understanding service limits", find: "pro mode" },
      { answers: "Azure AI Search tier limits", url: "https://learn.microsoft.com/azure/search/search-limits-quotas-capacity", title: "Azure AI Search service limits", find: "the tier name" },
      { answers: "Speech locale and feature support", url: "https://learn.microsoft.com/azure/ai-services/speech-service/language-support", title: "Speech language and voice support", find: "the locale code" },
      { answers: "Which built-in evaluator measures what", url: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators", title: "Built-in evaluators reference", find: "task adherence" },
      { answers: "Which feature exists in which region", url: "https://learn.microsoft.com/azure/foundry/reference/region-support", title: "Foundry feature availability across regions", find: "the feature name" },
    ],
  },
  ab100: {
    code: "AB-100",
    name: "Agentic AI Business Solutions Architect",
    totalQuestions: 336,
    coreTrees: ["microsoft-copilot-studio","azure/foundry","power-platform","azure/cloud-adoption-framework","dynamics365","purview"],
    coreShare: 87,
    trees: [
      {
        root: "microsoft-copilot-studio", rootUrl: "https://learn.microsoft.com/microsoft-copilot-studio/", label: "Microsoft Copilot Studio", questions: 105,
        pages: [
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/prompts-overview", title: "Prompts in Copilot Studio", questions: 16, bullets: 5 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-agent-evaluation-intro", title: "About agent evaluation", questions: 12, bullets: 4 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-overview", title: "Copilot Studio analytics overview", questions: 11, bullets: 4 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/flows-overview", title: "Agent flows overview", questions: 8, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/computer-use", title: "Computer use in Copilot Studio", questions: 7, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/security-and-governance", title: "Copilot Studio security and governance", questions: 7, bullets: 3 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-copilot-studio", title: "Knowledge sources in Copilot Studio", questions: 7, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/autonomous-agents", title: "Design autonomous agent capabilities", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/agent-extend-action-mcp", title: "Extend an agent with Model Context Protocol", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/advanced-generative-actions", title: "Generative orchestration in Copilot Studio", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/multi-agent-patterns", title: "Multi-agent orchestration patterns", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/voice-overview", title: "Voice-enabled agents in Copilot Studio", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-solutions-overview", title: "Solutions and ALM in Copilot Studio", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-system-topics", title: "Use system topics", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-agent-evaluation-overview", title: "Choose evaluation methods", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/admin-data-loss-prevention", title: "Configure data policies for agents", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/requirements-messages-management", title: "Copilot Studio capacity and message management", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-themes", title: "Monitor user questions by theme", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent", title: "Use tools with custom agents", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication", title: "Configure user authentication", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "azure/foundry", rootUrl: "https://learn.microsoft.com/azure/foundry/", label: "Microsoft Foundry", questions: 46,
        pages: [
          { url: "https://learn.microsoft.com/azure/foundry/concepts/manage-costs", title: "Plan and manage costs for Microsoft Foundry", questions: 11, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators", title: "Built-in evaluators reference", questions: 9, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq", title: "What is Foundry IQ?", questions: 9, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard", title: "Monitor agents with the Agent Monitoring Dashboard", questions: 7, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router", title: "Model router for Microsoft Foundry", questions: 4, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry", title: "Role-based access control for Microsoft Foundry", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/agents/overview", title: "Microsoft Foundry Agent Service", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", title: "Deployment types for Microsoft Foundry Models", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "power-platform", rootUrl: "https://learn.microsoft.com/power-platform/", label: "Power Platform", questions: 44,
        pages: [
          { url: "https://learn.microsoft.com/power-platform/alm/pipelines", title: "Pipelines in Power Platform", questions: 7, bullets: 2 },
          { url: "https://learn.microsoft.com/power-platform/admin/wp-security-cds", title: "Dataverse security concepts", questions: 6, bullets: 1 },
          { url: "https://learn.microsoft.com/power-platform/well-architected/intelligent-application/", title: "Intelligent application workload", questions: 6, bullets: 3 },
          { url: "https://learn.microsoft.com/power-platform/alm/overview-alm", title: "Application lifecycle management in Power Platform", questions: 5, bullets: 3 },
          { url: "https://learn.microsoft.com/power-platform/well-architected/reliability/", title: "Well-Architected reliability pillar", questions: 4, bullets: 3 },
          { url: "https://learn.microsoft.com/power-platform/guidance/coe/starter-kit", title: "Center of Excellence starter kit", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/power-platform/admin/wp-data-loss-prevention", title: "Data loss prevention policies", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/power-platform/guidance/adoption/environment-strategy", title: "Environment strategy", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/power-platform/admin/managed-environment-overview", title: "Managed Environments overview", questions: 2, bullets: 2 },
          { url: "https://learn.microsoft.com/power-platform/guidance/adoption/methodology", title: "Power Platform adoption methodology", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/power-platform/admin/copilot/copilot-hub", title: "Track, manage, and scale Copilot adoption", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/power-platform/well-architected/", title: "Power Platform Well-Architected", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "azure/cloud-adoption-framework", rootUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/", label: "Cloud Adoption Framework", questions: 43,
        pages: [
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization", title: "Governance and security for AI agents", questions: 20, bullets: 7 },
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/data-architecture-plan", title: "Data architecture for AI agents", questions: 11, bullets: 3 },
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process", title: "Process to build agents across your organization", questions: 5, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/ai/", title: "AI adoption in the Cloud Adoption Framework", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/ai/strategy", title: "AI adoption: Strategy", questions: 3, bullets: 1 },
          { url: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/organization-people-readiness-plan", title: "Organizational readiness for AI agents", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "dynamics365", rootUrl: "https://learn.microsoft.com/dynamics365/", label: "Dynamics 365", questions: 40,
        pages: [
          { url: "https://learn.microsoft.com/dynamics365/copilot/ai-get-started", title: "Agents, Copilot, and AI capabilities in Dynamics 365 apps", questions: 13, bullets: 4 },
          { url: "https://learn.microsoft.com/dynamics365/customer-service/administer/configure-copilot-features", title: "Configure Copilot features in Customer Service", questions: 9, bullets: 3 },
          { url: "https://learn.microsoft.com/dynamics365/fin-ops-core/fin-ops/copilot/copilot-for-finance-operations", title: "Copilot in finance and operations apps", questions: 5, bullets: 2 },
          { url: "https://learn.microsoft.com/dynamics365/fin-ops-core/fin-ops/copilot/copilot-generative-help", title: "Generative help and guidance with Copilot", questions: 5, bullets: 2 },
          { url: "https://learn.microsoft.com/dynamics365/contact-center/use/use-ask-a-question", title: "Use Copilot to ask a question in Contact Center", questions: 5, bullets: 1 },
          { url: "https://learn.microsoft.com/dynamics365/sales/copilot-overview", title: "Copilot in Dynamics 365 Sales", questions: 2, bullets: 1 },
          { url: "https://learn.microsoft.com/dynamics365/supply-chain/procurement/procurement-agent-overview", title: "Procurement Agent overview", questions: 1, bullets: 1 },
        ],
      },
      {
        root: "purview", rootUrl: "https://learn.microsoft.com/purview/", label: "Microsoft Purview", questions: 15,
        pages: [
          { url: "https://learn.microsoft.com/purview/ai-microsoft-purview", title: "Microsoft Purview for AI", questions: 15, bullets: 5 },
        ],
      },
      {
        root: "azure/ai-foundry", rootUrl: "https://learn.microsoft.com/azure/ai-foundry/", label: "Foundry (classic paths)", questions: 13,
        pages: [
          { url: "https://learn.microsoft.com/azure/ai-foundry/concepts/fine-tuning-overview", title: "Fine-tuning in Microsoft Foundry", questions: 13, bullets: 4 },
        ],
      },
      {
        root: "microsoft-365-copilot", rootUrl: "https://learn.microsoft.com/microsoft-365-copilot/", label: "Microsoft 365 Copilot extensibility", questions: 12,
        pages: [
          { url: "https://learn.microsoft.com/microsoft-365-copilot/extensibility/agents-are-apps", title: "Agents are apps for Microsoft 365", questions: 6, bullets: 2 },
          { url: "https://learn.microsoft.com/microsoft-365-copilot/extensibility/", title: "Microsoft 365 Copilot extensibility", questions: 6, bullets: 3 },
        ],
      },
      {
        root: "azure/well-architected", rootUrl: "https://learn.microsoft.com/azure/well-architected/", label: "Azure Well-Architected Framework", questions: 7,
        pages: [
          { url: "https://learn.microsoft.com/azure/well-architected/ai/responsible-ai", title: "Responsible AI in the Well-Architected Framework", questions: 7, bullets: 1 },
        ],
      },
      {
        root: "ai-builder", rootUrl: "https://learn.microsoft.com/ai-builder/", label: "AI Builder", questions: 5,
        pages: [
          { url: "https://learn.microsoft.com/ai-builder/overview", title: "AI Builder overview", questions: 5, bullets: 4 },
        ],
      },
      {
        root: "microsoft-sales-copilot", rootUrl: "https://learn.microsoft.com/microsoft-sales-copilot/", label: "Microsoft 365 Copilot for Sales", questions: 3,
        pages: [
          { url: "https://learn.microsoft.com/microsoft-sales-copilot/introduction", title: "Microsoft 365 Copilot for Sales", questions: 3, bullets: 2 },
        ],
      },
      {
        root: "microsoft-copilot-service", rootUrl: "https://learn.microsoft.com/microsoft-copilot-service/", label: "Microsoft 365 Copilot for Service", questions: 2,
        pages: [
          { url: "https://learn.microsoft.com/microsoft-copilot-service/copilot-ask-a-question", title: "Microsoft 365 Copilot for Service", questions: 2, bullets: 1 },
        ],
      },
      {
        root: "microsoft-365", rootUrl: "https://learn.microsoft.com/microsoft-365/", label: "microsoft-365", questions: 1,
        pages: [
          { url: "https://learn.microsoft.com/microsoft-365/copilot/extensibility/agent-builder-share-manage-agents", title: "Share and manage agents", questions: 1, bullets: 1 },
        ],
      },
    ],
    fastPaths: [
      { answers: "Which deployment type, and where data is processed", url: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types", title: "Deployment types for Foundry Models", find: "Data Zone" },
      { answers: "Which Foundry role grants what", url: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry", title: "Role-based access control for Microsoft Foundry", find: "Project Manager" },
      { answers: "Which built-in evaluator measures what", url: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators", title: "Built-in evaluators reference", find: "task adherence" },
      { answers: "Which feature exists in which region", url: "https://learn.microsoft.com/azure/foundry/reference/region-support", title: "Foundry feature availability across regions", find: "the feature name" },
      { answers: "Copilot Studio capacity and message consumption", url: "https://learn.microsoft.com/microsoft-copilot-studio/requirements-messages-management", title: "Copilot Studio capacity and message management", find: "capacity" },
      { answers: "Which connectors a data policy can block", url: "https://learn.microsoft.com/power-platform/admin/wp-data-loss-prevention", title: "Power Platform data loss prevention policies", find: "connector" },
      { answers: "Which AI features exist in which Dynamics 365 app", url: "https://learn.microsoft.com/dynamics365/copilot/ai-get-started", title: "Agents, Copilot, and AI capabilities in Dynamics 365", find: "the app name" },
      { answers: "Which Copilot Studio authentication exposes which variable", url: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication", title: "Configure user authentication", find: "AccessToken" },
    ],
  },
};
