import type { Question, SyllabusRef } from "./questions";

/**
 * AI-103 skills-measured citation for every question in the Northstar and specialty
 * banks, keyed by question id. The q() helpers in advanced-questions and
 * specialty-questions attach these, mirroring how those files already apply
 * id-keyed option overrides.
 *
 * Bullets are verbatim from AI103_SYLLABUS; the question-bank audit fails if a
 * citation drifts from the published outline or if any question lacks one.
 *
 * Note: the SDK and Copilot Studio banks use DomainId as a UI area label rather than
 * an exam domain, so their citations name the exam domain they actually test, which
 * can differ from the area the question is displayed under.
 */
export const QUESTION_REFERENCES: Record<string, SyllabusRef> = {
  "ae-01": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Produce clean, grounded representations to use with agents and RAG by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/quickstart/use-rest-api",
    docTitle: "Quickstart: Use Content Understanding",
  },
  "ae-02": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Extract information by using multimodal pipelines that combine OCR, layout analysis, and field extraction",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/prebuilt-analyzers",
    docTitle: "Prebuilt analyzers in Content Understanding",
  },
  "ae-03": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Extract information by using multimodal pipelines that combine OCR, layout analysis, and field extraction",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/analyzer-reference",
    docTitle: "What is a Content Understanding analyzer?",
  },
  "ae-04": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Produce clean, grounded representations to use with agents and RAG by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/elements",
    docTitle: "Document elements and spans",
  },
  "ae-05": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Implement analyzers for generating structured or markdown outputs for downstream reasoning by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/overview",
    docTitle: "Content Understanding document solutions",
  },
  "ae-06": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Produce clean, grounded representations to use with agents and RAG by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/quickstart/use-rest-api",
    docTitle: "Quickstart: Use Content Understanding",
  },
  "ae-07": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Configure RAG ingestion flow, including documents and using optical character recognition (OCR)",
    docUrl: "https://learn.microsoft.com/azure/storage/blobs/storage-blob-user-delegation-sas-create-cli",
    docTitle: "Create a user delegation SAS",
  },
  "ae-08": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Extract information by using multimodal pipelines that combine OCR, layout analysis, and field extraction",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/overview",
    docTitle: "What is Azure Content Understanding in Foundry Tools?",
  },
  "ae-09": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Ingest and index content, such as documents, images, audio, and video",
    docUrl: "https://learn.microsoft.com/azure/search/search-indexer-overview",
    docTitle: "Indexers in Azure AI Search",
  },
  "ae-10": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Implement enrichment by using custom or built-in skills for text, images, and layout",
    docUrl: "https://learn.microsoft.com/azure/search/cognitive-search-skill-document-intelligence-layout",
    docTitle: "Document Layout skill",
  },
  "ae-11": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Implement enrichment by using custom or built-in skills for text, images, and layout",
    docUrl: "https://learn.microsoft.com/azure/search/search-how-to-define-index-projections",
    docTitle: "Define an index projection",
  },
  "ae-12": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Ingest and index content, such as documents, images, audio, and video",
    docUrl: "https://learn.microsoft.com/azure/search/cognitive-search-common-errors-warnings",
    docTitle: "Indexer errors and warnings",
  },
  "ae-13": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Ingest and index content, such as documents, images, audio, and video",
    docUrl: "https://learn.microsoft.com/azure/search/search-howto-schedule-indexers",
    docTitle: "Schedule an indexer",
  },
  "ae-14": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Configure semantic search, hybrid search, and vector search for grounding",
    docUrl: "https://learn.microsoft.com/azure/search/vector-search-how-to-create-index",
    docTitle: "Create a vector index",
  },
  "ae-15": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Connect retrieval pipelines directly to workflows and agent tools",
    docUrl: "https://learn.microsoft.com/azure/search/search-security-trimming-for-azure-search",
    docTitle: "Security trimming for Azure AI Search",
  },
  "ae-16": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Implement enrichment by using custom or built-in skills for text, images, and layout",
    docUrl: "https://learn.microsoft.com/azure/search/vector-search-integrated-vectorization",
    docTitle: "Integrated vectorization",
  },
  "ae-17": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Ingest and index content, such as documents, images, audio, and video",
    docUrl: "https://learn.microsoft.com/azure/search/search-howto-managed-identities-data-sources",
    docTitle: "Managed identities for indexer connections",
  },
  "ae-18": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Produce clean, grounded representations to use with agents and RAG by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/overview",
    docTitle: "Content Understanding document solutions",
  },
  "ae-19": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Connect retrieval pipelines directly to workflows and agent tools",
    docUrl: "https://learn.microsoft.com/azure/search/search-filters",
    docTitle: "Filters in Azure AI Search",
  },
  "ae-20": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Implement analyzers for generating structured or markdown outputs for downstream reasoning by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/elements",
    docTitle: "Document elements and spans",
  },
  "ae-21": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Ingest and index content, such as documents, images, audio, and video",
    docUrl: "https://learn.microsoft.com/azure/search/multimodal-search-overview",
    docTitle: "Multimodal search in Azure AI Search",
  },
  "ag-01": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "ag-02": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "ag-03": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/agent-applications",
    docTitle: "Agent applications in Microsoft Foundry",
  },
  "ag-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "ag-05": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "ag-06": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/code-interpreter",
    docTitle: "Code Interpreter tool for Foundry agents",
  },
  "ag-07": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/search/agentic-retrieval-overview",
    docTitle: "Agentic retrieval in Azure AI Search",
  },
  "ag-08": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/toolbox",
    docTitle: "Foundry Toolbox",
  },
  "ag-09": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/vector-search-integrated-vectorization",
    docTitle: "Integrated vectorization",
  },
  "ag-10": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/hybrid-search-overview",
    docTitle: "Hybrid search in Azure AI Search",
  },
  "ag-11": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/semantic-search-overview",
    docTitle: "Semantic ranking in Azure AI Search",
  },
  "ag-12": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/hybrid-search-how-to-query",
    docTitle: "Create a hybrid query",
  },
  "ag-13": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/vector-search-how-to-query",
    docTitle: "Create a vector query",
  },
  "ag-14": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/vector-search-how-to-configure-vectorizer",
    docTitle: "Configure a vectorizer",
  },
  "ag-15": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/semantic-how-to-configure",
    docTitle: "Configure semantic ranking",
  },
  "ag-16": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/search-query-overview",
    docTitle: "Query types and composition",
  },
  "ag-17": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/search-security-trimming-for-azure-search",
    docTitle: "Security trimming for Azure AI Search",
  },
  "ag-18": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Tune generation behavior, such as prompt engineering and adjusting model parameters",
    docUrl: "https://learn.microsoft.com/azure/search/agentic-retrieval-overview",
    docTitle: "Agentic retrieval in Azure AI Search",
  },
  "ag-19": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "ag-20": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/overview",
    docTitle: "Microsoft Foundry Agent Service",
  },
  "ag-21": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/agent-framework/integrations/by-component/agent-services/foundry",
    docTitle: "Foundry Agent Service in Agent Framework",
  },
  "ag-22": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/agent-framework/integrations/by-component/agent-services/foundry",
    docTitle: "Foundry Agent Service in Agent Framework",
  },
  "ag-23": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
    docUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process",
    docTitle: "Process to build agents across your organization",
  },
  "ag-24": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "ag-25": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators",
    docTitle: "Built-in evaluators reference",
  },
  "ag-26": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/evaluation-evaluators/agent-evaluators",
    docTitle: "Agent evaluators",
  },
  "ag-27": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators",
    docTitle: "Built-in evaluators reference",
  },
  "ag-28": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Design workflows, tool-augmented flows, and multistep reasoning pipelines",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs",
    docTitle: "Structured outputs",
  },
  "ag-29": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Orchestrate multiple models, flows, or hybrid LLM and rules engines",
    docUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/governance-security-across-organization",
    docTitle: "Governance and security for AI agents",
  },
  "ag-30": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Implement model reflection, chain-of-thought evaluations, and self-critique loops",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/observability",
    docTitle: "Observability in generative AI",
  },
  "ag-31": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "ag-32": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Orchestrate multiple models, flows, or hybrid LLM and rules engines",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/model-router",
    docTitle: "Model router for Microsoft Foundry",
  },
  "ag-33": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/search/retrieval-augmented-generation-overview",
    docTitle: "RAG in Azure AI Search",
  },
  "ag-34": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection",
    docTitle: "Prompt Shields",
  },
  "ag-35": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/groundedness",
    docTitle: "Groundedness detection",
  },
  "ag-36": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry",
    docTitle: "Role-based access control for Microsoft Foundry",
  },
  "ag-37": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "ag-38": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Design workflows, tool-augmented flows, and multistep reasoning pipelines",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/overview",
    docTitle: "What is Azure Content Understanding in Foundry Tools?",
  },
  "ag-39": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "ag-40": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators",
    docTitle: "Built-in evaluators reference",
  },
  "ag-41": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "al-01": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Configure detection of sentiment, tone, safety issues, and sensitive content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/language-service/sentiment-opinion-mining/overview",
    docTitle: "Sentiment analysis and opinion mining",
  },
  "al-02": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Configure detection of sentiment, tone, safety issues, and sensitive content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/language-service/personally-identifiable-information/overview",
    docTitle: "Detect personally identifiable information",
  },
  "al-03": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Implement solutions to extract entities, topics, summaries, and structured JSON outputs by using generative prompting and Foundry Tools",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs",
    docTitle: "Structured outputs",
  },
  "al-04": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Customize language model outputs for domain tasks, such as compliance summarization and domain extraction",
    docUrl: "https://learn.microsoft.com/azure/ai-services/language-service/custom-text-classification/overview",
    docTitle: "Custom text classification",
  },
  "al-05": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Build solutions that translate text by using Azure Translator in Foundry Tools or LLM‑powered translation flows",
    docUrl: "https://learn.microsoft.com/azure/ai-services/translator/translator-overview",
    docTitle: "What is Azure Translator in Foundry Tools?",
  },
  "al-06": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Build solutions that translate text by using Azure Translator in Foundry Tools or LLM‑powered translation flows",
    docUrl: "https://learn.microsoft.com/azure/ai-services/translator/document-translation/overview",
    docTitle: "Document translation",
  },
  "al-07": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Build solutions that translate text by using Azure Translator in Foundry Tools or LLM‑powered translation flows",
    docUrl: "https://learn.microsoft.com/azure/ai-services/translator/custom-translator/overview",
    docTitle: "Custom Translator",
  },
  "al-08": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Implement solutions to extract entities, topics, summaries, and structured JSON outputs by using generative prompting and Foundry Tools",
    docUrl: "https://learn.microsoft.com/azure/ai-services/language-service/language-detection/overview",
    docTitle: "Language detection",
  },
  "al-09": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-to-text",
    docTitle: "Speech to text",
  },
  "al-10": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/fast-transcription-create",
    docTitle: "Fast transcription",
  },
  "al-11": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/batch-transcription",
    docTitle: "Batch transcription",
  },
  "al-12": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/get-started-stt-diarization",
    docTitle: "Real-time diarization",
  },
  "al-13": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Integrate speech as an agent modality, including custom speech models",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/language-identification",
    docTitle: "Language identification with Speech",
  },
  "al-14": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Translate speech into other languages by using language models and Foundry Tools",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-translation",
    docTitle: "Speech translation",
  },
  "al-15": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-synthesis-markup",
    docTitle: "Speech Synthesis Markup Language",
  },
  "al-16": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Integrate speech as an agent modality, including custom speech models",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/improve-accuracy-phrase-list",
    docTitle: "Improve recognition accuracy with phrase lists",
  },
  "al-17": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Integrate speech as an agent modality, including custom speech models",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "al-18": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Build solutions that translate text by using Azure Translator in Foundry Tools or LLM‑powered translation flows",
    docUrl: "https://learn.microsoft.com/azure/ai-services/translator/translator-overview",
    docTitle: "What is Azure Translator in Foundry Tools?",
  },
  "al-19": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Configure detection of sentiment, tone, safety issues, and sensitive content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/language-service/personally-identifiable-information/overview",
    docTitle: "Detect personally identifiable information",
  },
  "al-20": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Apply language model text analysis",
    bullet: "Customize language model outputs for domain tasks, such as compliance summarization and domain extraction",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/structured-outputs",
    docTitle: "Structured outputs",
  },
  "ap-01": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry",
    docTitle: "Role-based access control for Microsoft Foundry",
  },
  "ap-02": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry",
    docTitle: "Role-based access control for Microsoft Foundry",
  },
  "ap-03": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry",
    docTitle: "Role-based access control for Microsoft Foundry",
  },
  "ap-04": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry",
    docTitle: "Role-based access control for Microsoft Foundry",
  },
  "ap-05": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/search/search-security-rbac",
    docTitle: "Connect to Azure AI Search using roles",
  },
  "ap-06": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Choose appropriate deployment options",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
    docTitle: "Deployment types for Microsoft Foundry Models",
  },
  "ap-07": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Choose appropriate deployment options",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
    docTitle: "Deployment types for Microsoft Foundry Models",
  },
  "ap-08": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Choose appropriate deployment options",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
    docTitle: "Deployment types for Microsoft Foundry Models",
  },
  "ap-09": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/provisioned-throughput",
    docTitle: "What is provisioned throughput for Foundry Models?",
  },
  "ap-10": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits",
    docTitle: "Foundry Models quotas and limits",
  },
  "ap-11": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Configure model and agent deployments",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
    docTitle: "Deployment types for Microsoft Foundry Models",
  },
  "ap-12": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "ap-13": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "ap-14": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Monitor model performance, drift, safety events, and grounding quality",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "ap-15": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard",
    docTitle: "Monitor agents with the Agent Monitoring Dashboard",
  },
  "ap-16": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Implement auditing through trace logging, provenance metadata, and approval workflows",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "ap-17": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Configure safety filters, guardrails, risk detection, and content moderation",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection",
    docTitle: "Prompt Shields",
  },
  "ap-18": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/evaluation-evaluators/agent-evaluators",
    docTitle: "Agent evaluators",
  },
  "ap-19": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Monitor model performance, drift, safety events, and grounding quality",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/groundedness",
    docTitle: "Groundedness detection",
  },
  "ap-20": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard",
    docTitle: "Monitor agents with the Agent Monitoring Dashboard",
  },
  "ap-21": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
    docTitle: "Run evaluations in the cloud by using the Foundry SDK",
  },
  "ap-22": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Design Azure infrastructure for AI apps and agent-based solutions",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
    docTitle: "Create a project for Microsoft Foundry",
  },
  "ap-23": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Choose the appropriate Foundry services for generative AI and agents",
    bullet: "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/evaluate-generative-ai-app",
    docTitle: "Run evaluations from the Microsoft Foundry portal",
  },
  "ap-24": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits",
    docTitle: "Foundry Models quotas and limits",
  },
  "ap-25": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/manage-costs",
    docTitle: "Plan and manage costs for Microsoft Foundry",
  },
  "ap-26": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/search/search-security-rbac",
    docTitle: "Connect to Azure AI Search using roles",
  },
  "ap-27": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "ap-28": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "ap-29": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Implement auditing through trace logging, provenance metadata, and approval workflows",
    docUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/content-filters",
    docTitle: "Configure content filters",
  },
  "ap-30": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Design Azure infrastructure for AI apps and agent-based solutions",
    docUrl: "https://learn.microsoft.com/azure/foundry/reference/region-support",
    docTitle: "Feature availability across cloud regions",
  },
  "ap-31": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Choose the appropriate Foundry services for generative AI and agents",
    bullet: "Choose appropriate memory, tool, and knowledge integration services for agent solutions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/what-is-foundry-iq",
    docTitle: "What is Foundry IQ?",
  },
  "av-01": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Implement a solution that generates images from text prompts and reference media",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/dall-e",
    docTitle: "Generate images with Foundry Models",
  },
  "av-02": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Configure image-editing workflows, including inpainting, mask‑based edits, and prompt‑driven modifications",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/dall-e",
    docTitle: "Generate images with Foundry Models",
  },
  "av-03": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Select and apply appropriate generation and editing controls provided by the platform",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/dall-e",
    docTitle: "Generate images with Foundry Models",
  },
  "av-04": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Implement filters to classify unsafe or disallowed visual content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/overview",
    docTitle: "What is Azure AI Content Safety?",
  },
  "av-05": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Enforce visual policy rules, such as applying watermarks, flagging prohibited symbols, upholding brand usage requirements, and detecting potentially inappropriate content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/custom-categories",
    docTitle: "Custom categories in Azure AI Content Safety",
  },
  "av-06": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Detect and mitigate indirect prompt injection by using embedded text in images",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection",
    docTitle: "Prompt Shields",
  },
  "av-07": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Implement filters to classify unsafe or disallowed visual content",
    docUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/content-filters",
    docTitle: "Configure content filters",
  },
  "av-08": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Enforce visual policy rules, such as applying watermarks, flagging prohibited symbols, upholding brand usage requirements, and detecting potentially inappropriate content",
    docUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/content-filters",
    docTitle: "Configure content filters",
  },
  "av-09": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Enforce visual policy rules, such as applying watermarks, flagging prohibited symbols, upholding brand usage requirements, and detecting potentially inappropriate content",
    docUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/content-filters",
    docTitle: "Configure content filters",
  },
  "av-10": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Select and apply appropriate generation and editing controls provided by the platform",
    docUrl: "https://learn.microsoft.com/azure/storage/blobs/storage-blob-user-delegation-sas-create-cli",
    docTitle: "Create a user delegation SAS",
  },
  "av-11": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement multimodal understanding workflows",
    bullet: "Build a solution that analyzes visual context by using multimodal models",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "av-12": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Configure image-editing workflows, including inpainting, mask‑based edits, and prompt‑driven modifications",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/built-in-evaluators",
    docTitle: "Built-in evaluators reference",
  },
  "av-13": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Implement a solution that generates videos from text prompts and reference media",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/video-generation",
    docTitle: "Video generation with Sora 2",
  },
  "av-14": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Implement workflows to edit generated videos",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/video-generation",
    docTitle: "Video generation with Sora 2",
  },
  "av-15": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Enforce visual policy rules, such as applying watermarks, flagging prohibited symbols, upholding brand usage requirements, and detecting potentially inappropriate content",
    docUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/content-filters",
    docTitle: "Configure content filters",
  },
  "av-16": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement multimodal understanding workflows",
    bullet: "Implement visual understanding by configuring Azure Content Understanding in Foundry Tools to extract visual characteristics",
    docUrl: "https://learn.microsoft.com/azure/search/multimodal-search-overview",
    docTitle: "Multimodal search in Azure AI Search",
  },
  "av-17": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement multimodal understanding workflows",
    bullet: "Implement visual understanding by configuring Azure Content Understanding in Foundry Tools to extract visual characteristics",
    docUrl: "https://learn.microsoft.com/azure/search/vector-search-how-to-configure-vectorizer",
    docTitle: "Configure a vectorizer",
  },
  "av-18": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Configure image-editing workflows, including inpainting, mask‑based edits, and prompt‑driven modifications",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/dall-e",
    docTitle: "Generate images with Foundry Models",
  },
  "av-19": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Detect and mitigate indirect prompt injection by using embedded text in images",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection",
    docTitle: "Prompt Shields",
  },
  "av-20": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Detect and mitigate indirect prompt injection by using embedded text in images",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection",
    docTitle: "Prompt Shields",
  },
  "av-21": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Enforce visual policy rules, such as applying watermarks, flagging prohibited symbols, upholding brand usage requirements, and detecting potentially inappropriate content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/custom-categories",
    docTitle: "Custom categories in Azure AI Content Safety",
  },
  "cs-01": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/advanced-generative-actions",
    docTitle: "Generative orchestration in Copilot Studio",
  },
  "cs-02": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/advanced-generative-actions",
    docTitle: "Generative orchestration in Copilot Studio",
  },
  "cs-03": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent",
    docTitle: "Use tools with custom agents",
  },
  "cs-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/advanced-generative-actions",
    docTitle: "Generative orchestration in Copilot Studio",
  },
  "cs-05": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Connect retrieval pipelines directly to workflows and agent tools",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-copilot-studio",
    docTitle: "Knowledge sources in Copilot Studio",
  },
  "cs-06": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/agent-extend-action-mcp",
    docTitle: "Extend an agent with Model Context Protocol",
  },
  "cs-07": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Connect retrieval pipelines directly to workflows and agent tools",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-copilot-studio",
    docTitle: "Knowledge sources in Copilot Studio",
  },
  "cs-08": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Govern agent behavior with oversight modes, constraints, and tool-access controls",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/knowledge-add-dataverse",
    docTitle: "Add Dataverse as a knowledge source",
  },
  "cs-09": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication",
    docTitle: "Configure user authentication",
  },
  "cs-10": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication",
    docTitle: "Configure user authentication",
  },
  "cs-11": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/publication-fundamentals-publish-channels",
    docTitle: "Publish your agent",
  },
  "cs-12": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication",
    docTitle: "Configure user authentication",
  },
  "cs-13": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/configuration-end-user-authentication",
    docTitle: "Configure user authentication",
  },
  "cs-14": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Govern agent behavior with oversight modes, constraints, and tool-access controls",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/admin-data-loss-prevention",
    docTitle: "Configure data policies for agents",
  },
  "cs-15": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-create-edit-topics",
    docTitle: "Create and edit topics",
  },
  "cs-16": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/add-tools-custom-agent",
    docTitle: "Use tools with custom agents",
  },
  "cs-17": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/flows-overview",
    docTitle: "Agent flows overview",
  },
  "cs-18": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/requirements-messages-management",
    docTitle: "Copilot Studio capacity and message management",
  },
  "cs-19": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-solutions-overview",
    docTitle: "Solutions and ALM in Copilot Studio",
  },
  "cs-20": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
    docUrl: "https://learn.microsoft.com/power-apps/maker/data-platform/environmentvariables",
    docTitle: "Environment variables overview",
  },
  "cs-21": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Monitor model performance, drift, safety events, and grounding quality",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-overview",
    docTitle: "Copilot Studio analytics overview",
  },
  "cs-22": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/analytics-agent-evaluation-intro",
    docTitle: "About agent evaluation",
  },
  "cs-23": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-test-bot",
    docTitle: "Test an agent",
  },
  "cs-24": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/security-and-governance",
    docTitle: "Copilot Studio security and governance",
  },
  "cs-25": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/guidance/autonomous-agents",
    docTitle: "Design autonomous agent capabilities",
  },
  "cs-26": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
    docUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process",
    docTitle: "Process to build agents across your organization",
  },
  "cs-27": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-add-other-agents",
    docTitle: "Add other agents overview",
  },
  "cs-28": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-system-topics",
    docTitle: "Use system topics",
  },
  "cs-29": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Define agent roles, goals, conversation-tracking approach, and tool schemas",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/authoring-variables",
    docTitle: "Work with variables",
  },
  "cs-30": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Implement auditing through trace logging, provenance metadata, and approval workflows",
    docUrl: "https://learn.microsoft.com/microsoft-copilot-studio/admin-logging-copilot-studio",
    docTitle: "View Copilot Studio audit logs",
  },
  "cx-banking-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/evaluation-evaluators/agent-evaluators",
    docTitle: "Agent evaluators",
  },
  "cx-energy-01": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Choose appropriate deployment options",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
    docTitle: "Deployment types for Microsoft Foundry Models",
  },
  "cx-energy-02": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "cx-energy-03": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Detect and mitigate indirect prompt injection by using embedded text in images",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/concepts/jailbreak-detection",
    docTitle: "Prompt Shields",
  },
  "cx-energy-04": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Monitor model performance, drift, safety events, and grounding quality",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "cx-factory-04": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Ingest and index content, such as documents, images, audio, and video",
    docUrl: "https://learn.microsoft.com/azure/search/cognitive-search-common-errors-warnings",
    docTitle: "Indexer errors and warnings",
  },
  "cx-healthcare-04": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Connect retrieval pipelines directly to workflows and agent tools",
    docUrl: "https://learn.microsoft.com/azure/search/search-how-to-define-index-projections",
    docTitle: "Define an index projection",
  },
  "cx-insurance-01": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Extract information by using multimodal pipelines that combine OCR, layout analysis, and field extraction",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/overview",
    docTitle: "Content Understanding document solutions",
  },
  "cx-insurance-02": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Implement responsible AI for multimodal content",
    bullet: "Implement filters to classify unsafe or disallowed visual content",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-safety/overview",
    docTitle: "What is Azure AI Content Safety?",
  },
  "cx-insurance-03": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build autonomous or semiautonomous workflows with safeguards and approval flow controls",
    docUrl: "https://learn.microsoft.com/azure/cloud-adoption-framework/ai-agents/build-secure-process",
    docTitle: "Process to build agents across your organization",
  },
  "cx-insurance-04": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Implement responsible AI across generative AI and agentic systems",
    bullet: "Implement auditing through trace logging, provenance metadata, and approval workflows",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "cx-legal-04": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Extract information by using multimodal pipelines that combine OCR, layout analysis, and field extraction",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/concepts/analyzer-reference",
    docTitle: "What is a Content Understanding analyzer?",
  },
  "cx-logistics-01": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Extract content from documents",
    bullet: "Implement analyzers for generating structured or markdown outputs for downstream reasoning by using Content Understanding",
    docUrl: "https://learn.microsoft.com/azure/ai-services/content-understanding/document/elements",
    docTitle: "Document elements and spans",
  },
  "cx-logistics-02": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "cx-logistics-03": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/agent-framework/integrations/by-component/agent-services/foundry",
    docTitle: "Foundry Agent Service in Agent Framework",
  },
  "cx-logistics-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "cx-media-04": {
    domain: "Implement computer vision solutions (10–15%)",
    skill: "Design and implement image- and video-generation solutions",
    bullet: "Implement a solution that generates videos from text prompts and reference media",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/concepts/video-generation",
    docTitle: "Video generation with Sora 2",
  },
  "cx-retail-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "cx-support-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/hybrid-search-overview",
    docTitle: "Hybrid search in Azure AI Search",
  },
  "cx-travel-04": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Integrate speech as an agent modality, including custom speech models",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/language-identification",
    docTitle: "Language identification with Speech",
  },
  "cx-university-01": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-to-text",
    docTitle: "Speech to text",
  },
  "cx-university-02": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Translate speech into other languages by using language models and Foundry Tools",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/speech-translation",
    docTitle: "Speech translation",
  },
  "cx-university-03": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Implement retrieval-augmented generation (RAG) in an application",
    docUrl: "https://learn.microsoft.com/azure/search/search-security-trimming-for-azure-search",
    docTitle: "Security trimming for Azure AI Search",
  },
  "cx-university-04": {
    domain: "Implement text analysis solutions (10–15%)",
    skill: "Implement speech solutions",
    bullet: "Implement workflows to convert speech to text and text to speech for agentic interactions",
    docUrl: "https://learn.microsoft.com/azure/ai-services/speech-service/batch-transcription",
    docTitle: "Batch transcription",
  },
  "sdk-01": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
    docTitle: "Create a project for Microsoft Foundry",
  },
  "sdk-02": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-03": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-04": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-05": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-06": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-07": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-08": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Configure model and agent deployments",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/concepts/deployment-types",
    docTitle: "Deployment types for Microsoft Foundry Models",
  },
  "sdk-09": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-10": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-11": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-12": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-13": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "sdk-14": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Deploy and consume LLMs, small models, code models, and multimodal models",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-15": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "sdk-16": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
    docTitle: "Create a project for Microsoft Foundry",
  },
  "sdk-17": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
    docTitle: "Create a project for Microsoft Foundry",
  },
  "sdk-18": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "sdk-19": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "sdk-20": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/rbac-foundry",
    docTitle: "Role-based access control for Microsoft Foundry",
  },
  "sdk-21": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/create-projects",
    docTitle: "Create a project for Microsoft Foundry",
  },
  "sdk-22": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "sdk-23": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-24": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
    docTitle: "Run evaluations in the cloud by using the Foundry SDK",
  },
  "sdk-25": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
    docTitle: "Run evaluations in the cloud by using the Foundry SDK",
  },
  "sdk-26": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
    docTitle: "Run evaluations in the cloud by using the Foundry SDK",
  },
  "sdk-27": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
    docTitle: "Run evaluations in the cloud by using the Foundry SDK",
  },
  "sdk-28": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/develop/cloud-evaluation",
    docTitle: "Run evaluations in the cloud by using the Foundry SDK",
  },
  "sdk-29": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/how-to-monitor-agents-dashboard",
    docTitle: "Monitor agents with the Agent Monitoring Dashboard",
  },
  "sdk-30": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety",
    docUrl: "https://learn.microsoft.com/azure/foundry/how-to/evaluate-generative-ai-app",
    docTitle: "Run evaluations from the Microsoft Foundry portal",
  },
  "sdk-31": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/agent-framework/integrations/by-component/agent-services/foundry",
    docTitle: "Foundry Agent Service in Agent Framework",
  },
  "sdk-32": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Implement orchestrated multi-agent solutions",
    docUrl: "https://learn.microsoft.com/agent-framework/integrations/by-component/agent-services/foundry",
    docTitle: "Foundry Agent Service in Agent Framework",
  },
  "sdk-33": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "sdk-34": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "sdk-35": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads",
    docUrl: "https://learn.microsoft.com/azure/foundry/foundry-models/quotas-limits",
    docTitle: "Foundry Models quotas and limits",
  },
  "sdk-36": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Manage, monitor, and secure AI systems",
    bullet: "Configure security, including managed identity, private networking, keyless credentials, and role policies",
    docUrl: "https://learn.microsoft.com/azure/foundry/concepts/authentication-authorization-foundry",
    docTitle: "Authentication and authorization in Microsoft Foundry",
  },
  "sdk-37": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-38": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-39": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-40": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Build agents that integrate retrieval, function-calling, and conversation memory",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "sdk-41": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/concepts/tool-best-practice",
    docTitle: "Best practices for using tools in Foundry Agent Service",
  },
  "sdk-42": {
    domain: "Implement information extraction solutions (10–15%)",
    skill: "Build retrieval and grounding pipelines",
    bullet: "Connect retrieval pipelines directly to workflows and agent tools",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/file-search",
    docTitle: "File search tool for agents",
  },
  "sdk-43": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build agents by using Foundry",
    bullet: "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions",
    docUrl: "https://learn.microsoft.com/azure/foundry/agents/how-to/tools/code-interpreter",
    docTitle: "Code Interpreter tool for Foundry agents",
  },
  "sdk-44": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Configure an application to connect to a Foundry project",
    docUrl: "https://learn.microsoft.com/azure/foundry/openai/how-to/responses",
    docTitle: "Responses API in Microsoft Foundry",
  },
  "sdk-45": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Optimize and operationalize generative AI systems",
    bullet: "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns",
    docUrl: "https://learn.microsoft.com/azure/foundry/observability/how-to/trace-agent-setup",
    docTitle: "How to set up tracing in Microsoft Foundry",
  },
  "sdk-46": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-47": {
    domain: "Plan and manage an Azure AI solution (25–30%)",
    skill: "Set up AI solutions in Foundry",
    bullet: "Integrate Foundry projects with continuous integration and continuous deployment (CI/CD) pipelines",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-48": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-49": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
  "sdk-50": {
    domain: "Implement generative AI and agentic solutions (30–35%)",
    skill: "Build generative applications by using Foundry",
    bullet: "Integrate generative workflows into applications by using Foundry SDKs and connectors",
    docUrl: "https://learn.microsoft.com/azure/foundry/quickstarts/get-started-code",
    docTitle: "Get started with the Microsoft Foundry SDK",
  },
};

// Additional specialty scenarios reuse the same published objective and Learn
// page as the closely related capability they extend. Keeping these aliases here
// avoids duplicating citation text while ensuring every shipped question still
// resolves to a complete, audited reference.
const SPECIALTY_REFERENCE_ALIASES: Record<string, string> = {
  "sdk-51": "sdk-40",
  "sdk-52": "sdk-38",
  "sdk-53": "sdk-07",
  "sdk-54": "sdk-39",
  "sdk-55": "sdk-39",
  "sdk-56": "sdk-40",
  "sdk-57": "sdk-40",
  "sdk-58": "sdk-45",
  "sdk-59": "sdk-44",
  "sdk-60": "sdk-20",
  "sdk-61": "sdk-20",
  "sdk-62": "sdk-46",
  "sdk-63": "sdk-27",
  "sdk-64": "sdk-24",
  "sdk-65": "sdk-24",
  "sdk-66": "sdk-45",
  "sdk-67": "sdk-45",
  "sdk-68": "sdk-36",
  "sdk-69": "sdk-19",
  "sdk-70": "sdk-13",
  "sdk-71": "sdk-33",
  "sdk-72": "sdk-42",
  "sdk-73": "sdk-41",
  "sdk-74": "sdk-43",
  "sdk-75": "sdk-24",
  "sdk-76": "sdk-35",
  "sdk-77": "sdk-35",
  "sdk-78": "sdk-37",
  "sdk-79": "sdk-38",
  "sdk-80": "sdk-49",
  "cs-31": "cs-15",
  "cs-32": "cs-15",
  "cs-33": "cs-02",
  "cs-34": "cs-29",
  "cs-35": "cs-09",
  "cs-36": "cs-14",
  "cs-37": "cs-20",
  "cs-38": "cs-19",
  "cs-39": "cs-19",
  "cs-40": "cs-19",
  "cs-41": "cs-07",
  "cs-42": "cs-07",
  "cs-43": "cs-08",
  "cs-44": "cs-30",
  "cs-45": "cs-22",
  "cs-46": "cs-21",
  "cs-47": "cs-16",
  "cs-48": "cs-26",
};

for (const [questionId, sourceId] of Object.entries(SPECIALTY_REFERENCE_ALIASES)) {
  QUESTION_REFERENCES[questionId] = QUESTION_REFERENCES[sourceId];
}

/**
 * Attach the AI-103 citation to each question. Both the app (through questions.ts)
 * and the question-bank audit call this, so the audit validates exactly what ships.
 */
export function withReferences(questions: Question[]): Question[] {
  return questions.map((question) => ({ ...question, syllabus: QUESTION_REFERENCES[question.id] }));
}
